### ISSUE TITLE
Refactor the providers to provide more than one source select widget and related configuration

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS-Enhancement-Proposals#101]
# QGIS Enhancement: Refactor the providers to provide more than one source select widget and related configuration

**Date** 2017/08/15

**Author** Alessandro Pasotti

**Contact** apasotti at boundlessgeo dot com

**maintainer** apasotti at boundlessgeo dot com

**Version** QGIS 3

# Summary

## The problem

Most providers have a `QGISEXTERN QgsWMSSourceSelect *selectWidget` that is called whenever we need to build a GUI to manage the provider's data sources.
This function returns a single widget but some providers **need more than one** (WMS is an example: that needs XYZ and the standard WMS widgets, but I have another use case for ogr/gdal and the specialized geopackage dialog).
The new geonode PR is another use case.

There are several points in the GUI where we would benefit to a central registry for provider's GUI widgets:
- the layers menu: to create menu item that point to the data source select (Layer -> Add layer -> Add ....)
- the add layer dialog: iterate through the providers and get the menus (we would need a priority here to sort the items in a meaningful way)
- the layer button bar

## Proposed Solution

A similar problem for the browser tree was solved in an elegant way and I think that we should follow the same route taken by the browser tree root nodes ( that uses QgsDataItemProvider and QgsDataItemProviderRegistry ) by creating new classes QgsSourceSelectProvider and QgsSourceSelectProviderRegistry .

See: https://www.qgis.org/api/classQgsDataItemProviderRegistry.html

A provider or a plugin (C++, Python etc.) will then be able to provide any number of source select interfaces (probably keyed in some way so that we can retrieve the right one by key in case we need it).

This would replace/extend the actual source select function selectWidget

Another possible approach (maybe simpler but I did not check all the implications) would be to refactor the selectWidget to return a list of instances/structs that would include for each item:

- the widget
- the label
- the svg icon for the unified dialog and menus
- a priority to allow for sorting/ordering

### Affected Files

- Core: new classes for the `QgsSourceSelectProvider` and `QgsSourceSelectProviderRegistry`
Providers

## Performance Implications

None

## Backwards Compatibility

No issues

## Votes

(required)

**Comment by jef-n** [comment]
There also is the entry point `QGISEXTERN void registerGui( QMainWindow *mainWindow )` called from `QgsProviderRegistry::registerGuis()`, that allows providers to add any UI.

**Comment by elpaso** [comment]
@jef-n thanks, I didn't notice that. That entry point is useful but I think we need something more structured and specific to handle the data source selects. 

The goal is to be able to loop through the `QgsSourceSelectProviderRegistry` from the unified add layer dialog and get all the GUI elements we need for the individual source select dialogs.

Providers and plugins would be able to add source selects to the registry and hence to the unified add layer dialog (and possibly menus and button bars).

**Comment by nyalldawson** [comment]
Sounds good to me, +1

**Comment by luipir** [comment]
+1 for me too

**Comment by elpaso** [comment]
Implemented: https://github.com/qgis/QGIS/pull/5124

**Comment by nyalldawson** [comment]
@NathanW2 another one which can be marked off
