### ISSUE TITLE
Welcome page improvements

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#102]
# QGIS Enhancement: Welcome page improvements

**Date** 2017/08/31

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall.dawson@gmail.com

**Version** QGIS 3.0

# Summary

Following up on discussion at the recent QGIS developer meetup in August, this QEP covers the options discussed for enhancing the current welcome screen to improve the new user experience for QGIS 3.0.

## Proposal

The proposal is to split the current welcome dialog, which shows just recent projects, into 3 sections.

### Section 1: Recent projects

This section will consist of the current recent projects list (with thumbnails and other details) as has been used in QGIS 2.x. It will ONLY be shown when a user has at least 1 recent project - so for the first startup of a new QGIS install this pane will not be shown.

### Section 2: Project templates

The second section in the welcome page will consist of a list (with thumbnails) of available project templates.

Additionally, an item will be added to the templates section for "new blank project". If selected, this will create a totally empty QGIS project.

While QGIS 2.x includes some support for project templates (available through the Project->New From Template menu item), this will be enhanced for 3.0. The proposal is to follow a similar approach as the existing composer templates support, allowing users to setup multiple template paths which will all be searched through when determining available templates to show. Initially, the template path list will consist of 

- Templates included with the default install (e.g. "C:\Program Files\QGIS\apps\qgis\templates")
- User config folder templates (e.g. "C:/Users/Me/.qgis3/templates" or equivalent)

Users can add additional paths to this list through the options dialog, and enterprise installs may wish to include some additional paths in their install packages too.

Users can also manually remove these paths, such as removing the default install templates path if desired.

QGIS 3.0 will ship with some preinstalled templates, each consisting of a project containing a single OpenStreetMap XYZ layer.

This will allow new users to startup QGIS, and instantly be presented with some options to create a simple map containing some content. Because new installs will not show the recent projects option (as noted above, it's hidden when no recent projects are available), they will instead see just the templates panel containing the preinstalled OSM maps (with pretty thumbnails!) and the "blank project" option.

### Section 3: QGIS news

When the new welcome page was first introduced, it included support for showing the content from the QGIS blog. This was later reverted, due to:

1. Ugly default appearance of the blog feed
2. The infrequent updates to the blog meant that the same content was continually being shown
3. There was no way to filter what content would be shown to users
4. Privacy concerns due to "phoning home"

It is proposed that this news feed support be resurrected and enhanced.

The discussion at Nødebo had the conclusions:

- The news feed should only be shown whenever a new piece of news content is available. If no new news is available, we do not show the news panel
- The feed would be pulled from a "curated" category on the QGIS blog - e.g. it will not containing all blog posts, only those manually tagged for inclusion in the feed.
- The news feed can be disabled via a QSettings key (for enterprise/offline installs/those concerned about phone home behavior etc)
- An option is added in the feed panel to "never show QGIS news items"

## Related UI changes

Some additional UI changes would also be introduced to complement the new welcome page:

- The "new project" action will reopen the welcome page, but show only the project templates section (including the 'blank project' option). The behavior of the welcome page is to hide as soon as a layer is added or other change is made to the project, so display of this page does not force any additional "clicks" to the process of creating a new project

- A "close project" action is added to the project menu. Selecting this will close the current project (by creating a new blank project) and reopens the welcome page, showing all suitable panels (recent projects, project templates and news)

## Votes

(required)

**Comment by nirvn** [comment]
While we're at it, it'd be good to implement a right-click menu for the recent projects to manually remove recent project(s) from the list. The right-click menu can also be used to manually remove templates. 

Glad to see this proposal popping up.

**Comment by m-kuhn** [comment]
Nice proposal, very much in favor

> The "new project" action will reopen the welcome page, but show only the project templates section (including the 'blank project' option). The behavior of the welcome page is to hide as soon as a layer is added or other change is made to the project, so display of this page does not force any additional "clicks" to the process of creating a new project

If you are already on the welcome page and click the "new project" button in the menu, it should open an empty canvas or some people will be very surprised.

We need a "save as template" checkbox to the "save project as" dialog which sends it to `[profile folder]/templates`

> While we're at it, it'd be good to implement a right-click menu for the recent projects to manually remove recent project(s) from the list. The right-click menu can also be used to manually remove templates.

And a "pin to top" or "favorite" checkbox. And I'm in favor of a more options icon ![More Options Icon](https://cdn3.iconfinder.com/data/icons/fanaticons/100/More-16.png) in the top right corner in addition to the right click context menu.

**Comment by nyalldawson** [comment]
> We need a "save as template" checkbox to the "save project as" dialog which sends it to [profile folder]/templates

Ok, so long as it's not added IN the dialog (which would force the disgusting, useless Qt save file dialog)

**Comment by elpaso** [comment]
@nyalldawson glad to see this proposal! 

A few notes:

- Can we expose the welcome page to iface so that plugins can change/remove or even add their own tabs?
- I see that an option to disable the new is foreseen, but just to make sure please keep in mind that every network-accessing action in the tabs can be disabled in the (Q)Settings

> QGIS 3.0 will ship with some preinstalled templates, each consisting of a project containing a single OpenStreetMap XYZ layer.

Cool! Would this supercede https://github.com/qgis/QGIS/pull/5000 ?

**Comment by nyalldawson** [comment]
>>QGIS 3.0 will ship with some preinstalled templates, each consisting of a project containing a single OpenStreetMap XYZ layer.
>Cool! Would this supercede qgis/QGIS#5000 ?

I don't think so - there's still strong arguments for having out of the box connections available so that OSM layers can be added to existing projects.

**Comment by nyalldawson** [comment]
> Can we expose the welcome page to iface so that plugins can change/remove or even add their own tabs?

That could be added in a future followup. But I'd be concerned about abuse ("A new version of super-map-processer plugin is available, featuring Swahili translation updates!!!1!!" ;) ).

Other followups (post 3.0) could include:
- build in IP based geolocation, and have the default included projects use this to center the map on a reasonable location for the user
- following on that, we could potentially auto-select a reasonable projection based on this area (for now the projects would either be 4326/3857 - neither of which are ideal)

**Comment by pcav** [comment]
Very much in favour, +1 from me.

**Comment by haubourg** [comment]
Nice! 
I remember discussing the possibility to change the rss feed in Qsettings . This would be really usefull for enterprises or project to keep their users informed of important news. We had that idea we coding the rss plugin, and experiencing user to not read anything unless it's right on the landing page . 
A versatile option would be to allow aggregating several feeds.

**Comment by luipir** [comment]
I really like Templates and (configurable) project news... it would make sense to have also a list of startup profiles (that dev by @NathanW2).
I strongly agree also to access landing page from iface (ok in a second phase)

**Comment by elpaso** [comment]
@haubourg I believe that every URL must go in the QggsSettings.

**Comment by timlinux** [comment]
We discussed this at Nødebo - I think it will be a HUGE plus if we can reach out to our users. Here is a little moqup I made:

<img width="985" alt="screen shot 2017-09-06 at 11 07 32 pm" src="https://user-images.githubusercontent.com/178003/30134709-572cda86-9358-11e7-9dc1-72f9e4d25978.png">

Moqup here:

https://app.moqups.com/tim@kartoza.com/jIMJwEHpV4/view/page/aa9df7b72

Feel free to pop me a note and I will give you edit access to tweak the moqup:

**Comment by NathanW2** [comment]
+1 good idea.

One thing I think we need to address after 3.0 is putting the widget in the
same place as the canvas.  If you have a lot of docks, toolbars, etc then
you have limit room to show this widget making it look less then ideal.

I think a possible solution isnested QMainWIndows with a main "app" one and
then another one for the normal stuff and docks. This means we can have
docks, tabs, etc at a higher level in the app and switch between them

**Comment by timlinux** [comment]
What about if we j

**Comment by haubourg** [comment]
> Feel free to pop me a note and I will give you edit access to tweak the moqup:

Nice that moqup tool! Godd job. I would rename "Project news" to "News" if we make it customizable with various RSS feeds. 

Not sure if QT makes it easy, new modern apps tend to propose some greyed out transparent overlay for startup screen or assistants. It might be better looking than hidding docks and  showing them again.

Maybe also adding a box named "New to QGIS?".
 At start a simple link to the documentation would be nice. Later on, because this requires some work, we could imagine having that "10 steps assistant" showing quickly the main minimal actions needed to start a map (Add some layers, navigate, query data, print a composer, Learn more). As QGIS docks an toolbars are not fixed, I think gif screencasts would be the only option.

**Comment by DelazJ** [comment]
> At start a simple link to the documentation would be nice. Later on, because this requires some work, we could imagine having that "10 steps assistant" showing quickly the main minimal actions needed to start a map (Add some layers, navigate, query data, print a composer, Learn more).

I like the idea. I recall @alexbruy [QEP](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/92) about inserting the Lessons Plugin as a core feature. Didn't get much reaction from the community (yet) but could be of interest here.

**Comment by andreasneumann** [comment]
This should be further worked on at the A Coruña dev meeting. It should be more of priority to the project for several reasons. It is an opportunity for our project:

- we can better communicate with our users
- we can better communicate the visual changelog to them
- we can better reach out to them for funding campaigns
- perhaps we can use the welcome screen to collect some very basic statistic about our users (we need to communicate this transparently)

**Comment by andreasneumann** [comment]
Another idea from @nyalldawson is to also use QTelemetry to collect anonymous data on the application usage. Something to also consider for the future:

https://www.phoronix.com/scan.php?page=news_item&px=Qt-5.13-Possible-QTelemetry

**Comment by inouterer** [comment]
Hello! Why QGIS 3.12 Bukuresti does not show the recent projects on launch?

**Comment by m-kuhn** [comment]
https://github.com/qgis/QGIS/issues/33718#issuecomment-573907204
