### ISSUE TITLE
No more Q_FOREACH in master

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#103]
# QGIS Enhancement: No more Q_FOREACH in master

**Date** 2017/05/09

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall dot dawson at gmail dot com

**Version** QGIS >= 3.0

# Summary

The current master branch of the QGIS codebase contains around 2300 uses of the Qt Q_FOREACH macro. This macro has been deprecated by upstream Qt and will be removed in a future Qt version (probably 6.0). More details about Q_FOREACH's removal (including pages of complaints from Qt library users!) are available at https://www.kdab.com/goodbye-q_foreach/

Qt's stance is that Q_FOREACH is unmaintained and the code should swap to the std c++11 range based for loops instead (which is understandable).

Unfortunately, there's no automatic tool available to replace use of Q_FOREACH with std::for loops. (Full details of why are on the KDAB page linked above). 

Quick summary:
- while Q_FOREACH is safe to use when a container is modified inside the loop (Q_FOREACH takes an internal copy of the container), std::for is not and can cause crashes if the container is modified. We need to verify that these containers are never modified inside the loop before we can safely change the loop from Q_FOREACH to for.
- Q_FOREACH never detaches, but std::for may detach the container (causing a deep copy). To avoid this we need to ensure that the iterated container is const.

These two points mean that there's no current alternative to manually flipping each Q_FOREACH use across to for. The 2300 uses of the Q_FOREACH macro in QGIS represent a significant technical debt which we will need to address before Qt upstream fully drops the macro. (For reference - I've swapped a few of these over and it takes somewhere between 5-30 seconds for each)

Accordingly, this QEP proposes that we block ALL use of Q_FOREACH for new code being introduced into master to prevent this tech debt increasing.

# Alternatives to Q_FOREACH

Instead of Q_FOREACH, the following approaches should be used:

    Q_FOREACH ( Obj *i, someFunctionReturningAQList() )

should be changed to

    const QList< ... > list = someFunctionReturningAQList();
    for ( Obj *i : list )

(storing the temporary list container in a const variable prevents the detach)

    QList< QgsFeature > partFeatures = ...;
    partFeatures.append(...);
    ...
    Q_FOREACH ( const QgsFeature &feature, partFeatures )

should be changed to:

    QList< QgsFeature > partFeatures = ...;
    partFeatures.append(...);
    ...
    for ( const QgsFeature &feature, qgsAsConst( partFeatures ) )

(the qgsAsConst function is designed to mimic std::as_const (not available until c++17) and prevents the detach)

Similarly,

    void myFunc()
    {
      Q_FOREACH ( const QgsFeature &feature, mFeatures )

should be changed to

    void myFunc()
    {
      for ( const QgsFeature &feature : qgsAsConst( mFeatures ) )

However, for a const member function:

    void myFunc() const
    {
      Q_FOREACH ( const QgsFeature &feature, mFeatures )

it can be easily changed to

    void myFunc() const
    {
      for ( const QgsFeature &feature : mFeatures )

There's no need for the qgsAsConst here - since mFeatures is already const because the member function is marked as const.

# Automatic blocking of Q_FOREACH?

While it would be nice in future to develop a script similar to the existing spell check script, which automatically checks git commits and flags any which use Q_FOREACH, this is not feasible while we have such extensive use of the macro in the codebase. Hopefully this could be developed in future (and also block other unwanted Qt functions, such as qRound, qAbs, etc) when the Q_FOREACH usage is decreased.

**Comment by pvalsecc** [comment]
Regarding the automatic blocking, looks like you can disable Q_FOREACH by defining the QT_NO_FOREACH macro.

**Comment by elpaso** [comment]
+1 if there is an alternative to Qt macro I think we should use it.

**Comment by sbrunner** [comment]
+1 :-)

**Comment by 3nids** [comment]
side note for testing, it would be quite doable to check for additions only.
And if someone pushes a small modification to some code with existing Q_FOREACH, the test will be fixed by next coming commit (if the author didn't remove the Q_FOREACH)

**Comment by nyalldawson** [comment]
> side note for testing, it would be quite doable to check for additions only.

Do you mean by using an equivalent of the spellok comment? If so, I don't like that idea because it means we'll have thousands of these littered through the code.

> And if someone pushes a small modification to some code with existing Q_FOREACH, the test will be fixed by next coming commit (if the author didn't remove the Q_FOREACH)

Also seems a bit messy to me - wouldn't it mean any work touching any file with a Q_FOREACH somewhere else will fail on Travis?

**Comment by 3nids** [comment]
> Do you mean by using an equivalent of the spellok comment? If so, I don't like that idea because it means we'll have thousands of these littered through the code.

No just testing on modified/added lines. Something like:
`git diff --diff-filter=ACM -G Q_FOREACH`

> Also seems a bit messy to me - wouldn't it mean any work touching any file with a Q_FOREACH somewhere else will fail on Travis?

We have the choice:

* if we do modified/added, indeed it will fail but that would help converting them. Anyway, any new commit would fix the test as the line won't be changed anymore.
* we can stick to additions only in the diff filter and hence no failing test in this case

**Comment by nyalldawson** [comment]
> if we do modified/added, indeed it will fail but that would help converting them. Anyway, any new commit would fix the test as the line won't be changed anymore.

Heh... let's do this. Forced crowd-sourced de-deprecation :)

**Comment by luipir** [comment]
tnx @nyalldawson to formalize this matter in a QEP.
Before to use spellcheck similar script, why not add check in precommit check to deprecate Q_FOREACH right now? Instruction how to port are already in this QEP.

**Comment by nyalldawson** [comment]
@luipir that's what I had in mind - but we'd need the script in order to add it to the precommit check. (Unless I'm misunderstanding you)

**Comment by luipir** [comment]
@nyalldawson right.

**Comment by dakcarto** [comment]
This is a burdensome change, but nonetheless understandable. Thanks @nyalldawson for concisely describing the issue and steps to fixing current loops. I'll be bookmarking this page! Also, thanks to @dmarteau (I think that's the right github account) for [bringing this up](http://osgeo-org.1560.x6.nabble.com/Replacing-Q-FOREACH-in-Qgis-code-td5303990.html) earlier this year.

**Comment by m-kuhn** [comment]
Oh, I missed this discussion, thanks for bringing it up.

I am very much in favor of switching over from Qt tools to C++ constructs / std implementations. range-based for loops look like something in this category on first sight fall into this category, but this one is particularly nasty.

The tricky bit is this: it's not allowed to modify the container inside the loop or bad things will happen (aka UB). While it sounds easy, it's very hard to impossible in reality to know.

Imagine a loop over all layers in the project. For every layer a check is done like `resolveReferences()`. Inside this method the join buffer is asked to also resolve references. Inside this method a signal is emitted that `joinedFieldsChanged()`. Now who guarantees, that some core or plugin code does not connect to this signal and remove some other layer from the project? 💥
Of course one might argue that in this case a copy should be taken. But let's be honest, if you are the one adding the `joinedFieldsChanged()` signal, you are not going to check that every code path leading up to this method will only work on copies of containers...

At the current point in time we don't even have a tool to detect such scenarios. And we have code that is protected against such scenarios. I'm not sure what exactly we win with this, especially given that [Qt has also taken a step back from removal](https://www.kdab.com/goodbye-q_foreach/#comment-140640).

At the current point in time I'm -0 on this, I would opt to wait a bit for other early adopters and see what happens upstream. I can well imagine that one day [a tool appears](https://www.kdab.com/goodbye-q_foreach/#comment-140645) that does the job for us.

**Comment by wonder-sk** [comment]
I am 0 on this... it is nice to use standard c++ constructs, but I am not sure if the bulk transition is worth it...

**Comment by m-kuhn** [comment]
see for example here https://github.com/qgis/QGIS/pull/5179/files#r138856385

**Comment by vmora** [comment]
@m-kuhn see for what: to do or to avoid. Is it a +1 -0 -1 ?

I've been asked to move to std loops in https://github.com/qgis/QGIS/pull/4765, wich I did, and put some thouhgt in it. Now I'm bitten by dragons, or I'm I ? Thanks for pointing that out BTW. It strengthens your previous point, isn't it ?

**Comment by m-kuhn** [comment]
I guess we are all just about to gain experience with this. What sounds like a nice change might be harder to get right than expected.

I'm happy to do this, but only if we have a chance to get it right in a reasonable way.

**Comment by vmora** [comment]
I'm still alive (avoided the dragons this time). 

But considering what just happened I lean toward a check in the pre-commit script to avoid Q_FOREACH in modified files rather than an attempt to globally remove them.

We can then have knowledgeable reviewers pay special attention to those loops and propagate the knowledge. 

Since it doesn't affect the API, there is no rush and we can take our time to get it right, a step at a time.

So +1, but not too fast because the related bugs may be nasty ones.
