### ISSUE TITLE
Add support for OGC Filter Encoding to WMS

### ISSUE THREAD

**Issue by pvalsecc** [qgis/QGIS-Enhancement-Proposals#104]
# QGIS Enhancement: Add support for OGC Filter Encoding to WMS

**Date** 2017/09/21

**Author** Patrick Valsecchi

**Contact** patrick.valsecchi@camptocamp.com

**maintainer** @pvalsecc

**Version** QGIS 3.0

# Summary

The current WMS filter mechanism provided by QGIS is limited to QGIS specific expressions. This QEP proposes to add support of OGC Filter Encoding, following the same parameter format as MapServer and GeoServer.

## Proposed Solution

Add another format for the WMS FILTER parameter that follows the current MapServer/GeoServer “standard”:
```
…&FILTER=(<filter>...filter for layer 1...</filter>)(<filter>...filter for layer 2...</filter>)...
```

In the code handling the WMS format parameter, if the value starts with `“(<”` or with `“<”` (both starting strings not possible with the current format), we split the filters for the different layers and generate the `QgsFeatureRequest` from the XML, using `QgsWfs::parseFilterElement` (moving this function to `QgsOgc` or something).

The answer to GetCapabilities from MapServer doesn’t contain any reference to the filtering. So no change there.

### Example(s)

See http://mapserver.org/development/rfc/ms-rfc-118.html

### Affected Files

* src/server/services/wfs/qgswfsutils.cpp
* src/server/services/wms/qgswmsrenderer.cpp
* Some other files impacted by refactoring

## Performance Implications

Should have no impact on queries using the current filter format and the performance should be similar for the OGC Filter Encoding format.

## Backwards Compatibility

No problem there. The old format will still be supported.

## Votes

(required)

**Comment by pvalsecc** [comment]
@rldhont, @rouault, an opinion on that?
Anybody else to ask?

**Comment by mhugent** [comment]
+1
Supporting OGC filter syntax in addition to the datasource syntax will be a plus

**Comment by rldhont** [comment]
+1
This will also need an enhancement in QgsVectorLayer or QgsMapSettings to defined filter based on expression for rendering.

**Comment by haubourg** [comment]
ping @pblottiere too

**Comment by nboisteault** [comment]
@pvalsecc Thank you for this feature. Does filter accept GML version 3?

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
