### ISSUE TITLE
Improve the editing tools

### ISSUE THREAD

**Issue by lbartoletti** [qgis/QGIS-Enhancement-Proposals#106]
# QGIS Enhancement: Improve the editing tools

**Date** 2017/10/03

**Author** Loïc Bartoletti (@lbartoletti)

**Contact** lbartoletti at tuxfamily dot org

**maintainer** @lbartoletti

**Version** QGIS 3.X

# Summary

Qgis has simple and sufficient editing tools, but there is always a lack of advanced or directly usable tools without having to perform a processing.
I propose here a panorama of what it can be useful to have built-in QGis to allow a drawing experience close to CAD or other GIS softwares.
Many plugins exist to allow some of the listed actions, but in my opinion, this must be integrated into QGis.
As often as possible, I try to indicate references to plugins (QAD, CADDigitize) of other GIS (GvSIG, OpenJump, ArcGis/[GeoTools](http://www.ian-ko.com/ETGeoTools.html)) or CAD (AutoCAD, QCad) software.
I'm only going to talk about 2D even though all methods can be applied to 3D.

### 1. Rotation by reference (aka absolute angle)

With the Reference option, you can rotate an object to align it to an absolute angle.

This tool come from AutoCAD and is available in QAD.

Links:
- [AutoCAD About Rotating Objects](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/AutoCAD-Core/files/GUID-9DB2CB8C-7FB7-45A4-83A7-82FFC53FC7E1-htm.html)
- [AutoCAD To Rotate an Object to an Absolute Angle](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/AutoCAD-Core/files/GUID-968C016A-FDC5-4ACD-845C-18AE5AB58664-htm.html)

### 2. Trim/Extend

You can shorten or lengthen objects to meet the edges of other objects.
This tool come from AutoCAD, available in QAD, CADDigitize (with more options), OpenJump and GvSIG.

You can merge this tool in one (old CADDigitize, QAD) or two tools (new CADDigitize, QCad, GvSIG, OpenJump)

Links:
- [AutoCAD:
About Trimming and Extending Objects](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/AutoCAD-Core/files/GUID-725D3A7A-5E52-47F0-BA7A-7D15F9EF6D7F-htm.html)
- [AutoCAD: To Trim an Object](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/AutoCAD-Core/files/GUID-3C7BDDBD-46F5-440B-98E2-884996D3B6E8-htm.html)
- [AutoCAD: To Extend an Object](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/AutoCAD-Core/files/GUID-E92C9CFF-2352-449C-9954-4AA7558BD308-htm.html)
- [QCad: Trim](https://qcad.org/doc/qcad/latest/reference/en/scripts/Modify/Trim/doc/Trim_en.html)
- [QCad: Trim both](https://qcad.org/doc/qcad/latest/reference/en/scripts/Modify/TrimBoth/doc/TrimBoth_en.html)

### 3. Chamfer/bevel
A chamfer or bevel connects two objects with an angled line in 2D (, or creates an angled face between the adjacent faces of a 3D solid)

This tool come from AutoCAD and is available in QAD.

Links:
- [AutoCAD: About Chamfers and Bevels](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/AutoCAD-Core/files/GUID-97D6FA66-3A0D-4F16-9D6F-092220F76C99-htm.html)
- [AutoCAD: To Work With 2D Chamfers and Bevels](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/AutoCAD-Core/files/GUID-F5361744-F759-4F0E-9EA6-42258F71FD35-htm.html)
- [AutoCAD: CHAMFER (Command)](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/AutoCAD-Core/files/GUID-B1DCF991-90A7-4DB0-96FC-BDA3FB76337C-htm.html)
- [QCad: Bevel](https://qcad.org/doc/qcad/latest/reference/en/scripts/Modify/Bevel/doc/Bevel_en.html)
- [ET_GeoTools: Chamfer At Vertex](http://www.ian-ko.com/ET_GeoTools/ETGTUG_WEB/etgt/ETChamferAtVertex.htm)
- [ET_GeoTools: Chamfer At All Vertices](http://www.ian-ko.com/ET_GeoTools/ETGTUG_WEB/etgt/ETChamferAtAllVertices.htm)

### 4. Fillet/round
Rounds or fillets the edges of two 2D objects (or the adjacent faces of a 3D solid.)

This tool come from AutoCAD and is available in QAD

Links:
- [AutoCAD: FILLET (Command)](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/AutoCAD-Core/files/GUID-64F8B700-23B3-4BD6-8C03-66121AA13E8F-htm.html)
- [QCad: Round](https://qcad.org/doc/qcad/latest/reference/en/scripts/Modify/Round/doc/Round_en.html)
- [ET_GeoTools: Fillet at Vertex](http://www.ian-ko.com/ET_GeoTools/ETGTUG_WEB/etgt/ETFilletAtVertex.htm)
- [ET_GeoTools: Fillet at All Vertices](http://www.ian-ko.com/ET_GeoTools/ETGTUG_WEB/etgt/ETFilletAtAllVertices.htm)

### 5. Buffer and offset
Sometimes I only want to compute a buffer or offset directly in the layer. I believe that recently, Martin have made a tool to draw with an offset on a snap. But, we can also apply the offset directly in the layer like in CAD software.

This tool come from AutoCAD and is available in QAD and CADDigitize.

CADDigitize permit to apply the offset on a segment or on the whole geometry.

Link:
- [AutoCAD: About Offsetting Objects](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2017/ENU/AutoCAD-Core/files/GUID-704C1ADE-A4AE-4A85-8822-454ACAC1345A-htm.html)
- [AutoCAD: To Offset an Object](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2017/ENU/AutoCAD-Core/files/GUID-F6B26611-5D88-41DD-9BC2-DFB739528BD8-htm.html)
- [AutoCAD: OFFSET (Command)](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2017/ENU/AutoCAD-Core/files/GUID-C0E4246D-C420-42BD-A6FC-8B1852EFD005-htm.html)
- [QCad: Polyline Equidistant](https://www.qcad.org/doc/qcad/3.2.0/reference/en/scripts/Pro/Draw/Polyline/PolylineEquidistant/doc/PolylineEquidistant_en.html)
- [QCad: Offset (with Distance)](http://qcad.org/doc/qcad/latest/reference/en/scripts/Modify/Offset/doc/Offset_en.html)

### 6. Swap direction
Some lines must be oriented (river, road, etc.). The plugin named "SwapDirectionVector" is absolutely what we need when we work on this objects.
Must be into the core.

#### 1. Rotation by reference (aka absolute angle)
Like AutoCAD, select the base point, enter the reference (2 points or a segment) and the two endpoints or a segment for the absolute angle.

#### 2. Trim/Extend

Select one or more boundaries segment(s) and select segments to apply this editing. 

All the tools authorize this editing for line type. I think that only CADDigitize authorize it for the polygon type (or closed line in CAD).
Also, all the tools modify the last selected geometry. Only CADDigitize propose (for line type ) to add as a new entity of the full new segments or only the extended part.
Maybe, we can propose to add this options in a memory layer?

#### 3. Chamfer/bevel
Select two segments and apply options for chamfers. The length can inserted (delegate it to CAD dock widget) or draw it.

#### 4. Fillet/round
Like 3. Chamfer/bevel

#### 5. Buffer and offset
Select the entity (optional: only a segment) and move your cursor or input the value in a widget (delegate it to CAD dock widget).

#### 6. Swap direction
Like the plugin. Select the geometry and it's done.
 
### Example(s)

See links.

#### 1. Rotation by reference (aka absolute angle)
QgsMapToolRotateFeature.{cpp,h}
src/qgisapp.{cpp,h}
ui/qgisapp.ui

#### 2. Trim/Extend
src/qgisapp.{cpp,h}
ui/qgisapp.ui
QgsGeometryUtils and geometries.

I think that we have to move or adapt QgsMapToolCircle2TangentsPoint::intersect into QgsGeometryUtils
Visually we will need more options for rubberbands

#### 3. Chamfer/bevel
Like 2. Trim/Extend

#### 4. Fillet/round
Like 2. Trim/Extend

#### 5. Buffer and offset
src/qgisapp.{cpp,h}
ui/qgisapp.ui
The methods are already available in QgsGeometry

#### 6. Swap direction
src/qgisapp.{cpp,h}
ui/qgisapp.ui

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

Create a full documentation on how works the tools:
- Obviously a classical doc in the manual
- Create a visual changelog on how we digitize now and how we can after this QEP
- A tutorial like "QGis for (Auto)CAD users" with real examples

And communicate

## Backwards Compatibility

N/A

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)
[] Rotation by reference
[] Trim/Extend
* [] Allow multi trim/extend 
* [] Like AutoCAD or [] with more options like CADDigitize
* [] Also for polygon

[] Chamfer/bevel
* [] For all vertices like ETGeoTools

[] Fillet/round
* [] For all vertices like ETGeoTools

[] Buffer
[] Offset
[] Swap direction

**Comment by haubourg** [comment]
Hi starting the review of that very welcome QEP. @dsavary your opinion is welcome here. 

Question 1:
Autocad doc mentions that rotations can be applied in the following systems: degrees, radians, grad, surveyor bearing (which means handling geographic north, magnetic north, geodetic north, assumednorth). So I see two points. 

One is ergonomics for choosing the type of units. I guess the advanced digitizing panel could find some room for that in its settings
![image](https://user-images.githubusercontent.com/1629853/31271411-b37aaf5c-aa87-11e7-88ff-9cc4b33c776a.png)


The other is for defining north reference with the current planar or geographic reference system used in the map canvas.
 This is probably something much more tricky to play with in good intelligence with changing map projection or rotation.
Is that something needed right now?

**Comment by haubourg** [comment]
For Trim extend, if I understand correctly the autocad doc, trimming/extend does not only shorten a feature, but can also merge with to others. This is where GIS concept will not allow as many things as CAD:
![image](https://user-images.githubusercontent.com/1629853/31271971-87b64fb4-aa89-11e7-8525-fefef4081ac9.png)

![image](https://user-images.githubusercontent.com/1629853/31272026-cfb48bc8-aa89-11e7-8bcc-b37f4562b2f2.png)

this particular case could be in QGIS one big multi line and triming the line crosses is not an issue. But most likely, the four lines will be 4 individual features, and the trim will then do some tricky things.. Any opinion?

**Comment by haubourg** [comment]
3. Chamfer / bevel 
Making a chamfer on multipart polygons or lines is a bit like the current reshape tool.  We could imagine a dropdown list of maptools there (freehand reshape / chamfer / bevel ). Use of angles or distances could probably be achieved with the advanced digitizing panel.

**Comment by dsavary** [comment]
Very good proposal ! Thanks !
We (Lausanne - QWAT users) are interested in this kind of tools (1, 2, 5, 6). 
Our users are advanced users of AutoCAD. It would be very well if the behaviour of these tools are close to autocad tools :) . 
Perhaps, just one comment, it would be great if this tools take care of : 

- 3D geometry
- the different geometry type (polyline with curve, multi-geometry, ...) 
- the different source of layer (postgis layer, SHP, gpkg, memory layer,...)

**Comment by lbartoletti** [comment]
@dsavary you're welcome :)

- 3D geometry: I will verify but I think it's possible for all tools proposed. Just more difficult for some tools ;)
- Geometry type: In AutoCAD, some tools are not allowed for the curve type. I think this type needs a better integration for some of the tools proposed. FYI, I created a discussion in the Qgis-developer mailinglist for the management of "complex"geometries. It's very related.
- Source: OK. I don't see any problem to do that. Also, maybe propose a better integration for some types and formats of the layers.

**Comment by lbartoletti** [comment]
Hi @haubourg, as I understand, there is also a need for construction tools (get intersections of circle-circle for example) without this being a new geometry. I think it can be integrated with the dock cad. How do you feel about that?

It is necessary to add some algorithms in the class circle* (in progress 😉), to port the creations of the arcs from Qad and CADDigitize plugins.

* For circle-circle-circle intersection, can you specify what is expected? The area of the intersection of 3 circles can be calculated. You want to be able to minimize this area in order to have an area close to zero and thus a point of intersection of these 3 circles, like a triangulation?

**Comment by haubourg** [comment]
>  there is also a need for construction tools (get intersections of circle-circle for example) without this being a new geometry.

totally yes. the "advanced digitizing dock is a good idea. Currently in construction mode, it keeps memory only of the two last sketches. If it kept all the sketches created while in construction mode and add them + the infered intersection points to the snapping index, that would do. 

> For circle-circle-circle intersection, can you specify what is expected? 

in GEONIS, this is a dedicated panel that computes a mid point inside the remaining intersection area and allows you to force that computation by forcing the distance on some circle and refreshing the mid point computation. We could maybe just reuse the current advanced digitizing dock too, by infering the mid point (a barycenter) on all polygonal or circles intersections. Changing a circle diameter to force a new barycenter could be just adding a new circle. Not sure this plays well for CAD users, but I would very much be in favor not to add additional docks or dialogs for each tool.

**Comment by sergegevaerts** [comment]
Very good proposal. Committed to fund effort to implement these features.

**Comment by lbartoletti** [comment]
> Question: the new extend feature, which version of QGIS will be in?

Available in QGIS Dev and will be in QGis 3.6

**Comment by enzedrailmaps** [comment]
Ideally, we also need some way of having the editor snap to a particular angle e.g. 90 degrees. For drawing irregular rectangle shapes for example.

**Comment by enzedrailmaps** [comment]
An alternative way of drawing an irregular rectangle is to draw it as a series of regular rectangles that overlap, and then having some way of merging them into one shape.

**Comment by haubourg** [comment]
@enzedrailmaps doesn't the advanced editing panel allows that already ?

**Comment by miguelzuza** [comment]
Please!

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
