### ISSUE TITLE
Add WMS Time support in QGIS server

### ISSUE THREAD

**Issue by sbrunner** [qgis/QGIS-Enhancement-Proposals#110]
# QGIS Enhancement: Add WMS Time support in QGIS server

**Date** 2018/02/22

**Author** Stéphane Brunner (@sbrunner)

**Contact** stephane.brunner@camptocamp.com

**maintainer** @sbrunner

**Version** QGIS 3.2

# Summary

Add WMS Time support in QGIS server

## Proposed Solution

Add in the vector layer properties / `QGIS Server` a section named `WMS Time` with the following attributes:
* Field: `Combo boy with disable and compatible fields`
* [X] Advance => Extent: `text field with e.g.: min1/max1/res1,min2/max2/res2`, Default: `text field`
* Resolution: `integer field` `combo with years Y, months M, days D, time T,  hours H, minutes M, seconds S`
  It we want to put more advance resolution like: `P1M10D` or `PT1.5S` use the advance field
* Extent: from `date (time) picker` to `date (time) picker`
* Default: `date (time) picker`

Impact the WMS server:
* `GetCapabilities`
 - Add the Dimensions for the vector layers
 - Copy the Dimensions for the WMS layers
* `GetMap` and `GetFeatureInfo` for vector layers
 - Add a Filter Expression eventually a Filter SubsetString for the Postgis layers
* `GetMap` and `GetFeatureInfo` for WMS layers
 - Just a pass throw of the TIME parameter

Points to investigate:
* what's don in the time manager (client part) https://plugins.qgis.org/plugins/timemanager/
* should we have a solution that manage all the Dimensions...
* should we add the settings int the server part or in a new tab of the layer for an eventual implementation in QGIS desktop

Next steps:
* Also avalable for WMTS layers
* Have a GUI in QGIS desktop like the TimeManager
* Also support the elevation spec

See also: http://mapserver.org/ogc/wms_time.html

### Affected Files

(required if applicable)

## Performance Implications

**(required if known at design time)**

## Backwards Compatibility

**(required)**

## Votes

(required)

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
