### ISSUE TITLE
Allow overwrite of QgsProject::homePath()

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#112]
# QGIS Enhancement: Allow overwrite of QgsProject::homePath()

**Date** 2018/02/28

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall dot dawson at gmail dot com

**maintainer** @nyalldason

**Version** QGIS 3.2

**Sponsor** SMEC/SJ

# Summary

QgsProject::homePath() is used by the QGIS Browser to show a directory item containing files and subdirectories contained within the current project's home path.

The home path is currently automatically determined by taking the path of the project file, so always matches the folder containing the .qgs project file.

This setup works only if users store all files relating to a project in subdirectories off the qgs project file location. However, this is not an ideal setup in many organisations. Some organisation projects may have many related .qgs project files, and these may be stored in a subdirectory from the main organisational project folder. E.g.

```
/projects/A000001 Road design/Documentation
/projects/A000001 Road design/Incoming data
/projects/A000001 Road design/Outputs
/projects/A000001 Road design/QGIS Projects (containing .qgs files)
/projects/A000001 Road design/Scripts
```

In this case, only the subfolder containing the .qgs folders is accessible via the browser, whereas ideally the project home path would be `/projects/A000001 Road design` so that the Documentation, Incoming data, Outputs and Scripts folders are also accessible via the Project home item in the browser.

## Proposed Solution

A new QgsProject member `setHomePath( const QString& path )` is introduced. If called, the specified path will be stored in a string member variable `mHomePath` within QgsProject. When calling `setHomePath`, the `QgsProject::homePathChanged` signal will be fired if the path has changed. The manual home path specified via `setHomePath` will be saved and restored when serializing the project.

`QgsProject::homePath()` logic will be altered so that first a check is made whether `mHomePath` is non empty, and if so it is returned for the home path. If it is empty, the existing auto-detection of the .qgs project file path will be used.

The logic in `QgsBrowserModel::initialize()` will be changed to connect instead to the `QgsProject::homePathChanged` signal to update the folder displayed in the Project home browser item.

A new expression variable `@project_home` will be added which contains the project home path.

### GUI

A new context action will be added to the Project home browser item "_Set Project Home..._". Clicking this will allow users to browse for a new project home folder for the current project.

Additionally, the project home will be shown in a line edit within the Project Properties dialog, along with a corresponding browse button to set it directly there.

### Affected Files

Affected files are QgsProject and QgsBrowserModel.

A unit test will be added to test_qgsproject.py.

## Performance Implications

None

## Further Considerations/Improvements

QgsProject::homePath is used only by the browser, so there is no wider implications to changing the logic here.

## Backwards Compatibility

N/A

## Votes

(required)

**Comment by nirvn** [comment]
Nice idea. The setHomePath() function should support relative paths, is that part of the plan?

**Comment by nyalldawson** [comment]
> The setHomePath() function should support relative paths, is that part of the plan?

I'll make sure that works - in this case they would be set via manual entry in the Project Properties setting.

I should add that this does NOT affect how relative paths are resolved in projects -- those are, and will remain, relative to the .qgs project file itself.

**Comment by NathanW2** [comment]
Nice work. That would be a good addition.

**Comment by nyalldawson** [comment]
@rduivenvoorde

It doesn't affect favourite items. All it will do is change the path that the current "project home" item directs to.

So no extra UI clutter involved :)

**Comment by nyalldawson** [comment]
Implemented at https://github.com/qgis/QGIS/pull/6557

**Comment by nyalldawson** [comment]
Accepted and implemented
