### ISSUE TITLE
Allow injection of "label blocking regions" into QgsMapSettings

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#113]
# QGIS Enhancement: Allow injection of "label blocking regions" into QgsMapSettings

**Date** 2018/02/28

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall dot dawson at gmail dot com

**maintainer** @nyalldawson

**Version** QGIS >= 3.2

# Summary

The PAL labeling library utilised as a backend for QGIS map labelling has numerous features for supporting "label obstacles", which act as a deterrent for placing labels within an area on the map.

These are utilised internally when labeling map features to avoid placing labels over map features, and is exposed to QGIS users via the "_Blocking_" label setting for a layer or the "_Discourage labels from covering features_" option.

Currently, obstacles can only be inserted into the labeling problem via vector layer features - there is no way to control additional, non-feature-based regions to avoid placing labels within. This proposal concerns adding API support for manually injecting regions into the labeling problem to discourage the placement of labels within these regions.

Manual label blocking regions are useful for discouraging labels from falling within "hidden" areas of a map. E.g. when a map annotation or scalebar is displayed over a portion of the map, QGIS should attempt to avoid placing labels in the obscured area below these annotations. Similarly, within a print layout, if a map item has additional items placed over it (such as a legend or north arrow), it is desirable that labels should not be placed in map areas below these obscuring items.

This proposal covers adding the API calls for supporting manual label blocking regions only -- it is left to a future work to implement automatic creation of these blocking regions for map-obscuring elements.

## Proposed Solution

A new class, `QgsLabelBlockingRegion` is introduced:

```
/**
 * Label blocking region (in map coordinates) to blocking priority (0-10).
*/
class QgsLabelBlockingRegion
{
  public:
    QgsLabelBlockingRegion( const QgsGeometry& geometry, double obstacleFactor )
        : geometry( geometry )
        , factor( obstacleFactor )
    {}

    //! Geometry of blocking region, in map coordinates
    QgsGeometry geometry;

    //! Label blocking priority, from 0-10
    double factor;

};
```

QgsLabelBlockingRegions can be added to a QgsMapSettings via new methods:

```
   /**
     * Sets a list of \a regions to avoid placing labels within.
     */
    void setLabelBlockingRegions( const QList< QgsLabelBlockingRegion >& regions );

    /**
     * Returns the list of regions to avoid placing labels within.
     */
    QList< QgsLabelBlockingRegion > labelBlockingRegions() const;

```

The `pal` class would gain similar getters and setters for lists of label blocking regions added - QgsLabelingEngine::run would inject the current map setting's labelBlockingRegions into the pal object before processing each labeling provider and registering their features within the labeling problem.

Within the pal engine, `FeaturePart` would become an abstract base class, with pure virtual methods:

```
  //! Returns the feature's obstacle factor, which represents the penalty
  //! incurred for a label to overlap the feature
  virtual double obstacleFactor() const = 0;
 
  //! Returns the obstacle type for this feature
  virtual QgsPalLayerSettings::ObstacleType obstacleType() const = 0;

  //! Clones the feature part  
  virtual FeaturePart* clone() const = 0;
```

FeaturePart would be subclassed into `LabelFeaturePart` and `ObstacleFeaturePart` (where the current implementation of FeaturePart becomes LabelFeaturePart).  

Before solving the labeling problem, ObstacleFeatureParts will be created for each QgsLabelBlockingRegion registered to the pal instance.

### Affected Files

QgsMapSettings
pal/feature.h/.cpp
pal/layer.h/.cpp
QgsLabelingEngine

+ corresponding unit tests

## Performance Implications

None, if label blocking regions are not in use. When automatic label blocking regions are created for map annotations and other obscuring items then it is likely to slow the labeling solution process. If the performance cost is deemed too high then the creation of the automatic blocking regions could be user-controllable via a checkbox in the project label settings dialog.

## Backwards Compatibility

N/A

## Votes

(required)

**Comment by mhugo** [comment]
+1

Does a maximum blocking priority guarantee that there won't be any labels drawn ? Or is it more a "best effort" ? (Thinking about masking labels from a "mask" layer)

**Comment by nyalldawson** [comment]
> Does a maximum blocking priority guarantee that there won't be any labels drawn ? Or is it more a "best effort" ? (Thinking about masking labels from a "mask" layer)

It's the same as "highest priority" when marking a layer's labels with "Discourage labels from covering features". However -- I think there's improvements we can make here to the costs applied by pal for covering obstacles. Currently I still see labels which sometimes cover features even with the maximum obstacle cost of 10. In my opinion we should make the maximum cost mean "NEVER put labels here". 

I've wanted to tweak the costing for different pal penalties for a while now, but I'm also aware that we don't have a full set of unit tests covering many different labeling situations.

So as a separate piece of work I'd love to:
1. Make unit tests covering lots of different label situations, e.g. "when a point label and polygon label of equal importance clash and only have a single candidate position, prefer to label the point feature", "when a point label and polygon label with differing importance clash, prefer to label the feature with highest priority", etc...
2. Tweak the cost so that an obstacle importance of 10 equates to "never cover"

In the meantime the work proposed here will not change the current candidate costs.

**Comment by mhugo** [comment]
@nyalldawson thanks for your explanations. And of course, I agree, if we can have someday a "never cover", that would be nice.

**Comment by haubourg** [comment]
@mhugo agreed that having something in core for mask use case would be nice. 
 I think we should also modify the labeling logic so that it sends only the portion of the feature that is **outside** the masking area to compute labels. 
Imagine for instance a long river overlapping the mask area, this would allow to still have the labels being drawn.

**Comment by nyalldawson** [comment]
@haubourg 

> I think we should also modify the labeling logic so that it sends only the portion of the feature that is outside the masking area to compute labels.
Imagine for instance a long river overlapping the mask area, this would allow to still have the labels being drawn.

That should already be handled by the pal library. Here's a screenshot from 3.0 of a line feature with a label being covered by a polygon feature set to "blocking" mode:

![image](https://user-images.githubusercontent.com/1829991/36821356-65474352-1d3e-11e8-8d3a-d9eb0027a806.png)

You can see that candidates are generated on either side of the obstacle.

**Comment by haubourg** [comment]
Huge ! /me happy :-)

**Comment by nirvn** [comment]
@nyalldawson , could this be used to make the labelling engine aware of the visible canvas extent, and push labels inside the canvas instead of drawing chopped of labels? I.e., could we add a buffer region just outside the visible canvas extent to deal as a blocking area?

**Comment by nyalldawson** [comment]
@nirvn that's already possible - turn off "show partial labels" in the project label settings

**Comment by nirvn** [comment]
@nyalldawson ,  thought switching that off was only removing chopped labels, i.e. not suggesting another placement when label placement is set to cartographic, around centroid, etc. Am I wrong?

**Comment by nyalldawson** [comment]
Well, it eliminates candidates which cross the bounds. You need to be using a label placement mode which has other candidates possible for it to "re-place" them.

**Comment by nirvn** [comment]
@nyalldawson , ah cool, so I was uninformed. TIL :smile:

**Comment by nyalldawson** [comment]
Implemented in https://github.com/qgis/QGIS/pull/8644/
