### ISSUE TITLE
Edit features in place using processing algorithms

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS-Enhancement-Proposals#114]
# Edit features in place using processing algorithms

**Date** 2018/03/02

**Author** Alessandro Pasotti (@elpaso), Nyall Dawson (@nyalldawson )

**Contact** elpaso at itopen dot it, nyall dot dawson at gmail dot com

**maintainer** @elpaso, @nyalldawson

**Version** QGIS 3.2

# Summary

Given a layer opened for editing and a set of selected features, this enhancement will allow a user to execute suitable algorithms on the selected features directly modifying feature geometry in-place.

For an algorithm to be suitable for in-place modifications it needs to support operations on isolated features, it must not change the wkb type of the input geometry and must not add or remove or change the type of any field in the layer. 

## Proposed Solution

The proposed solution add a tri-state tool button to the processing toolbar, the button becomes checkable when the user selects some features in an editable layer.

When the button is pressed, the processing toolbar enters in modify-in-place mode and it filters the algorithms that are suitable to be executed on a set of features and allow geometries in-place modification of the geometries. 

The algorithm dialog input and output fields will be hidden when the dialog is opened in this mode.

![qgis-in-place-mock](https://user-images.githubusercontent.com/142164/36893744-7d088426-1e09-11e8-84a5-7a847b60af32.png)

If the algorithm does not have any additional user-set parameters (excluding the usual input and output layer parameters), then the algorithm will be run immediately over the selected features without any dialog popup. 

The locator input box could also be used as additional mean to run the algorithms for advanced users or touch typers.

### Typical workflow

The typical workflow will be:

- user makes a layer editable
- makes selection on the layer
- runs the algorithm in a special mode (* see note below)
- the selected features are iterated over, modifying each by pushing
them through the algorithm's `processFeature` method, and then storing
them back in the layer's edit buffer via `QgsVectorLayer::updateFeature`
(run in the main thread, not a task - we're editing the layer so we
can't do it in the background.)

### Example(s)

Existing algorithms that are suitable for in-place geometry modifications
are all algorithms which derive from `QgsProcessingFeatureBasedAlgorithm`
for example: buffering (for polygons), simplification, smoothing, translation, offsetting, densification, make valid, remove
duplicate vertices, remove hole, reverse line directions and multiparts to singleparts.

## Justification

Currently, it is very difficult to perform "in-place", algorithm-based
edits on geometries within QGIS. To perform a common task like
reversing the direction of a set of linestrings requires users to run
the corresponding processing algorithm over the selected features,
causing a new layer to be created with the result. The original layer
features must then be deleted, and the reversed features from the new
layer manually copied and pasted back into the original layer. These
manual tasks are tedious and error-prone.

Neither is it is not a feasible long-term solution to add additional
editing tools to the QGIS Edit menu or Advanced Digitizing toolbar.
These menus and toolbars are already home to many actions, and adding
additional actions here causes UI clutter and makes QGIS more
unfriendly for new users.

Similarly, relying on 3rd party plugins to perform these editing
operations is not an ideal long-term solution either, as the plugins
also must add additional actions to QGIS and also add to UI clutter.

By leveraging QGIS' processing algorithms, we can immediately expose
dozens of desired in-place editing operations without any code
duplication. 3rd party plugins can easily extend the feature by
implementing their operations as processing algorithms derived from
QgsFeatureBasedAlgorithm (which also has the side-benefit of allowing
these plugin-provided operations to be fully operational within
processing models and accessible for Python scripting). Furthermore,
the QGIS algorithms are extensively unit tested, ensuring that the
in-place editing operations will be error-free.

### Affected Files

Affected files are mainly in python processing plugin, some signal/slot connections must also
be created to keep the UI in sync with feature selection in an editable layer.

In the C++ side, `QgsProcessingAlgorithm::Flag` requires a new flag to mark algorithms that are suitable
for in-place operations.

## Performance Implications

None

## Backwards Compatibility

No issues.

## Votes

(required)

**Comment by alexbruy** [comment]
Nice! A big +1 from me.

**Comment by rduivenvoorde** [comment]
Really like this idea!!!!
But question: such an edit IS in the undo-buffer isn't it? 
That is: somebody doing this to the selection and making the wrong edits, is able to undo this in one go?

**Comment by nyalldawson** [comment]
@rduivenvoorde

Correct - it's only enabled when a layer is made editable, and the changes are buffered and not automatically committed.

**Comment by haubourg** [comment]
That is wonderful and will implement that feature request here : https://issues.qgis.org/issues/13050

**Comment by jgrocha** [comment]
In **Field Calculator** we already can change the `$geometry` field, using an expression, which is a basic in-place geometry modification. Maybe the algoritms tagged as suitable for in-place operations could be listed in Field Calculator, ready to apply over all selected features. Does it make sense?

**Comment by elpaso** [comment]
@jgrocha I think it does, maybe out of scope for this QEP, but it could be implemented independently.

**Comment by jgrocha** [comment]
Thanks @elpaso. The option to add these algorithms to field calculator can be added later.

**Comment by rduivenvoorde** [comment]
FYI: https://issues.qgis.org/issues/18436 could be a use case I think: given a layer with polygons, clip all features, based on one selected?

**Comment by jgrocha** [comment]
@rduivenvoorde Issue https://issues.qgis.org/issues/18436 changes the number of existing features on a layer. My initial understanding of this proposal was just a function over the geometry column without adding or deleting features.

**Comment by wonder-sk** [comment]
May I suggest that also algorithms that are not based on QgsProcessingFeatureBasedAlgorithm could be used for this feature? In such case, the selected features could be put into a temporary layer, the algorithm would be run and the resulting data would replace the original selected features. This could give us more functionality and users would not need to understand that some algorithms are implemented as feature-based and some aren't... (i.e. only some algs are available for in place editing). Like this all algorithms that output the same geometry type and the same set (or super-set) of attributes could be used...

**Comment by nyalldawson** [comment]
@wonder-sk

> May I suggest that also algorithms that are not based on QgsProcessingFeatureBasedAlgorithm could be used for this feature? In such case, the selected features could be put into a temporary layer, the algorithm would be run and the resulting data would replace the original selected features. This could give us more functionality and users would not need to understand that some algorithms are implemented as feature-based and some aren't... (i.e. only some algs are available for in place editing). Like this all algorithms that output the same geometry type and the same set (or super-set) of attributes could be used...

That's a good idea, and would certainly extend the functionality of this feature. (I'd skip the temporary layer in this case and just throw the features into a QgsFeatureStore to keep things nice and light). It's also not possible to directly replace the input features, because there's no gaurantee that their feature ids will be kept intact, so we'd need to:
-  run the algorithm on the selected features, using a QgsFeatureStore as the output sink to collect the results
- delete all selected features from the layer
- add the features from the temporary store as new features

(This has some undesired side effects, e.g. there's no longer any link between the original features and their modified forms, which could be an issue with db triggers, etc. But I think it's an acceptable compromise. For feature based algs we'd still operate directly on features themselves, so those algs WOULD remain db trigger friendly).

It's not quite trivial to implement however. The difficulty is in handling the input and output layers for these non-feature based algorithms. E.g. for the "clip" algorithm, we would need a way to indicate that the "INPUT" layer parameter is the parameter which corresponds to the editable layer which are modifying, the "OVERLAY" parameter is a different layer and must still be selected by the user, and the "OUTPUT" parameter must be set to the QgsFeatureStore we are collecting results in.

While we could just blindly force this to always be "INPUT"/"OUTPUT", I think I'd rather add virtual methods which allows the algorithms to specifically return the correct parameter names.

In any case, I'd suggest we start by exposing this via the feature based algorithms. That's a much easier change, and will allow us to refine the UX for this feature. When that's all locked in we can then add handling for non feature based algorithms which also return the "in place support" flag.

**Comment by nyalldawson** [comment]
@elpaso 
> I don't know about that one, but I'm pretty sure that if the algorithm does modify the layer as a whole (like adding new fields) it shouldn't be suitable for in-place editing.

I think the "right" approach is to be tolerant here for algorithms which don't HAVE to add fields. So eg in the case of oriented minimum bounding boxes, we just don't add new fields if it's in in-place mode. But for something like "drop field" then we should NOT allow in-place mode, as changing fields is integral part of that algorithm.
