### ISSUE TITLE
Add metadata to QgsProject

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#115]
# QGIS Enhancement: Add metadata to QgsProject

**Date** 2018/03/06

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall dot dawson at gmail dot com

**maintainer** @nyalldawson

**Version** QGIS 3.2

# Summary

QGIS projects currently only have limited support for "project level" metadata. On the project level there is only the option to set a project "title". Projects for QGIS server have rich metadata support, including short names, abstracts, contacts and keywords, yet those settings are specific to QGIS server publishing and cannot (should not?) be re-used outside of the server context.

This proposal covers adding some basic metadata support for QGIS projects themselves, including:

- Author
- Creation date
- Keywords
- Subject

## Proposed Solution

A new class, `QgsProjectMetadata` will be created, with getters and setters for project author, creationDate, keywords and subject. (This can be extended in future with additional metadata items). 

QgsProjectMetadata will contain methods for serializing metadata to and from XML.

`QgsProject` will have a `QgsProjectMetadata` member.

The Project Properties dialog will be extended to include a new tab for Project Metadata, allowing users to edit this metadata.

The project expression context scope will be extended with new variables, @project_author, @project_creation_date, @project_keywords and @project_subject, allowing the values of these metadata fields to be accessed through QGIS expressions.

Exports from layouts will automatically set the corresponding metadata in the created files (depending on the export format support). E.g. 

- PDF: AUTHOR,  CREATION_DATE, KEYWORDS, SUBJECT and TITLE (existing)
- SVG: SUBJECT and TITLE (existing)
- Image Based Formats: Items are dependant on destination format (and the Qt library’s support for that
format). Available items will include AUTHOR, CREATION_DATE, KEYWORDS, SUBJECT
and TITLE, with items unsupported by the specific destination format ignored on export.

### Affected Files

- QgsProject (+corresponding tests)
- QgsProjectMetadata
- QgsLayoutExporter
- QgsExpressionContextUtils (+corresponding tests)

## Performance Implications

None

## Backwards Compatibility

N/A

## Votes

(required)

**Comment by pcav** [comment]
+1. Thanks Nyall.

**Comment by ghtmtt** [comment]
big +1. Thanks

**Comment by elpaso** [comment]
+1 , but I'd try to merge the MD with the server's ones to avoid duplication.

**Comment by haubourg** [comment]
+1. I would also be in favor of having the standard Dublin Core fields used for documents and also supported by most open data portals like GeoNode. @timlinux maybe you have opinions about metadata interoperability at the project level?

**Comment by jgrocha** [comment]
+1, related with #91

**Comment by aureliopires** [comment]
Big +1, related with #91

**Comment by luca76** [comment]
I think we should click on the + icon (at bottom of the first post)

**Comment by nyalldawson** [comment]
> +1. I would also be in favor of having the standard Dublin Core fields used for documents and also supported by most open data portals like GeoNode. @timlinux maybe you have opinions about metadata interoperability at the project level?

@haubourg 

I totally agree -- it would be nice to go with the standards here. But I'm unsure how much of Dublin Core/ISO 19115 applies on a project level. Ideally I'd like to reuse some of the metadata classes which were added in 3.0 -- e.g. split QgsLayerMetadata into QgsBaseMetadata (subclassed and extended by QgsLayerMetadata), which would then be inherited by QgsProjectMetadata.

Looking at the layer metadata class, a lot of it can't apply to projects (at least, in my opinion). We've got the content of the Identification tab, keywords, contacts, links, and history. But does the standard dictate others? 

ping
@tomkralidis @doublebyte1@kalxas @Gustry @timlinux

**Comment by tomkralidis** [comment]
It might be valuable to use the same approach as we did for resource metadata, i.e. a generic [schema](https://github.com/qgis/QGIS/blob/master/resources/qgis-resource-metadata.xsd) which could be marshalled into DC, ISO, etc.

Having said this, +1 to splitting and subclassing.  XML-schema wise, we could have a qgis-base-metadata.xsd which define core constructs and then qgis-project-metadata.xsd and qgis-resource-metadata.xsd

**Comment by nyalldawson** [comment]
Thanks @tomkralidis 

Which layer metadata items do you think should be moved to base and apply to projects also?

**Comment by tomkralidis** [comment]
definitely contact, links and history can be moved to base.

**Comment by nyalldawson** [comment]
> definitely contact, links and history can be moved to base.


So then:

Base:
- Contact
- Links
- History
- Keywords
- Title
- Abtract

Project:
- everything from base
+ author
+ creation date
+ subject

Layer:
- everything from base
+ identifier
+ parent identifier
+ type
+ categories
+ access
+ extent

What about language? Should that also be moved to base?

**Comment by tomkralidis** [comment]
Thanks @nyalldawson looks good.  I would also put identifier in base given it is always valuable to concisely refer to something by its id.

**Comment by nyalldawson** [comment]
Part 1 is implemented by https://github.com/qgis/QGIS/pull/6635

**Comment by ghtmtt** [comment]
> Part 1 is implemented by https://github.com/qgis/QGIS/pull/6635

thanks Nyall!

Matteo

**Comment by nyalldawson** [comment]
Implemented in master
