### ISSUE TITLE
Allow Drill-down (cascade) search in Value Relation Widgets

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS-Enhancement-Proposals#116]
# QGIS Enhancement: Allow Drill-down (cascade) search in Value Relation Widgets

**Date** 2018/03/18

**Author** Alessandro Pasotti (@elpaso)

**Contact** elpaso at itopen dot it

**maintainer** @elpaso

**Version** QGIS 3.2

# Summary

This is basically a port of the 2.x Form Aware Value Relation Widget plugin https://github.com/elpaso/qgis-formawarevaluerelationwidget/

The plugin for 2.x allowed to create value relation expressions based on the current value of another field in the same form.

When the value changes in the current field, the values available in the related fields are filtered again allowing to use a hierarchical filtering strategy (drill-down, or cascading) inside a form.

Please see the readme in https://github.com/elpaso/qgis-formawarevaluerelationwidget/ for a visual explanation or see the video at https://www.youtube.com/watch?v=ipezh4KXrgo

## Proposed Solution

The proposed implementation is an enhancement of the current classes `QgsValueRelationSearchWidgetWrapper` and `QgsValueRelationFieldFormatter`, by adding a 
 `QgsExpressionContextUtils::formScope` that holds current form values, passed by the form widget or the `QgsAttributeEditorContext`.

A new function `get_current_form_value` will be added to the layer's form widget expression editor, the function will retrieve the current value of another form field in the form or table row that is currently being edited.

In case the form scope is not required the internal workflow of the existing classes is not altered in any way and it is supposed to maintain the current behavior and performances.

The 2.x original plugin did not work at all in the attribute table row contex: this limitation will be removed by the proposed implementation.

### Affected Files

Above mentioned classes plus `qgsexpressioncontext.h`  and other expression files for the new expression function `GetCurrentFormFieldValue`.

## Performance Implications

None affecting existing workflows.

## Further Considerations/Improvements
There are indeed some considerations about caching when a form context is required: for this kind of dynamic relations the usual caching of kvp for the widgets is bypassed and the features are re-filtered any time the value used in the expression changes.

This might not scale well on some scenarios and a smarter caching approach might be required as further enhancement.

## Backwards Compatibility

No issues.

## Issue Tracking ID(s)

There should be something buried in the issues tracker but I couldn't find it now, please let me know if you find it.

## Votes

(required)

**Comment by pcav** [comment]
I think this would be an important improvement.
Thanks Ale.

**Comment by m-kuhn** [comment]
Good topic, long enough untackled.

I wonder if it's required to have a new scope to hold form values or if it would be sufficient to pass in an updated feature with the current value (as done for tab and group box visibility or constraints).

The logic to re-trigger expressions based on their dependencies should also be almost equal to these other ones.

**Comment by elpaso** [comment]
@m-kuhn thanks for the comment, I'll have a look at that approach.

I though about a scope because it can encapsulate the function and the variable and it seemed more logical and cleaner to me, it is actually a form scope/context: the function and the variable only have a meaning in a form/table-row context.

**Comment by m-kuhn** [comment]
What would you fill into the feature data for the expression? (i.e., what would an expression `"fieldA"` evaluate to)

**Comment by elpaso** [comment]
That would not change: `"fieldA"` would always refer to the original feature field value before it was edited (if any). 

What I'm adding here is `get_current_form_value('FieldA')` (note single quotes) that would return the value of the field, in case it wasn't changed it will be the same as the original `"fieldA"`, but if the user has edited the field, the value will be different.

**Comment by m-kuhn** [comment]
My main concern is that this would be different to how *conditional visibility* and *constraints* handle things.

**Comment by elpaso** [comment]
Honestly I did never think at altering the feature directly because I was afraid of side effects (you know  well as I do that that area of the code is not exactly easy to follow).

If you feel comfortable with just overriding the feature values it is probably the simplest approach.

Having a function to retrieve the current form value make it easy to determine if there is a "dynamic" filter in the value-relation (and in that case rebuild the cache - re-filter the features - when that value has changed), but if we agree that: 

in the filter expression, any `"fieldA"` reference to a field name that belongs to the main layer is meant to be part of a dynamic filter, 

then I guess we have a criteria to know if the expression is dynamic and we can safely assume that the cache needs to be rebuilt and we don't need an explicit function (even if "explicit" is better than "implicit").

**Comment by elpaso** [comment]
... forgot  to mention that another reason for taking the harder route would be in case we want to add more form-scoped functions or variables in the future, the scope has place for multiple functions and variables.
ATM I cannot think of other use cases though.

**Comment by m-kuhn** [comment]
> Honestly I did never think at altering the feature directly because I was afraid of side effects (you know well as I do that that area of the code is not exactly easy to follow).

It's already done for other parts (constraints and conditional visibility), maybe I'm missing something but it sounds trivial to me to apply the same behaviour.

Adding a form scope in addition to setting the expression feature based on form values sounds reasonable to me. I don't think they are orthogonal concepts.

**Comment by elpaso** [comment]
Can you please point me to the relevant parts of the code where you are altering the current edited feature fields to be used in the expression for a widget filter ?

**Comment by m-kuhn** [comment]
Sure https://github.com/qgis/QGIS/blob/master/src/gui/qgsattributeform.cpp#L768

**Comment by elpaso** [comment]
thanks :smile:

**Comment by m-kuhn** [comment]
One more question, how do you see the future of the Value Relation widget and the Relation Reference widget? They are extremely similar, yet they both provide their own set of features and limitations.

The relation reference widget supports [filtering available entries](https://qgis.org/api/classQgsFeatureListComboBox.html#a2d45cfbb1ce33f77abda818361becd91) almost out of the box, one of the reasons to introduce this API was the to be prepared for the use case described in this QEP.

**Comment by haubourg** [comment]
Hi @m-kuhn 
Totally agreed, I think those two components needs to inlined each other and improved. What about writing a QEP on that? I think I can do that since I already drafted some requirement. We discussed that last year a didn't get the funds finally, but it is still highly critical to build nice business applications. 
Do you think a QEP is a good place to start?

**Comment by elpaso** [comment]
@m-kuhn @haubourg I totally agree that a broader proposal about the value-relation-reference would be a good thing.

But the scope of this QEP is more limited and it's about enhancing the existing value-relation widget to allow dynamic filtering on form/row values (and geometry).

I'm almost done with the implementation, I think that for now it could be a nice improvement, but I'm ok with closing this QEP and wait for better times, just let me know before I invest more (volunteer) time on this task.

**Comment by m-kuhn** [comment]
> and geometry

what's that?

> I'm almost done with the implementation

Ok, I assume it shouldn't be too hard to port this functionality.

> Do you think a QEP is a good place to start?

The first thing we need is probably a comprehensive list of functionality that *the one and only* widget will implement. Then move any missing functionality from widget A to widget B and finally deprecate widget A to make sure new functionality are always directly implemented in widget B.

**Comment by elpaso** [comment]
> what's that?

Not the primary goal of this QEP but you get it for free.

Once the form/attr-table-row context has access to the currently edited feature, a value-relation filter can have access to the geometry and make a filter out of it: for example (not sure about the syntax but you get the idea:

... AND contains(buffer( $geometry, 10), current_form_geometry)

where current_form_geometry is the geometry of the feature being edited and $geometry is the geometry of the features from the value-related layer in the value-relation widget.

**Comment by m-kuhn** [comment]
Yeah, that's been on my wish list too. I actually still hope to find someone to sponsor an interactive slider for the relation reference widget to control the size in your abovementioned expression.

**Comment by elpaso** [comment]
@m-kuhn about the `"field_name"` in the expression : the expression filter that you set in the widget configuration run in the related layer, so "field_name" is a field in the related layer (not in the one you are editing)
but, with my new function you have access to the values of the main layer (the one you are editing) within the filter in the related one, this allows you to make the filter dynamic
I hope the video explains it well.

**Comment by m-kuhn** [comment]
I see, so the feature gets set from the related layer (and not from the current layer). That definitely makes sense!

**Comment by vidarusny** [comment]
is the get_current_form_value function implemented in 3.28?
because I can't find it

**Comment by jhonalex06** [comment]
> is the get_current_form_value function implemented in 3.28? because I can't find it

You can use the following expression:

    current_value('field_name')
