### ISSUE TITLE
[processing] create and manage label in WidgetWrapper class

### ISSUE THREAD

**Issue by rkanavath** [qgis/QGIS-Enhancement-Proposals#117]
# QGIS Enhancement: create and manage label in WidgetWrapper class

**Date** 2018/03/16

**Author** Rashad Kanavath (@rkanavath)

**Copyright** CNES, CS-SI 2018

**Contact** rashad.kanavath at c s fr

**maintainer** @nyalldawson , @alexbruy 

**Version** QGIS 3.2

# Summary

AlgorithmDialog and ModelerParametersDialog manages a list of wrappers, labels, widgets 
A wrapper is an instance of widgetWrapper class and already has a member that hold QWidget. It is possible to add "label" member to WidgetWrapper class so that there is no need to manage three lists in modeler. Just one which is list of wrappers.

## Proposed Solution

Add `WidgetWrapper.createLabel` method that will create a QLabel and store it in self.label.  If dialog type is BATCH then it returns None. 
For checkboxes which are instance of BooleanWidgetWrapper, we override createLabel method and returns None if dialog type is MODELER

https://github.com/qgis/QGIS/pull/6614
https://github.com/qgis/QGIS/pull/6614#issuecomment-373559463

### Example(s)

(optional)

### Affected Files
python/plugins/processing/gui/ParametersPanel.py 
python/plugins/processing/gui/wrappers.py
python/plugins/processing/modeler/ModelerParametersDialog.py

## Performance Implications

None 

## Further Considerations/Improvements

set tooltip when creating label in createLabel method

## Backwards Compatibility

End-user functionality is same. so changes are compatible

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by elpaso** [comment]
I'm just concerned about naming: in core we already have a `QgsWidgetWrapper` class, is this related?
If it is not, I would suggest adding a (Processing) prefix to avoid confusion with the existing core class.

**Comment by rkanavath** [comment]
@elpaso , i don't think both classes are related. if there is confusion it can renamed, but can i include such change in this PR?

**Comment by elpaso** [comment]
Yes please, maybe just `ProcessingWidgetWrapper` or something similar that make it clear that it has nothing to do with `QgsWidgetWrapper` used in forms and tables in the main QGIS application.

**Comment by nyalldawson** [comment]
@elpaso WidgetWrapper class has been around in processing since 2.x - it's part of the processing API contract and we can't change it now (until 4.0)

**Comment by rkanavath** [comment]
@nyalldawson, I am skipping change on WidgetWrapper class names.

**Comment by elpaso** [comment]
@nyalldawson nevermind, I thought it was introduced by this QEP.

**Comment by rkanavath** [comment]
@elpaso , you can see all changes in associated PR https://github.com/qgis/QGIS/pull/6614
