### ISSUE TITLE
Temporal support in QGIS map renderer/application

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#128]
# QGIS Enhancement: Temporal support in QGIS map renderer/application

**Date** 2018/07/12

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall dot dawson at gmail dot com

**Version** QGIS 3.4 (or later)

# Summary

A number of different areas and projects relating to QGIS have long been involved with exposing temporal and animation support to QGIS. These include:

Current projects:

- the Time Manager plugin
- the Crayfish plugin
- the inbuilt QGIS property system (e.g. data defined symbology)
- the new 3d animation support

Potential future work:

- QGIS Desktop WMS-T client support
- QGIS Server WMS-T support (see #110)
- Time based, dynamic datum transform support (such as the Australian GDA2020 datum)
- Trajectory support

This QEP is intended as a "gathering place" to discuss a unified approach toward temporal and animation handling within QGIS. A unified approach is desired, as it would allow these different animation related components to work together. For instance, a mesh layer animation which also uses Time Manager to filter a set of vector point events, which are dynamically styled/animated using data defined symbology based on time.

## Use cases

Potential use cases include:

### Vectors

- a layer with events, one attribute is a timestamp of the event
- a layer with intervals, two attributes with timestamps - one for the start, the other for the end
- several layers with the same attributes, recording state of objects at the time (or interval) of the layer (the time may come from layer's name or metadata)
- vector layers with trajectory attributes

### Rasters

- a layer with multiple bands, each band having a different timestamp
- several layers, each layer having a different timestamp (each layer can have multiple bands)

### Meshes

- a layer with multiple datasets, each dataset having a different timestamp

### Map Rendering

Initially, the QGIS core map rendering classes need modification to handle the desired timeframe corresponding to a map render. This could be done by exposing a new date time range member within QgsMapSettings.

E.g.

    void setTemporalRange( const QgsDateTimeRange& range );

Using QgsDateTimeRange allows for either a range of times (i.e. start to end time) or a single "moment" in time (by specifying an equal start/end time for the range).

This would allow standalone scripts and plugins which render maps to specify the time slice for which the map should be rendered. Additionally, it will allow server to render responses for a specific time range, which is a pre-requisite for server WMS-T support (see #110).

The temporal range would also be added as a member within QgsRenderContext (and copied from the map settings in QgsRenderContext::fromMapSettings). This would allow individual map layer renderers access to the desired temporal range, so that e..g QgsMeshLayerRenderer can utilise the time range within the passed QgsRenderContext to render the correct dataset.

The temporal range would also be exposed as new variables (e.g. `@map_timestamp_begin` and `@map_timestamp_end`) within the map settings expression context scope (see `QgsExpressionContextUtils::mapSettingsScope()`). This would allow expressions to access the current map temporal range, allowing for data defined symbology and labeling to respond the current time slice. (Much like how Time Manager currently exposes the `animation_datetime()` function). 

### QgsMapCanvas (and setting the current time slice)

The current temporal range for the map canvas would be exposed via methods within QgsMapCanvas. 

Time Manager (and other plugins) would be able to access the current canvas temporal range through `QgsMapCanvas::mapSettings() `.  

A new setter could be added to QgsMapCanvas to allow plugins to specify the current time slice shown in the canvas, e.g.

    void setTemporalRange( const QgsDateTimeRange& range );

Calling this would update the canvas' internal map settings' temporal range and cause a re-render of the canvas. (A `temporalRangeChanged` signal would also be fired prior to re-rendering the canvas).

### GUI control for time/animation

Lastly, a new gui widget for controlling the current temporal range displayed in the map canvas would need to be created. This could be based heavily off Time Manager's widget (see https://underdark.files.wordpress.com/2011/09/timemanager.png ), which allows both the start time stamp and duration of the range to be set (i.e. allows for both the start and end timestamps required for QgsDateTimeRange to be controlled).

Ideally, a common base class should be created to allow the 3d animation widget to share common code/functionality with the 2d canvas widget.

## Further Considerations/Improvements

This is just an early prototype design, intended for discussion amongst interested parties!

## Backwards Compatibility

N/A

## Votes

(required)

**Comment by nyalldawson** [comment]
Ping @wonder-sk @anitagraser

**Comment by PeterPetrik** [comment]
Animation and temporal support is handled by mesh layer & MDAL [QEP 119](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/119)

**Comment by haubourg** [comment]
ping @vmora, I bet this is of high interest for you

**Comment by nyalldawson** [comment]
@peterpetrik

From #119:

"This QEP intentionally tries to stay away from dealing with time component as that is quite a large topic itself. We assume that plugins may introduce convenience functionality for handling of the temporal nature of mesh layers (e.g. easy moving between time steps, animation, export of videos). In the future we would like to look into having a separate QEP to cover time component within QGIS for all types of map layers."

Consider this that separate PR ;)

**Comment by nyalldawson** [comment]
It's been pointed out that #110 also relates - I'll include that as another component in this qep

**Comment by PeterPetrik** [comment]
@nyalldawson Thanks for starting this discussion, it would be great to have common code and widgets. We thought at the beginning that handling of time (steps) will be fully handled by external plugins, but now it seems that we slightly shifted as we already have "time" slider in the mesh layer styling panel. 

Besides rendering, we need to solve how individual layers/bands form temporal group and how it is represented in the GUI (in layer tree?). Crayfish (MDAL) does some magic to guess which layers/gdal bands/files represents same data but in various times and GUI uses "active dataset" to select time to render (QgsMeshRendererActiveDatasetWidget).

**Comment by saberraz** [comment]
I think in addition to rendering, we probably need to consider analytical side of temporal data for the Processing toolbox: e.g. aggregate functions and temporal data calculator.

**Comment by wonder-sk** [comment]
Great to see some action towards temporal data support in QGIS :-)

I think it would be good to start with a bunch of use cases that we would like to cover under the temporal framework (and maybe even a list of use cases we explicitly decide to ignore). Various types of temporal data sources:
- vectors
  - a layer with events, one attribute is a timestamp of the event
  - a layer with intervals, two attributes with timestamps - one for the start, the other for the end
  - several layers with the same attributes, recording state of objects at the time (or interval) of the layer (the time may come from layer's name or metadata)
- rasters
  - a layer with multiple bands, each band having a different timestamp
  - several layers, each layer having a different timestamp (each layer can have multiple bands)
- meshes
  - a layer with multiple datasets, each dataset having a different timestamp
Are there some other common scenarios?

The next thing is what the timestamps actually mean - are they concrete instances of time ("absolute") or are they relative times that do not have a reference time? Relative times are common for simulations.

While the most common case of a vector with an attribute having absolute timestamps can be handled easily even without explicitly defining its temporal domain, I think it will be an important part of the implementation to have some temporal metadata assigned to layers (and maybe go as far as grouping e.g. a bunch of "ordinary" map layers into a single "temporal" layer that would be shown in the layer tree and its sub-layers would share style etc.)

It may be good to get some inspiration from GRASS GIS and how temporal data support is implemented there: https://grass.osgeo.org/grass74/manuals/temporalintro.html

Things get more interesting when there are multiple temporally enabled layers in a project, possibly with different temporal domains - how do we work with them? I assume there would be just one time slider, and users would pick which temporal layers are static (fixed to a time instance/interval) and which are transient (moving with the time slider).

It may be good to think about what time ranges / precision are we going to support - I suppose there will be people requiring second/millisecond precision, as well as geologists going some billions of years there and back :-)

When we get to animating things, it will be probably also good to make distinction between the animation time and the current map time (or interval). For example the animation for 3D view does not need to be related to temporal data - it can simply animate camera within one time instance of the map (a static scene).

It would be really cool if we also had support for interpolation of temporal data in between time instances:
- a temporal point layer with vehicle movement where point positions would get interpolated
- a temporal raster layer where the resulting raster would be a cross-fade between two rasters

Those who will be using temporal rasters will be probably very keen to have a profile tool to be able to visualize changes in one or more points (think a graph of precipitations in London over last 30 years).

Support for processing algorithms would be another big topic I do not want to dig into, but for those algorithms I can see there is a strong need to have a QGIS wide temporal metadata defined for temporal layers, so that the algorithms can use that information (and the temporal metadata do not need to be defined separately every time).

OK I will stop here :-)

**Comment by wonder-sk** [comment]
The workshop for working with temporal data in GRASS is also worth checking out:
http://ncsu-geoforall-lab.github.io/grass-temporal-workshop/

**Comment by nyalldawson** [comment]
> The next thing is what the timestamps actually mean - are they concrete instances of time ("absolute") or are they relative times that do not have a reference time? Relative times are common for simulations.

**Comment by nyalldawson** [comment]
@wonder-sk 

> The next thing is what the timestamps actually mean - are they concrete instances of time ("absolute") or are they relative times that do not have a reference time? Relative times are common for simulations.

I would say we always use absolute time. For sources with relative time, you could either

1. Set a time adjustment via the layer properties, e.g. set the "start" or "end" time for the layer.
or 
2. Leave the time as completely relative, in which case the times are made absolute by adding them to an "origin" time for the project. (So e.g. changing the "start" time for the project time slider would then shift all relative data source times accordingly.)

But ultimately, we should transform all relative time values into an absolute time to allow a common timeframe across all project sources.

> Things get more interesting when there are multiple temporally enabled layers in a project, possibly with different temporal domains - how do we work with them? I assume there would be just one time slider, and users would pick which temporal layers are static (fixed to a time instance/interval) and which are transient (moving with the time slider).

I might be misinterpreting, but I'd envisage temporal support will always be "opt in" for layers. E.g. you'd go to layer properties, and tick a "temporal" check box (and then setup start time/end time fields, time offsets, time zones, etc). And ANY layer which has been temporally enabled would be affected by the time slider. Non-temporal enabled data sources would be handled manually, e.g. like how mesh datasets are currently handled in master. These are static and not impacted by the time slider. So basically we have a single temporal domain per project.

> a temporal point layer with vehicle movement where point positions would get interpolated

For reference, the Time Manager plugin currently supports this.


> When we get to animating things, it will be probably also good to make distinction between the animation time and the current map time (or interval). For example the animation for 3D view does not need to be related to temporal data - it can simply animate camera within one time instance of the map (a static scene).

Good point!

**Comment by kbevers** [comment]
I think this is a very interesting proposal. I also think that it goes a bit deeper than initially suggested, although the discussion is starting to unveil the depths of what is needed for temporal support. So here's something that falls under the "further considerations/improvements" category. I have previously been advocating for QGIS adopting spatiotemporal coordinates. It seems to me that doing so would help implement some of the ideas presented here. You would get an obvious place to put the timestamps and you would be able to delegate most of the work to PROJ. After all, keeping track of time is one of the [core disciplines within geodesy](https://en.wikipedia.org/wiki/International_Earth_Rotation_and_Reference_Systems_Service).

> The next thing is what the timestamps actually mean - are they concrete instances of time ("absolute") or are they relative times that do not have a reference time? Relative times are common for simulations.

This is the sort of stuff that the [GDALbarn](https://gdalbarn.com) work will make it simpler to deal with. WKT2 CRS descriptions include options for describing the temporal reference frame.

> But ultimately, we should transform all relative time values into an absolute time to allow a common timeframe across all project sources.

This is an obvious job for PROJ, handling transformations between different time frames. Of course this is not something we can do just yet but if it is necessary for QGIS and other projects it can be prioritized. I am happy to mentor this if someone from the QGIS community should have an interest in contribution such code.

Of course I am aware that what I am proposing will be slowing development down so I don't expect it to happen at this time. I just want to highlight the potential synergies here and let you know what's to come in the future for PROJ, in case you were not aware.

**Comment by anitagraser** [comment]
>  I have previously been advocating for QGIS adopting spatiotemporal coordinates.

Thanks @kbevers, I just wanted to suggest the same thing and add to @wonder-sk's list that a vector layer use case can also be **trajectories of moving objects**. If we could work out how to deal with spatio-temporal features, such as trajectories, that would be a huge step forward for GIS.

> QGIS Desktop WMS-T client support

TimeManager does support WMS-T but it's not pretty :-|

**Comment by pcav** [comment]
timestamptz? https://www.postgresql.org/docs/11/static/datatype-datetime.html

**Comment by nyalldawson** [comment]
@kbevers 

> I think this is a very interesting proposal. I also think that it goes a bit deeper than initially suggested, although the discussion is starting to unveil the depths of what is needed for temporal support. So here's something that falls under the "further considerations/improvements" category. I have previously been advocating for QGIS adopting spatiotemporal coordinates. It seems to me that doing so would help implement some of the ideas presented here. You would get an obvious place to put the timestamps and you would be able to delegate most of the work to PROJ. After all, keeping track of time is one of the core disciplines within geodesy.

Good point -- I'd neglected the potential requirement for dynamic transforms to also consider timestamps. I'll add it to the QEP text.

**Comment by nyalldawson** [comment]
@anitagraser 
> I just wanted to suggest the same thing and add to @wonder-sk's list that a vector layer use case can also be trajectories of moving objects. If we could work out how to deal with spatio-temporal features, such as trajectories, that would be a huge step forward for GIS.

Also added, thanks!

**Comment by nyalldawson** [comment]
Ok, in order to keep this moving and avoid it becoming just a wishlist dumping ground, I'd like to propose that as a first step toward time handling we:

- Implement the original proposal (above) and add an **absolute** time range option to QgsMapSettings:

```
    /**
     * Sets a temporal \a range to restrict the data displayed within map renders to a specific time range.
     *
     * If no temporal range is set, or if a default constructed QgsDataTimeRange is used, then data from
     * all time periods will be included. 
     *
     * \see temporalRange()
     * \since QGIS 3.4
    */
    void setTemporalRange( const QgsDateTimeRange& range );

    /**
     * Returns the current temporal range used to restrict the data displayed within map renders to a specific time range.
     *
     * If no temporal range is set a default constructed QgsDataTimeRange will be returned, and data from
     * all time periods will be included.
     *
     * \see setTemporalRange()
     * \since QGIS 3.4
    */
    const QgsDateTimeRange& temporalRange() const;
```

- Add a setting to enable temporal support to QgsMapLayer. Eventually this would be exposed in the GUI as a checkbox at the top of a future "time" tab in the layer properties dialog:

```
    /**
     * Sets the map layer as a temporal layer, which will be considered when rendering maps with a specific time range set.
     *
     * If the map layer is not set as temporal, then any other temporal settings relating to the map will be ignored during rendering.
     *
     * \see isTemporal()
     * \since QGIS 3.4
    */
    void setIsTemporal( bool enabled );

    /**
     * Returns true if the map layer is a temporal layer, and will be filtered when rendering maps with a specific time range set.
     *
     * If false is returned, then any other temporal settings relating to the map will be ignored during rendering.
     *
     * \see setIsTemporal()
     * \since QGIS 3.4
    */
    bool isTemporal() const;
```

- Add an option to set a fixed temporal range for a QgsMapLayer (analogous to the map minimum/maximum scale - i.e. the whole layer is NOT rendered if the layer's fixed temporal range does not intersect with the map settings temporal range):

```
    /**
     * Sets a temporal \a range to restrict the layer visibility only for map renders which intersect this time range.
     *
     * \note Temporal based visibility is only considered when isTemporal() returns true.
     *
     * \see temporalRange()
     * \since QGIS 3.4
    */
    void setTemporalRange( const QgsDateTimeRange& range );

    /**
     * Returns the temporal range used to restrict the layer visibility only for map renders which intersect this time range.
     *
     * \note Temporal based visibility is only considered when isTemporal() returns true.
     *
     * \see setTemporalRange()
     * \since QGIS 3.4
    */
    const QgsDateTimeRange& temporalRange() const;
```

This would initially meet the use cases of:

- Vectors: several layers with the same attributes, recording state of objects at the time (or interval) of the layer (the time may come from layer's name or metadata)
- Rasters: several layers, each layer having a different timestamp (each layer can have multiple bands)


(Obviously, this is the core API changes only - and we'd need to expose these settings in the UI and implement the time slider).

Any objections to locking this in as a first step?

**Comment by pcav** [comment]
No objection from my side.

**Comment by anitagraser** [comment]
This means that the whole layer will have a timestamp or timerange, instead of each feature having its own timestamp, right?

> Vectors: several layers with the same attributes, recording state of objects at the time (or interval) of the layer (the time may come from layer's name or metadata)

**Comment by nyalldawson** [comment]
@anitagraser

> This means that the whole layer will have a timestamp or timerange, instead of each feature having its own timestamp, right?

Correct - I'm just trying here to address the simplest use case first so that we can get the fundamental questions decided (like absolute vs relative time) without getting bogged down on the details of the more complex use cases. API for per feature timestamps will be on top of the per layer timestamp API.

**Comment by PeterPetrik** [comment]
Let say I have 30 weather GRIB files, each representing a temperature of the same area in different days during one month. It is obvious what I get when I want to render QgsDateTimeRange=timestamp(10.Jan.2018). But what is the resulting image when I want to render first week QgsDateTimeRange=range(1.Jan.2018-7.Jan.2018)? Is it some kind of animation or merge of all individual images?

**Comment by rduivenvoorde** [comment]
@PeterPetrik @nyalldawson I think how the resulting image (aka the mapcanvas via the mapsettings) is handling all the different use cases, is up to some intelligent 'player/timehandler'. 

That object has to be able to decide what to do when you have several layers with different kind of time ranges OR points in time. The above leaflet plugin for example has possibilities to either find out the max and min, or do an union of the times or a slice etc. And myself I had use cases where I needed a player (aka the time slider) in which I could set and change the range (so individually move the start and time gripper) and after that move the resulting range as a whole on distinct time points.

The case you describe above could be handled in the same way as Geoserver handles an 'image mosaic', that is if you sent one TimeStamp it will only show you those gribs/rasters which have exact that TimeStamp in their layer info. If you sent a TimeRange, it will collect all gribs/rasters and merge them.
OR IF you want (now looking at you grib) an animation you have to have some 'player' which shows only one (or a small set) of layers at a time, by showing a moving range (see the [LeafLet plugin examples](http://apps.socib.es/Leaflet.TimeDimension/examples/) for some nice use cases and examples).

Handling time data is a box of pandora :-)

**Comment by nyalldawson** [comment]
Following on from a joint conference call last week with myself, @PeterPetrik , @timlinux , @anitagraser  and @saberraz and @samweli - it was agreed that the core changes described in this QEP were acceptable and that requiring an absolute datetime range on the QgsMapSettings/QgsRenderContext level is appropriate.

It will be the individual map layer subclass' responsibility to transform any relative datetimes (or non-datetime values) into an absolute datetime for use in map renders, using a method which is suitable for that layer type (and exposing any user-facing settings for controlling this behavior as deemed necessary)

**Comment by whatnick** [comment]
I have a lot of WMS Time Based servers running in OWS. Keen to test and contribute.

**Comment by Nic-Rosengren** [comment]
Is there any possibility of addition of time in Millions of years before present?  Geochronological data its typically presented in the form XXX.xx  Ma  (eg 144.7 Ma) being 144.7 million years ago.  It would be great to be able to step through this data which i currently cant see how to do?

**Comment by vmora** [comment]
Thanks @Nic-Rosengren, I had fun trying to go back in time with postgresql date type and overflowed at '4714-12-31 BC',  even archeologists will be frustrated with that.
