### ISSUE TITLE
Field calc - save and load expressions files

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS-Enhancement-Proposals#135]
# Field calc - save and load expressions files

**Date** 2018/11/28

**Author** Salvatore Fiandaca (@pigreco)

**Contact** pigrecoinfinito@gmail.com

**maintainer** @pigreco

**Version** QGIS 3.4

# Summary

**Add the buttons to save and import the most important expressions, to save time.
The recent group stores the first 20 expressions, but they always change.**

## Proposed Solution

(required)

### 
![image](https://user-images.githubusercontent.com/7631137/49137657-64603e00-f2ed-11e8-8cf1-6bbab314c7c2.png)

(optional)

### Affected Files

(required if applicable)

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

**(required)**

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by Korto19** [comment]
it would be really useful

**Comment by Jacopoog** [comment]
LOVELY Function Totò!!
Looking forward. It may be the first step to an "Automated field calc on several layers" new feature? I.E. a list/table with SavedFuncions to be applied to each Layer
By now, many many Thanks!!

**Comment by pigreco** [comment]
### Here is a possible flow:
1. I write expression,
2. expression is valid;
3. I can save my expression;
4. by pressing on floppy, the dialog window opens; which displays the expression and define the name and description;
5. list of saved expressions;
6. possibility of eliminating expressions selected by the group, the icon appears only if an expression is selected.

![image](https://user-images.githubusercontent.com/7631137/69535506-68fd1800-0f7c-11ea-9fc7-639e65614978.png)

**Comment by Korto19** [comment]
Wonderful, this is what was missing. Very Very good Toto !

**Comment by elpaso** [comment]
I like the idea, I just would probably move the delete icon to the top to be consistent with the toolbar layout but that's a minor detail really.

Also we might consider adding a bulk import/export utility for stored expressions.

**Comment by jurajbetak** [comment]
Hello,
just some thoughts to design:

- LOAD icon next to the SAVE icon (this might actually open the combo EXPRESSIONs SAVED)
- What actually happens when you click the DELETE icon?) Instead, I would prefer to have Expression Manager (another icon next to SAVE) - with a separate window, where you can Delete, Edit, Create description notes, Import and Export (that would be nice if I can export my expressions e.g. to ZIP and import them elsewhere), ...

**Comment by elpaso** [comment]
> Hello,
> just some thoughts to design:
> 
>     * LOAD icon next to the SAVE icon (this might actually open the combo EXPRESSIONs SAVED)
> 

What for? The saved expressions appear in the expression tree under "Stored (generic)" (or whatever the context is).

>     * What actually happens when you click the DELETE icon?) 

The idea is that the delete icon will only appear when a stored expression is selected in the expression tree, the user will be asked for confirmation and the expression will be removed from the stored expressions. We might provide a context menu but in my experience that's the last resource in UX/UI design, it's much better and simpler to have a visible element to perform an action.

> Instead, I would prefer to have Expression Manager (another icon next to SAVE) - with a separate  window, where you can Delete, Edit, Create description notes, Import and Export (that would be nice if I can export my expressions e.g. to ZIP and import them elsewhere), ...

I agree, that would be also nice to have, but requires a bit more work, and it could be done later once the foundation API to store, retrieve and delete stored expressions is in place.

**Comment by pigreco** [comment]
## FIELD CALC DI QGIS – SAVE EXPRESSIONS – (CROWDFUNDING)

--

https://pigrecoinfinito.wordpress.com/2019/12/14/field-calc-di-qgis-save-expressions-crowdfunding/

**Comment by pigreco** [comment]
Done [#33437](https://github.com/qgis/QGIS/pull/33437) and [#33462](https://github.com/qgis/QGIS/pull/33462)
