### ISSUE TITLE
Relax QGis python requirements?

### ISSUE THREAD

**Issue by Puffton** [qgis/QGIS-Enhancement-Proposals#136]
Would it be possible to relax QGis Python requirements? Right now it's a precise version of 3.6, how about requiring the same major version, and *at least* the same minor version? That would simplify things a lot for me, and would keep me from having three different python installs on OS X (3.7, 3.6, 2.7).

**Comment by saberraz** [comment]
@Puffton please open a ticket here:
https://github.com/lutraconsulting/qgis-mac-packager

The OSX packages from above link don't need any python requirements. Everything is packaged within the app.
