### ISSUE TITLE
Symbol aware legend expression

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS-Enhancement-Proposals#137]
# QGIS Enhancement: Title

**Date** 2019/01/09

**Author** Myself, Nyall Dawson (@nyalldawson ) and whoever else want to participate.

**Contact** alroyliz0 at gmail dot com

**maintainer** unknown

**Version** QGIS 3.6 [edit 3.8?]

# Summary

The goal of this proposition is to replace the FeatureCounter in the legend by a QgsExpression in order to allow more complex elements to be displayed dynamically in the legend (such as field statistics grouped by legend and visible extent or any strings). This would evaluate the expression using the visible map extent (if filtering visible element is activated) and be done at for each symbology of a layer.

The goal would be to obtain statistics such as the total area(or any other variable) of visible features for each legend symbol with a static string at the end. Or any other type of expression.

Currently the design and implementation is still mostly in the planing stage. 

In order to make this possible some of these elements would need to be implemented:

- Symbol scope or any other mean to filter out legend symbol/keys and the associated features

-  Implement the base class to have the necessary filtering and behavior depending on the operation (separate behaviors for aggregate expressions, strings only, or field based)

- Change the UI to use the expression instead of the counter

- Refactor the related classes 

- ? implementing feature filtering based on extent and caching it instead of using requests?

## My Section
 Core implementation
Possibly UI
Unit test?
To be determined/whatever I can do.

## Proposed Solution

To be determined

### Example(s)

None

### Affected Files

qgslayertreemodellegendnode.cpp (line 509)
QgsLayoutItemLegend
QgsAggregatecalculator
Maybe every vector/raster renderer if the symbol scope or it's alternative needs to obtain a list of feature per key/symbol.
To be determined

## Performance Implications

Unknown

## Further Considerations/Improvements

-Optionnal: Caching visible layers per extent. This could be used to filter out QgsFeatureRequest or at least replace the option to filter out feature by Atlas extent in the legend .

## Backwards Compatibility

None?

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

N.B.: The project is still in elaboration, contributions/suggestions are very welcome.

**Comment by roya0045** [comment]
See Qgs Pull #8891

**Comment by roya0045** [comment]
Core is operational, UI remains.

**Comment by haubourg** [comment]
a big +1

**Comment by roya0045** [comment]
> a big +1

The pull is awaiting review by Mr. Dawson and anyone that is willing. With luck it might be merged this week in time for the next nightly build.

**Comment by roya0045** [comment]
Still pending review merging, behaviour has been improved to not stall and expressions can now be inserted anyhow since the original label will be converted and handled as a variable to allow more flexibility.

**Comment by roya0045** [comment]
Now replaced by PR #9846.

**Comment by roya0045** [comment]
Turns out featurerequest and the iterators needed to be modified too. Pending PRs.

**Comment by roya0045** [comment]
feature request PR has been merged.

Improved feature iterator and filter stacking is pending.

The first part of the main PR should be merged soon.

What remain is: 

- Revisiting how symbol fids are stored
- Revisiting how symbol are accessed
- Adding a symbol_id parameter to aggregate expressions (instead of parsing the string, rely on the user for filtering) 
- Stack fids and expression filters (once the PR is merged)

**Comment by roya0045** [comment]
New approaches based on expressions entirely are pending review. These should not have any downsides to any other thing. Still hoping to leave PR limbo. :(

**Comment by roya0045** [comment]
See https://github.com/qgis/QGIS/pull/33632 , https://github.com/qgis/QGIS/pull/33819 and https://github.com/qgis/QGIS/pull/34476 for usability.

**Comment by jgrocha** [comment]
@roya0045 Can you share some screenshots of the resulting legend and the interface to write down the expressions?

**Comment by roya0045** [comment]
@jgrocha Based on the current proposed PR here is the workflow: 

Use the expression function in the layout legend:
![Wheree](https://user-images.githubusercontent.com/12854129/76520027-77dade00-6438-11ea-834c-94c4aa6930a4.PNG)

Make your expression ( the current symbol expression is represented by @symbol_label) and to leverage the existing symbology you must filter by the expression representing the symbol @symbol_expression as implemented in https://github.com/qgis/QGIS/pull/33632)
![How](https://user-images.githubusercontent.com/12854129/76520126-b1134e00-6438-11ea-996b-739137ce7ec4.PNG)

Conditions can be combined such as using the extent of the layout map as the legend filtering by atlas or extent has no bearing on the expressions (this could be done but is not done to ensure that constant results can be achieved).

Then the expression simply replaces the text in the legend in order to provide the most flexibility to the user:
![What](https://user-images.githubusercontent.com/12854129/76520171-cdaf8600-6438-11ea-8c8e-5a865395e3e7.PNG)

Please let me know if this is helpful.

**Comment by jgrocha** [comment]
Thanks @roya0045 for the screen. It makes your proposal more clear to me. The images are quite clear.

For almost every interaction on the map, these expressions must be evaluated. I can see some overhead in a project with many layers (and layers from providers retrieving remote data).

Right now (in current QGIS), the user can enable/disable the legend based on the extent, because this option can have a dramatic overhead if enabled. Are you considering something similar? The user can enable/disable these expressions if it has many layers? (Sorry for asking. I didn't check the code)

**Comment by roya0045** [comment]
@jgrocha The current implementation evaluate only layers with an expression in the label or stored in the maplayer. Though the issue is that currently everything is evaluated three times when rendering the legend. For that reason I have made https://github.com/qgis/QGIS/pull/34476 to evaluate the expressions only once when rendering. I have tested with a layer with half a million features and 20 categories and with that optimisation the evaluation is quite bearable. Otherwise without this optimisation qgis would stay frozen 90% of the time to re evaluate everything three time.

Simple expressions are fast to eval, only with aggregate things can take some time. The user can simply change the expression and upon reopening the project the cached expressions are removed ( they are not stored permanently actually). 

If you want to give it a try you can use this https://github.com/roya0045/QGIS_1/actions/runs/53810586 , keep in mind that this version contains the optimisation, this is the one without the optimisation https://github.com/roya0045/QGIS_1/actions/runs/50990857

**Comment by roya0045** [comment]
@jgrocha I have found what was causing the issue with the weird refresh, the next build of those branches should be better and far more responsive.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
