### ISSUE TITLE
Find unmaintained plugins

### ISSUE THREAD

**Issue by thbaumann** [qgis/QGIS-Enhancement-Proposals#138]
# Find unmaintained plugins

**Date** 2019/02/08

**Author** Thomas Baumann (@rdbath)

**Contact** rdbath.regiodata@gmail.com

**maintainer** @rdbath

**Version** QGIS 3.X

# Summary

Some plugins have a lot of open issues or pull requests but there is no reaction from the maintainer.

I made the experience that buggy unmaintained plugins can cause a lot of frustration to users and that problems caused by such plugins are also very bad for the reputation of qgis.

## Proposed Solution

Check every year if a plugin is still maintained. Therefore an email with a confirmation link could be sent to maintainer of plugins which have not been updated in the last (3? 6? 9?) months. If there is no reaction from the maintainer there could some reminder-emails be sent (within a period of 3 month) until the plugin could be flagged as unmaintainded if the confirmation-link was not clicked by the maintainer.

The flag "unmaintained" could easily be removed as soon as the maintainer confirms that the plugin is still maintained. 
The plugin would always be available in the plugin-manager and could be installed. So the flag would be just an information for the user that he/she is going to install a plugin which is not under active maintanance.

### Example(s)

http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Rectangles-Ovals-Digitizing-plugin-deprecated-td5366686.html 

## Votes

(required)

**Comment by luipir** [comment]
can you articulate it the process should be automatic or there would be a person in charge to check every year?

**Comment by rdbath** [comment]
Paolo Cavalini had following idea: "An alternative would be to add to our Django app an
automatic reminder to be sent to maintainer, asking to confirm they
maintenance": http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Find-unmaintained-plugins-tp5393747p5393772.html

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
