### ISSUE TITLE
Clean up organisation repos

### ISSUE THREAD

**Issue by mbernasocchi** [qgis/QGIS-Enhancement-Proposals#146]
# QGIS Enhancement: Clean up organisation repos

**Date** 2019/05/24

**Author** Marco Bernasocchi (@mbernasocchi )

**Contact** marco@qgis.org

**maintainer** @mbernasocchi 

**Version** QGIS github organisation 

# Summary
I'd like to clean up the QGIS organisation repository list on GitHub and suggest archiving or deleting the following repository. I added all the last commiters to all repos to have their opinions.

## suggesting deletion since empty or now useless
~~https://github.com/qgis/redmine_migration_test (@m-kuhn)~~
~~https://github.com/qgis/QGIS-i18n (@3nids, @m-kuhn)~~

### Dead looking
~~https://github.com/qgis/QGIS-Compilation-Guide (@dassau, @mach0 , @cfarmer)~~
~~https://github.com/qgis/QGIS-workshop (@yjacolin, @Jean-Roc)~~
~~https://github.com/qgis/QGIS-OSGEO-Live-Tutorials (@pka, @mhugent)
https://github.com/qgis/QGIS-Redmine-Hub (@pka, @mwa)
https://github.com/qgis/pyqgis_wrappers/ (@volaya, @NathanW2)
https://github.com/qgis/QGIS-Processing (@volaya)~~

~~### Kartoza forks but not kept up to date with upstream (@timlinux)
https://github.com/qgis/docker-postgis
https://github.com/qgis/docker-qgis-desktop
https://github.com/qgis/docker-qgis-btsync
https://github.com/qgis/docker-qgis-server
https://github.com/qgis/docker-qgis-orchestration~~

## please comment below for each repo

**Comment by pcav** [comment]
I agree, the current situation is confusing. The problem has already been put forward recently, I don't think there are major objections.
In short, for me, go to all.

**Comment by mbernasocchi** [comment]
@m-kuhn agreed verbally to remove "his" repos

**Comment by pka** [comment]
* https://github.com/qgis/QGIS-OSGEO-Live-Tutorials -> transfered to sourcepole org
* https://github.com/qgis/QGIS-Redmine-Hub -> archived

**Comment by mbernasocchi** [comment]
thanks @pka

**Comment by yjacolin** [comment]
* https://github.com/qgis/QGIS-workshop is porobably old enough to be archived and started from scratch next time someone need a QGIS workshop.
* This is similar for https://github.com/qgis/QGIS-Compilation-Guide, QGIS build process is probably out of date after QGIS 3 migration.

**Comment by timlinux** [comment]
> Kartoza forks but not kept up to date with upstream (@timlinux)

> https://github.com/qgis/docker-postgis
> https://github.com/qgis/docker-qgis-desktop
> https://github.com/qgis/docker-qgis-btsync
> https://github.com/qgis/docker-qgis-server
> https://github.com/qgis/docker-qgis-orchestration

These can all be removed

**Comment by mbernasocchi** [comment]
Thanks all for the quick help, only one repo left, @volaya, @NathanW2 feel the pressure ;) ?

**Comment by mbernasocchi** [comment]
@pka I added qwc2 to the pinned repos, do you think it is better to pin qwc2 or qwc2-demo-app? 
and could we rename them to QGIS-Webclient-2 and QGIS-Webclient-2-demo-app? the old name would still work and all would be more consistent.
Cheers

**Comment by mbernasocchi** [comment]
@timlinux what is with https://github.com/qgis/demo.qgis.org
looks like a great idea but http://demo.qgis.org is dead (503) :(
@pblottiere was it you building up a demo of the server? I remember reading a cryptic link somewhere but I cant find it.

**Comment by rduivenvoorde** [comment]
No, it was Tim and me who put up a demo site when we first created  a QGIS-server docker. The idea was that people would send nice (small) projects and data to us, and we would show them on demo.qgis.org. 
These were all dockers, and with the last server-hickup-fullstop I did not put them up again (also it seemed nobody mentioned it...).
@timlinux are you able to start the dockers again? Or should we just kill the beast?

**Comment by haubourg** [comment]
@mbernasocchi yes, the demo servers are at http://qgis4.qgis.org:8081/qwc2_demo/

Having a map gallery on  http://demo.qgis.org  would be nice!

**Comment by yjacolin** [comment]
What about https://github.com/qgis/QGIS-Processing ? 2 years without a commit, issues and PR waiting and the processing service à no more download script.

**Comment by mbernasocchi** [comment]
let's try to ping @volaya on this one also

**Comment by volaya** [comment]
Fine for me to remove both of my ones. The QGIS-Processing is not used anymore to download stuff, so it can be safely removed, i think

**Comment by mbernasocchi** [comment]
thanks @volaya

**Comment by mbernasocchi** [comment]
Thanks all for your help.
cheers
Marco
