### ISSUE TITLE
Classification methods refactoring (as used in graduated renderer)

### ISSUE THREAD

**Issue by 3nids** [qgis/QGIS-Enhancement-Proposals#147]
# QGIS Enhancement: Breaks method refactoring (as used in graduated renderer)

**Date** 2019/05/18
**Author** Denis Rouzaud (@3nids)

**Version** QGIS 3.10

# Summary

Current implementations of graduated renderers (breaking or classification methods) are spread within the GUI class of the graduated renderer widget and the core part. This brings a few issues:

* code is hardly testable (currently the methods are not tested I believe)
* introducing new renderers is a painful task (see [recent try](https://github.com/qgis/QGIS/pull/9530) to introduce logarithmic breaks)
* it is difficult to customize the configuration of the renderers (the current symmetric option is only visible for some for instance)
* they are not reusable in other part of the code, such as processing 

This QEP propose to introduce a registry of graduated renderers which would solve the aforementioned issues. 

### Registry

There will be a registry of breaking methods in `QgsApplication` (core). It will be possible to add custom methods via Python.

### Base class

A base class `QgsClassificationMethod`will offer the basic required methods for a break and which would be reimplemented in any implementation.

### Additional configuration

It will be possible to provide additional configuration for the methods in a generic manner, using a dictionary of parameters. These parameters will be provided as Processing Parameters, such as `QgsProcessingParameterNumber` or `QgsProcessingParameterEnum`.

This will allow to use an automated mechanism to build the GUI part of the customizations (and hence avoid any need for GUI components in core.

### API 

```cpp
class QgsClassificationMethod
  public:
    QgsClassificationMethod();

    enum CalculationRequirements 
    {
      BoundsOnly, // only the bounds (min, max) are required to calculate the classes
      ValuesOnly,  // only the value list
      BoundsAndValues, // both
    }; 

    virtual QString name() const = 0;
    virtual QString objectName() const = 0; // as saved in the project
    virtual bool supportsSymmetricMode() const {return false;}
    virtual CalculationRequirements calculationRequirements() const = 0;

    // One and exactly one of the following 3 methods should be re-implemented
    virtual QList<double> classes( double min, double max, double values, int numberOfClasses) const {return QList<double>();} 
    virtual QList<double> classes( double min, double max, int numberOfClasses) const {return QList<double>();} 
    virtual QList<double> classes( double values, int numberOfClasses) const {return QList<double>();} 

    
    // non-virtual
    QList<double> classes( QgsVectorLayer* vl, int numberOfClasses ) const; // this will call the appropriate implementation of classes using values and/or bounds.
    QgsProcessingParameterDefinitions parameterDefinitions() const {return mParameterDefinitions;}
    void setSymmetricMode(bool enabled, double symmetryPoint = 0, bool astride = false);
    QDomElement writeXml( QDomDocument &doc ) const;
    void readXml( const QDomElement &elem );

  protected:
    QgsProcessingParameterDefinitions mParameterDefinitions = QgsProcessingParameterDefinitions();

  private:
    bool mSymmetricEnabled = false;
    double mSymmetryPoint = 0;
    bool mAstride = false;

```

### Test

Tests will be added to all existing breaks methods (EqualInterval, Quantile, Jenks, StdDev, Pretty)

### Not included in this work

* Creating logarithmic break method (although would be much easier afterwards)
* Making the breaks accessible in processing

## Changelog

2019-05-26 renamed breaks->classification, added API as requested by @nyalldawson

## Votes

(required)

**Comment by nyalldawson** [comment]
Another thing to consider with this would be unification of raster class break calculation with vector.

> A base class QgsBreakingMethod (any better idea welcome!) 

QgsClassifier? QgsClassificationMethod?

Can we see the proposed API for this class?

**Comment by 3nids** [comment]
@nyalldawson added first draft of the base class

**Comment by nyalldawson** [comment]
Thanks

>    QList<double> classes( QgsVectorLayer* vl, int numberOfClasses ) const; // this will call the appropriate implementation of classes using values and/or bounds.

Would be good to have:
- option for running on a QgsFeatureIterator (or QgsFeatureSource) 
- options for running on a raw list of values
- options for running with a lambda function to retrieve values? (.e.g. via a raster block)

**Comment by rduivenvoorde** [comment]
Thanks @3nids would be very good to tackle this. Code is really scattered. 

Adding to the comment @nyalldawson and said in https://github.com/qgis/QGIS/pull/9530 would be very nice if we create some 'breaks'-factory, not only for raster and vector, but also for Mesh (as that is a third source of break-creators).

I understand that the ui is not part of this proposal? But there are some very strange things going on when using combinations of checkboxes. Recreation of classes etc, on moments you do not expect and or no recreation when you expect. I think that has for example to do with the fact that the calculation of certain breaks is data/cpu intensive (eg calculating the median of part of the whole data). If we could have some 'cache' for that calculations, the 'recalculation' can maybe reused.

**Comment by pcav** [comment]
+1 from me. I think we should include a clear plan for upgrading the UI as well.
Thanks!

**Comment by 3nids** [comment]
@nyalldawson 
> option for running on a QgsFeatureIterator (or QgsFeatureSource)

What's the use case here? (i.e. when you don't have vector layer)

> options for running on a raw list of values

Isn't the proposed 3  `classes` methods enough? Or do I miss the point?

> options for running with a lambda function to retrieve values? (.e.g. via a raster block)

What's the advantage from running with the values directly?

**Comment by 3nids** [comment]
@rduivenvoorde 

> Adding to the comment @nyalldawson and said in qgis/QGIS#9530 would be very nice if we create some 'breaks'-factory, not only for raster and vector, but also for Mesh (as that is a third source of break-creators).

They are not tied to vector layers in the described approach.

> I understand that the ui is not part of this proposal? 

Yes it is!!!

> But there are some very strange things going on when using combinations of checkboxes. Recreation of classes etc, on moments you do not expect and or no recreation when you expect. I think that has for example to do with the fact that the calculation of certain breaks is data/cpu intensive (eg calculating the median of part of the whole data). If we could have some 'cache' for that calculations, the 'recalculation' can maybe reused.

I guess that would easily be fixed here.

**Comment by nickbearman** [comment]
Within this, please can I put a request in for Natural Breaks (Jenks) to be the default classification, rather than the current Equal Intervals? (https://github.com/qgis/QGIS/issues/30298)
