### ISSUE TITLE
Improving bad layer handling

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS-Enhancement-Proposals#150]
# QGIS Enhancement: Improved bad layer handling

**Date** 2019/06/20

**Author** @roya0045
**Contact** user at domain dot tld

**maintainer** @roya0045

**Version** QGIS 3.8/3.10

# Summary

Basically I want to add a search function to the bad layer handling to ease some pains. The change that I provided previously is nice when things are in one folder but when the data is split it is still an annoyance.

## My Section

add search function

## Proposed Solution

There are 2 ways that I can go on about this.

1. After all the current checks are done in the apply function. This would find the closest match and remove the row.
2. Another one would be to have an 'autofind' button. This would go through files and search for them in an outward spiral or use the same depth of the file to find the first matching filename. Found files would be highlighted in green and unfound files would be highlighted in red.
    File in green would be added when apply is hit and files in red would be discarded if the user doesn't change them

### Example(s)

(optional)

### Affected Files

QgsBadLayerHandler

## Performance Implications

Might be slow depending on the search depth and the limitation on the search depth.

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

**(required)**

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by roya0045** [comment]
@elpaso @nirvn since you reviewed my PR that touched this, your feedback would be appreciated. Mostly about which approach is better.

**Comment by roya0045** [comment]
Implemented.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
