### ISSUE TITLE
Stored filter expressions on attribute table

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS-Enhancement-Proposals#152]
# QGIS Enhancement: Store filter expressions on attributetable 

**Date** 2019/07/31

**Author** David Signer @signedav

**Contact** david at opengis dot ch

**maintainer** @signedav

**Version** QGIS 3.10

# Summary

In the attribute table the entries can be filtered. 

The idea is to have the possiblity to **store** the expressions used for filtering, **name them**, and finally **have them available in a submenu** of the filter section of the attribute table.

### Stored expressions in the attribute table

![filter_qep](https://user-images.githubusercontent.com/28384354/62208130-3d836b80-b396-11e9-9c5a-b53fa58a4af2.png)

"Save" or "Save As" button next to the "Apply" button.

The submenu could be under a section called "Stored Filter (Expression)".
```
-- Show Edited and New Features
-- Field Filter
   |-- fid
   |-- name
   |-- uuid
-- Advanced Filter (Expression)
-- Stored Filter (Expression)
   |-- my_stored_filter 1
   |-- another stored_filter 2
```

Or it would be slimmer, when it's directly in the "Advanced Filter (Expression)" section. But this could lead the user to think, that "Advanced Filter (Expression)" is only a menu section and not a functionality.
```
-- Advanced Filter (Expression)
   |-- my_stored_filter 1
   |-- another stored_filter 2
```

If the user does not define a name, it appends the expression text itself to the list.
```
-- Stored Filter (Expression)
   |-- my_stored_filter 1
   |-- another stored_filter 2
   |-- "id" > 8 
```

### API
Furthermore an API that provides the possiblity to load and read stored expressions or lists of them:

Functions like e.g. for adding a single expression:
```
/**
* Adds a expression to the stored expressions
*
*  \param name       optional name of the expression
*  \param expression the expression content 
*  \param tag        some content, maybe scope where to be shown
*/
QgsVectorLayer::addStoredExpression( const QString &name, const QString &expression, const QString &tag )
```
Or for adding a list of expressions:
```
QgsVectorLayer::addStoredExpressions( QList(< QPair< QString, QString > > namedexpressions, const QString &tag )
```
Or for reading:
```
QgsVectorLayer::getStoredExpressions( const QString &tag )
```
(returning a list of tuples/pairs `QList(< QPair< QString, QString > >` or maybe in another format)

Reading and writing will be covered with **unit tests**.

### Other places where the filters can be used

As a future opportunity this stored expressions could be available at other places.

- Field Calculator
- Conditional Format rules
- etc.

### Edit in properties
Or there could be the possibility to edit the stored expressions in the layer properties.

### Removing stored expressions
Function to remove them (probably already in the basic implementation)

## Backwards Compatibility

New feature.

## Votes

(required)

**Comment by elpaso** [comment]
Where do you want to store them? In the settings?
Are the expression linked to a particular layer?
Do you plan to check if the expression makes sense for the current layer (i.e. check for fields and validate it before showing it to the user)?

**Comment by signedav** [comment]
Thanks for commenting.

> Where do you want to store them? In the settings?

The layer settings. But not fixed yet.

> Are the expression linked to a particular layer?

Yes. I think most expressions are written for the current layer. Or do disagree?

> Do you plan to check if the expression makes sense for the current layer (i.e. check for fields and validate it before showing it to the user)?

Maybe this can be an additional thing. Fields would make sense of course. Regarding other things I'm not sure yet. In the end the user stores them where he creates them. So they should be fine.

**Comment by nyalldawson** [comment]
> QgsVectorLayer::addStoredExpression( const QString &name, const QString &expression, const QString &tag )

Instead of putting this directly inside QgsVectorLayer, have you considered adding a new manager class, e.g. "QgsFilterManager" (or maybe "QgsFilterSelectionManager" - we could add stored selection sets in their too) and just attaching a getter to QgsVectorLayer, e.g.

    QgsFilterSelectionManager* QgsVectorLayer::filterSelectionManager()

I think it'd be cleaner, vs adding lots of members to the already cluttered QgsVectorLayer API.

**Comment by signedav** [comment]
Sounds good @nyalldawson

**Comment by signedav** [comment]
@nyalldawson I'm not (yet) convinced with your name idea. While this manager should probably be able to handle all kind of expressions in future, like for example expressions used for default values as well. And they have nothing to do with Filters.

So I prefer a name like `QgsStoredExpressionManager`. But this, of course, suits not the selection sets...
 
`QgsStored...Manager` - I don't have an idea at the moment.

**Comment by nyalldawson** [comment]
I guess you could have:
```
class QgsStoredExpressionManager;

class QgsVectorLayer
{
  public:

    QgsStoredExpressionManager& storedFilterManager();

    QgsStoredExpressionManager& defaultValueManager();
}
```

And just keep the QgsStoredExpressionManager API totally generic.
