### ISSUE TITLE
Extending possibilities of new RASTER SURFACE VOLUME native C++ Algorithm

### ISSUE THREAD

**Issue by Zatooka** [qgis/QGIS-Enhancement-Proposals#153]
# QGIS Enhancement: Extending possibilities of new RASTER SURFACE VOLUME native C++ Algorithm

**Date** 2019/08/03

**Author** Zatooka (@Zatooka)

**Contact** location@scarlet.be

**maintainer** @user

**Version** QGIS 3.8 and higher

# Summary

**This new native algorith only propose a basic BASE LEVEL.
Regarding this algorithim is supposed to replace the outdated SAGA raster volume, it makes sense to upgrade it with new feactures to cover higher needs**

## My Section

(optional) Insert custom sections wherever needed

## Proposed Solution

1. Include the possibilities to use a  raster or a 3D shapefile file as BASE LEVEL for the volume calculation;
2. Allow the superposition of a "Coverage layer" (with the same philosophy as in the ATLAS generation within PRINT LAYOUT) to calculate subvolumes within the BASE LEVEL area used in 1;

(required)

### Example(s)

(optional)

### Affected Files

(required if applicable)

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

**(required)**

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by kikislater** [comment]
r.volume is a grass module not saga ...
It's not outdated, usage are different

**Comment by Zatooka** [comment]
Apologizes for fhe confusion.
This optimization is indeed meant for SAGA RASTER VOLUME.
I have updated it in the text now.

Thank you for the quick recation.

Cheers

**Comment by gioman** [comment]
@Zatooka also I think for this was enough a feature request on the tracker, a QEP is a different beast.

**Comment by Zatooka** [comment]
> 
> 
> @Zatooka also I think for this was enough a feature request on the tracker, a QEP is a different beast.

@gioman Noted. 
How do I need to proceed?
It is my first time.
Via Github? Other?

Thank you in advance.

**Comment by luipir** [comment]
@Zatooka open an issue tagged as feature request... there are many examples. Be inspired from the best documented.
https://github.com/qgis/QGIS/issues?q=is%3Aissue+is%3Aopen+label%3A%22Feature+Request%22

**Comment by gioman** [comment]
> open an issue tagged as feature request.

@Zatooka correct, just file a ticket in the tracker tagged as" feature request".
