### ISSUE TITLE
is it possible to refresh the specific area of map in QgsMapCanvas?

### ISSUE THREAD

**Issue by xee425** [qgis/QGIS-Enhancement-Proposals#154]
i am developing a map navigation application, using QGis (2.0.1) and Qt C++,while moving the map on mapCanvas, i am having a problem on mapCanvas->refresh() call, when i call it the map ( raster map ) contract/expand a bit. is there any way to optimize the maprefresh() call? or just refresh the region of map which is not visible?

**Comment by luipir** [comment]
any issue should be open here: https://github.com/qgis/QGIS/issues btw are you really using qgis 2.0.1?

**Comment by luipir** [comment]
thsi repo is to create Enhancement proposal to QGIS that have to follow the template and process as specified in https://github.com/qgis/QGIS-Enhancement-Proposals/blob/master/README.md
