### ISSUE TITLE
Allow to make layer tree nodes (layers and groups) invisible/omitted/secret

### ISSUE THREAD

**Issue by gacarrillor** [qgis/QGIS-Enhancement-Proposals#155]
# QGIS Enhancement: Make layer tree nodes (layers and groups) invisible/omitted/secret 

**Date** 2019/08/24

**Author** Germán Carrillo (@gacarrillor)

**Contact** gcarrillo at linuxmail dot org

**maintainer** @gacarrillor

**Version** QGIS >= 3.10

# Summary

I'd like to port my "Invisible Layers and Groups" plugin (see [here](https://github.com/gacarrillor/InvisibleLayersAndGroups/#invisible-layers-and-groups)) into QGIS Core. It makes it possible to get rid of static layers like basemaps or read-only layers from the Layers panel, but still be able to access to them in QGIS (e.g. you would still see them on QGIS Canvas if they are spatial; relations to those layers won't get lost, etc.).

## What is the use case?

 + Make the Layers panel more readable, specially for projects with large number of layers/groups.
 + Have this configuration in the QGIS project (custom property for layer tree nodes) and allow other applications relying on a QGIS project (think about Lizmap or other mobile apps) to access such configuration centralized where it should be.

## Proposed Solution

**Core:**
Use the Qt's `setRowHidden( index.row(), index.parent(), hidden )` method for layer tree nodes.

Create a custom property on-demand for selected layer tree nodes (layers and groups) that stores the hidden/omitted/secret status for each node. As soon as the custom property is created or modified, we also update its status in the Layers panel using `setRowHidden()`. That is, we get rid of it or bring it again to the Layers panel, according to user actions.

`QgsProject.instance().readProject()` SIGNAL will trigger an update on layer tree nodes status.

**Gui:**
Add two additional menu entries into the "eye" button located on top of the Layers panel:

![image](https://user-images.githubusercontent.com/652785/63639813-db6e0b80-c6a0-11e9-8b08-f7b9e0adcfc0.png)

Menu entries could be `Omit selected layers from Layers panel` and `Make omitted layers visible`, or something like that.

### Example

For reference, this is how the current plugin works:
![Demo GIF](https://user-images.githubusercontent.com/652785/57670833-a26cc800-75d6-11e9-846b-16cadf28aeda.gif)

### Affected Files

 + src/app/qgsmapthemes.cpp
 + src/app/qgisapp.cpp
 + src/ui/qgisapp.ui
 + images/images.qrc

Optionally (if we make it available from `QgisInterface`):

 + src/app/qgisappinterface.cpp
 + src/gui/qgisinterface.cpp

## Performance Implications

None that I'm aware of.

## Further Considerations/Improvements

I've already discussed this functionality with @wonder-sk, but we still looking for proper names for the layer tree node status: is the node made hidden? Is it made secret? Is it omitted? :arrow_right:  Suggestions are welcomed for the wording!

## Backwards Compatibility

Tree nodes from prior projects won't have such custom property, and that's not a problem. We will handle that case for sure. 

## Votes

(required)

**Comment by nyalldawson** [comment]
I like the functionality, but have concerns over the approach described. The correct way to do this would be to make a QSortFilterProxyModel subclass which is responsible for dynamically hiding layer tree nodes based on this property.

**Comment by NathanW2** [comment]
Could I understand the use case on when you would want this? Not against
the idea just worried users will hide stuff and then forget and wonder why
layers are shown but not in the list

**Comment by nyalldawson** [comment]
I'd also propose that we don't expose this option in the layer tree itself, but rather in the project properties, data source tab, where a lot of similar options exist:
![image](https://user-images.githubusercontent.com/1829991/63643771-c08cad00-c71b-11e9-9946-fe1a5ea35f64.png)

**Comment by bstroebl** [comment]
I like the idea but hiding the layers should hide them in processing and snap settings (and maybe other places), too. Especially in processing I hate to scroll through a long list of layers where many are contained in background maps only. Furthermore it might irritate users to see layers in snap settings/proccessing that are not contained (or seem to not be contained) in the layer panel.

**Comment by gacarrillor** [comment]
Thank you all for the comments.

I'll have a look at the QSortFilterProxyModel.

> Could I understand the use case on when you would want this? Not against the idea just worried users will hide stuff and then forget and wonder why layers are shown but not in the list

@NathanW2 do you think we should indicate somewhere/somehow that the Layers panel is hiding some contents?


> I'd also propose that we don't expose this option in the layer tree itself, but rather in the project properties, data source tab, where a lot of similar options exist:
> ![image](https://user-images.githubusercontent.com/1829991/63643771-c08cad00-c71b-11e9-9946-fe1a5ea35f64.png)

@wonder-sk also told me about this dialog. This proposal also includes hiding groups from the Layers panel. The panel you mention does not have checkboxes for groups, should we add them for the goal of this QEP?

> I like the idea but hiding the layers should hide them in processing and snap settings (and maybe other places), too. Especially in processing I hate to scroll through a long list of layers where many are contained in background maps only. Furthermore it might irritate users to see layers in snap settings/proccessing that are not contained (or seem to not be contained) in the layer panel.

This makes a lot of sense for me as well. If everybody agrees, we can add this to the proposal.

**Comment by 3nids** [comment]
If this becomes a property of the layer and not a property of the tree node, can you explain:
* how are you going to hide it in the layer tree?
* how you avoid it to be listed in processing or in other places? Like any QgsMapLayerComboBox.

While this sounds like the right approach, it does sound like some work too.

**Comment by 3nids** [comment]
> I like the idea but hiding the layers should hide them in processing and snap settings (and maybe other places), too.

DXF export, etc.
that's not clear to me.

Mainly, plugins and QgsMapLayerComboBox rely on QgsProject.instance().mapLayers() to list the layers. What the expected behavior here?

in `QgsProject`, modifiy the method to: `QMap<QString, QgsMapLayer *> mapLayers( bool validOnly = false, bool removeHidden = ??? )`could be a solution. `True` by default?

I am not sure about real use case, and I cannot say if one wants to see the layer shown in DXF export or processing or snapping. I guess that's very up to the specificity of each project.

**Comment by andreasneumann** [comment]
Interesting proposal.

How would QGIS server handle such invisible layers? How would GetMap and GetPrint handle such layers? What about GetProjectSettings? I guess it would be important that this information would be available in the GetProjectSettings output.

**Comment by andreasneumann** [comment]
Also, I have quite some concerns about stability - given the many, many bugs we had with embedded layers and groups, and also alternative drawing order (both of these were broken multiple times in the past), we should be extra careful with such changes that mess around with layer visibility and layer tree manipulations. We'd need some really good unit tests.

**Comment by Jean-Roc** [comment]
@3nids one usecase we have would be to use relational values in a form without cluttering the table of content with each new table used

**Comment by gacarrillor** [comment]
@andreasneumann:

> How would QGIS server handle such invisible layers? How would GetMap and GetPrint handle such layers? What about GetProjectSettings? I guess it would be important that this information would be available in the GetProjectSettings output.

The main idea is that client-side software can make use of this "layer-hidden" setting. QField is already using it (so far, via Plugin), Lizmap already has the setting in its own configuration dialog, and I hope Input could eventually use it.

Regarding the server, it deserves some discussion (I'd contact @elpaso internally first). One option is to keep things simple and let the user choose in `Project Properties-->QGIS Server` whether a hidden layer should be served or not. So, I'd propose that hidden layers are listed in the `Project Properties-->QGIS Server` GUI to configure what to serve. 

> Also, I have quite some concerns about stability - given the many, many bugs we had with embedded layers and groups, and also alternative drawing order (both of these were broken multiple times in the past), we should be extra careful with such changes that mess around with layer visibility and layer tree manipulations. We'd need some really good unit tests.

Thanks for raising this, definitely worth to be careful with that scenario.

> And how are the map themes interacting with the invisible layers? Would they also store references to invisible layers?

I was going to answer "yes!", but then I see map themes are limited in scope (see https://github.com/qgis/QGIS/issues/26564, https://github.com/qgis/QGIS/issues/32265 and https://github.com/qgis/QGIS/issues/33080) and that the "layer-hidden" setting would be more a project setting (configured in Project Properties UI), which are also not supported by map themes (e.g., read-only setting), and then my answer is: probably not (unless there is a nice use case, and it'd be as follow-up work).

**Comment by 3nids** [comment]
After some intense discussions on the topic with @m-kuhn and @gacarrillor, we would propose not to follow the layer approach for the following reasons:
- hiding layers will be difficult to do at the layer level only, it makes more sense to allow working at the group level (a layer-tree group), UX is way better
- allowing to mix the hiding status at both layers and groups will make code way complex for what it is (facing the same issues we had for layer/group map visibility toggling)

So, API wise, the idea is add a new custom property in the layer tree groups to hide them.
UX wise, you will be able to hide a group from the legend in its context menu.
In the legend toolbar, under the visibility menu, there will be a new toggle "show/hide hidden groups".

These layers will be invisible from the legend but not from the map, they will follow their visibility status. Using hide all/show all will work as currently by affecting all the layer, independently from the legend-hidden status.
This will also be map-theme agnostic.

Regarding the server, I think it should follow the same behavior: hide from the layer tree, show in the map.

A followup proposal (not included here), would be to offer a new constructor to the `QgsMapLayerComboBox`. Instead of giving a `QgsProject`, you would feed it with `QgsLayerTreeSource`. This will allow to optionnaly hide the layers from hidden groups, and also to list the layers according to the legend.

Please raise your voices -- or you keyboards, just send a picture then -- if you have concerns with this approach.

**Comment by nyalldawson** [comment]
I'm fine with that approach. My use case is hiding non spatial layers anyway (ie tables used only as "supporting" other layers via relations, joins, etc).

Can you confirm you'll be doing this via a proxy model and not some other approach?

**Comment by 3nids** [comment]
> Can you confirm you'll be doing this via a proxy model and not some other approach

Yes, the idea is to use a proxy model in the legend in place of the current model. It will be a very basic one, just filtering out the groups having the hidden status and depending on the toggle.
This class will be in app.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
