### ISSUE TITLE
Add label dimensions or wrapping to Label Properties

### ISSUE THREAD

**Issue by snow-raven** [qgis/QGIS-Enhancement-Proposals#156]
# QGIS Enhancement: Label Properties - Wrap Lines to
**Date** YYYY/MM/DD

**Author** FirstName SurName (@user)

**Contact** user at domain dot tld

**maintainer** @user

**Version** QGIS X.X

# Summary

Would like to be able to manually change the dimensions of labels that have been placed using the new tools on the Label Toolbar. I'd envisioned changing height & width like a text box in many programs, but it might be more easily achieved by adding the "Wrap lines to" character selection to the Label Properties.

## Proposed Solution

Add "Wrap lines to" to the "Label Properties" pop-up window.

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

**(required)**

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by gioman** [comment]
@snow-raven this does not seems a QEP to me, but rather a simple feature request. Am I wrong?

**Comment by snow-raven** [comment]
Yes, sorry. Didn’t realize the difference.
