### ISSUE TITLE
Add support for travelling sales routing, Z-level and turn restrictions

### ISSUE THREAD

**Issue by paulwittle** [qgis/QGIS-Enhancement-Proposals#159]
# QGIS Enhancement: Supporting travelling sales routing, Z-level and turn restrictions

**Date** 2019/10/17

**Author** Paul Wittle (@paulwittle)

**Contact** paul dot wittle at dorsetcouncil dot gov dot uk

**maintainer** To be confirmed

**Version** To be confirmed

# Summary

The default routing tools in the processing toolbox can use a local road network and account for one-way streets however I can't see any settings which would allow the tools to take account of turn restrictions (banned turns) or Z-level attributes. 

Without these key pieces of information the tools are unable to provide accurate routing as they are vital to correct calculation. To give a UK specific example; if you are using Ordnance Survey's Highways network then some bridge links are split with the upper level links have a Z value of 1 whilst the lower links have a value of 0. The default tools permit routing to effectively 'jump off' the bridge onto the lower section and vice versa. 

It is much the same for the banned turns although creating a fix for these may be technically more complex. 

It would also be useful to look at whether or not travelling sales person routing could be added as default. To date I have written my own processing scripts which allow routing with way-points so perhaps that might be a starting point.

I would like to get involved in trying to add support for these functions as I think they will provide a significant boost to the default functionality and provide a good level of support before requiring third party options such as paid for routing software or the use of API keys (which may also incur a cost).

## Proposed Solution

Given that I am new to the group and need to get up to speed on development principals / scripting languages; I would like to propose that I organise a coding sprint or session of some sort where we can discuss / develop options and in effect kick start development.

I will continue to develop some options using my own processing scripts and they can be used as a basis for discussion however I think a more collaborative approach may be required to find a good quality solution. 

For turn restrictions I'm wondering whether that is best done by modifying the routing tree calculations (probably the right method but complex) or by the development of a tool which modifies the network itself. 

The later option is probably wrong on every level but it might be fairly simple to achieve by adding fake links and perhaps overriding the link distance / speed settings. I will work on explaining that better prior to any code sprint if that is thought to be a good route forward. 

### Example(s)

To be added later

## Affected Files

To be confirmed

## Performance Implications

Unknown

## Further Considerations/Improvements

Would also like to investigate the speed issues; my processing scripts currently clip the network prior to running routing as otherwise it takes over an hour for any process to run. This is because the routing tree calculations appear to work out the whole network rather than doing any form of base iteration to work out how much of the network is required. 

Additionally I would like to investigate why the routing functions are so hard to stop. We have had general issues where QGIS starts a task and it is difficult or perhaps even impossible to stop the tasks from QGIS or perhaps even via the Windows task manager. The organisation I work for think this should be resolved as part of this work if possible. 

## Backwards Compatibility

Unknown

## Issue Tracking ID(s)

Unknown

## Votes

No votes yet

**Comment by saberraz** [comment]
Hi @paulwittle thanks for your proposal.

This is more like a feature request. QEP is for changes like: adds new API, breaks current APIs, adds a new data provider, significant UI/UX changes.

For routing, you can use a proper spatial database (PostGIS + pgRouting) which already supports your requirement.

For native QGIS support, @wonder-sk has done a similar job a while back and probably can shed some light.

**Comment by timlinux** [comment]
@paulwittle to add to @saberraz's comments - improvements to the routing logic in QGIS are always welcome but ideally your QEP should provide a list of detailed API level changes / additions so that others may comment on your design approach before you embark on actual coding work.

Regards

Tim

**Comment by paulwittle** [comment]
@timlinux and @saberraz - Sorry if I've put it in the wrong place; ironically I was going to put it as a feature request but there was some text about using one of these if you think it is important so I used QEP instead. I'm happy to switch it over to a feature request if that is better?

I could create a feature request, comment to link this to it then close the QEP?

**Comment by paulwittle** [comment]
Please see https://github.com/qgis/QGIS/issues/32295 

Moved to feature request and closed.
