### ISSUE TITLE
Ability to copy/paste vertices to "snap" polygons together, and ability to move vertices shared by two polygons together at once.

### ISSUE THREAD

**Issue by bbct** [qgis/QGIS-Enhancement-Proposals#160]
# QGIS Enhancement: Ability to move shared vertices together, and ability to Copy/Paste a set of vertices in a given polygon to share a border with the source polygon

**Date** 2019/12/7

**Author** Brian Biales (@bbct)

**Contact** 

**maintainer**

**Version** QGIS 3.x

# Summary
**(required)**
I have polygons adjacent to each other.  I would like an easy way to 
1) move shared vertices and affect both polygons at the same time.  
2) use a copy/paste of vertices to manually "snap" via paste one polygon to share a border set of vertices with the original polygon.

## My Section
(optional) Insert custom sections wherever needed

## Proposed Solution
OPTION 1: Allow me to select two polygons at once when using the Vertex Tool.  It would then ONLY let me choose vertices shared by both (the edge vertices would be the more complicated ones to move, as they are not attached to a shared vertex).  When I pick a vertex shared by both, then moving that vertex will move it in BOTH polygons at once, keeping them in sync.  

OPTION 2: This option would help "snap" one polygon to another that is not exactly matched yet. 
Select the vertices from one polygon that you want the other polygon to share, and create the ability to "copy" this section of vertices.  Then the user can select the second polygon, select the section/vertices of the adjacent polygon that don't quite match that you want to match, then paste, the copied vertices, replacing the selected vertices with the copied ones.  This would make their edges match again, snapping the second polygon to the other.   

Together, the first option would make it easy to edit shared edges of polygons together, and the second option would make it easy to add a new simple polygon, and then "paste" the vertices from the existing polygon into the new one, "snapping" it into place.

These also require no advanced, automated algorithms to guess how to snap two polygons together.  The vertex selection is manual.  The Vertex tool already provides the ability to select a chain of vertices, one needs only to implement a "copy" feature (perhaps a right click context menu, or use the currently disabled "Copy" in the Edit drop down menu, or Ctrl-C to copy them.  Then let the user select the vertices in the second polygon to be replaced, again this feature already exists in the Vertex Tool, and implement a Paste option, again through a right click context menu, or currently disabled Paste in the Edit drop down, or support Ctrl-V.

### Example(s)

(optional)

### Affected Files

(required if applicable)

## Performance Implications
Should have no performance implications
**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility
There would be no backward compatibility issues - this is simply a new UI feature to help perform actions already supported.
**(required)**

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by haubourg** [comment]
Hi,
for option 1, are you aware that the topological editing option does this?

**Comment by bbct** [comment]
I was not, I will look into it, thanks.  I'm new to QGIS, and did not find that yet!

**Comment by bbct** [comment]
Upon further investigation, the topological editing option and snapping features are what I was looking for, Certainly for Option 1, and I'm fairly confident Option 2 as well (I need to try it out more first...)

**Comment by borysiasty** [comment]
For the Option 2, see "Enable tracing" and "Avoid intersections" functions.

**Comment by gioman** [comment]
@bbct closing?

**Comment by alexbruy** [comment]
Is this really a QEP? To me looks like feature request and should be closed (and if necessary a new ticket should be opened in bugtracker)

**Comment by gioman** [comment]
> Is this really a QEP? To me looks like feature request and should be closed (and if necessary a new ticket should be opened in bugtracker)

agree.

**Comment by bbct** [comment]
All, yes, closing is the right thing - deleting would be fine too :-)  I mistakenly thought this was where to post enhancement requests, but I see this is where enhancement proposals go...  Newbie mistake. 
The features I was looking for already exist in different form, I had yet to find them, and next time I have an enhancement suggestion it will be posted in the right place.  Thanks.
