### ISSUE TITLE
Client support for WMS-T

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Enhancement-Proposals#161]
# QGIS Enhancement: Title

**Date** 2020/01/04

**Author** Tim Sutton (@timlinux)

**Contact** tim@kartoza.com

**maintainer** @samweli

**Version** QGIS 3.14+

# Summary

We already have WMS-T support for QGIS Server (see https://github.com/qgis/QGIS-Enhancement-Proposals/issues/110). This QEP relates to adding WMS-T client related functionality in QGIS desktop.

Our work is funded by a client (and we are under contract to Mapgears) and is specific in its scope to the scoping document attached.

WMS-T support is important for organisations like meteorological agencies that work heavily with time sliced data.

There were broader possibilities for time related data management (beyond WMS-T) that were considered for this work piece that were ultimately not funded by our client. In particular 4 areas that we would like to work on - please contact me if you have funding to support these:

1. Vector layer time filtering support (similar to how time manager does it)
2. Directories containing file stamped raster files. The files matching the active time slice will be used.
3. Hierarchical formats  such as NetCDF which may contain temporal data.
4. Printing atlas or reports using time series.

Note also that we only considered the time dimension in WMS-T - other dimensions such as height are not proposed at this time.

@nyalldawson will be contracted to provide oversight for our work and ensure that everything gets merged smoothly.

## Proposed Solution

A detailed breakdown of the proposed changes / improvements are provided in the attached PDF document.

Detailed scoping document (redacted to remove some specific client details):

[WMS-T User Stories _ Use Cases _ Requirements - Version 3 - Public QEP Version.pdf](https://github.com/qgis/QGIS-Enhancement-Proposals/files/4026012/WMS-T.User.Stories._.Use.Cases._.Requirements.-.Version.3.-.Public.QEP.Version.pdf)

### Affected Files

See context diagram in scoping doc

## Performance Implications

None expected

## Further Considerations/Improvements

For the project wide time slicing, we probably need some wider discussion as there are other elements to QGIS that might benefit from this. 

CC @nyalldawson @saberraz 

## Backwards Compatibility

Only QGIS 3.12 or later will be supported

## Issue Tracking ID(s)

https://github.com/qgis/QGIS/pull/33539
https://github.com/qgis/QGIS/pull/33321 (crash relating to refreshing WMS metadata)
https://github.com/qgis/QGIS/pull/33467
More coming...

## Votes

(required)

**Comment by PeterPetrik** [comment]
related to https://github.com/qgis/QGIS-Enhancement-Proposals/issues/128

**Comment by PeterPetrik** [comment]
I think it needs to be QGIS 3.14+, not sure if you can manage to implement it in 2 weeks time?

**Comment by timlinux** [comment]
Update: We have had a little discussion with @PeterPetrik who is suggesting we re-use or use similar approach for data input handling to that used in mesh layers:

![Screenshot from 2020-01-07 08-45-19](https://user-images.githubusercontent.com/178003/71881450-396c2e80-312a-11ea-8dc5-26ba6ef0b94b.png)

In the detailed properties it also includes a calendar widget in the time picker.

![Screenshot from 2020-01-07 08-47-56](https://user-images.githubusercontent.com/178003/71881563-71737180-312a-11ea-9b63-afab7524e789.png)

**Comment by timlinux** [comment]
Thanks @PeterPetrik I corrected the version target.

**Comment by elpaso** [comment]
Nice! 
Just to be sure you are aware of that, WFS3/OAPIF time queries support is also implemented in QGIS Server since: https://github.com/qgis/QGIS/pull/32322
