### ISSUE TITLE
Magnetic model handling in QGIS

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#165]
# QGIS Enhancement: Magnetic model handling in QGIS

**Date** 2020/02/21

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall dot dawson at gmail dot com

**maintainer** @nyalldawson

**Version** QGIS 3.x?

# Summary

QGIS currently lacks any capabilities for handling magnetic model based calculations, such as calculation of magnetic north at any location.

This is limiting in numerous ways:

- When a GPS device does not include magnetic deviation in the NMEA messages (many don't), it's not possible to adjust the reported bearings to account for magnetic deviation
- There is no capability to orient north arrows to magnetic north -- users instead must use some external service to determine the deviation and manually adjust north arrows to suit
- We cannot expose the equivalent of ArcGIS' Magnetic Calculator toolkit (see https://desktop.arcgis.com/en/arcmap/10.3/tools/production-mapping-toolbox/magnetic-calculator.htm), which allows calculation of magnetic field properties corresponding to a set of input point locations

## Proposed Solution

The geographiclib library is a stable, widely available library which exposes the means to calculate the required magnetic field properties. It is proposed to make geographiclib a dependency of QGIS.
(This was previously done in https://github.com/qgis/QGIS/pull/8792/commits/0ff7310d60fc88222ebe06f6e06b2a36375025dc but later reverted, as the required methods were also exposed via the existing proj dependency).

geographiclib's magnetic model classes (see https://geographiclib.sourceforge.io/html/classGeographicLib_1_1MagneticModel.html) will be mirrored in the QGIS c++ and Python API, providing QGIS core and plugin code a stable API for accessing this functionality.

By default, the most current World Magnetic Model coefficients file will be installed alongside QGIS, and QGIS will default to using this for magnetic field calculations. A new setting in the global QGIS options will be added to allow users the option of using a different magnetic model, by setting a path to an alternative, manually downloaded model file (see https://geographiclib.sourceforge.io/html/magnetic.html for further details). 

In addition, this functionality will be made exposed to QGIS users via:

1. A new processing algorithm for calculating the magnetic field at locations from a point layer

2. A new option to automatically orient a layout north arrow towards magnetic north

3. A new option in the GPS information panel to control whether bearings reported via the GPS device need to be adjusted to account for magnetic deviation at the GPS location

## Votes

(required)

**Comment by haubourg** [comment]
A huge positive vote for me

**Comment by pcav** [comment]
+1, pretty important in some cases, and opes up many possibilities, also for plugins.

**Comment by PeterPetrik** [comment]
+1 looks good

**Comment by timlinux** [comment]
We could pull magnetic north from a service like this:

https://www.ngdc.noaa.gov/geomag/calculators/help/declinationHelp.html

Is the proposal just to calculate the offset from a service rather than manually add it as per:

https://github.com/qgis/QGIS/pull/3618

**Comment by nyalldawson** [comment]
@timlinux 

It's basically the same, except that if we follow the described approach we aren't reliant on external services or an internet connection.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
