### ISSUE TITLE
QGIS without GIS

### ISSUE THREAD

**Issue by pcav** [qgis/QGIS-Enhancement-Proposals#166]
# QGIS Enhancement: Title

**Date** 2020/02/22

**Author** Paolo Cavallini (@pcav )

**Contact** cavallini@faunalia.it

**maintainer** @pcav 

**Version** QGIS X314

# Summary
QGIS is good, also for non spatial data, at doing things like:
- forms
- attribute table
- conditional formatting in the attribute table
- loading views from PostgreSQL etc
- dataplotly
- layout/reports
I didn't find any good software to replace QGIS for these tasks.
For non GIS users the full interface of QGIS, with a map canvas and tons of buttons, is confusing and even intimidating.

## Proposed Solution
Add an option (e.g. `--nogis`) to start QGIS with a simplified interface:
* no map canvas
* no GIS commands
Alternatively, the qgis package could be split in two, one basic and one that adds the canvas and the GIS commands.

### Example(s)
An early attempt by @gustry:
https://github.com/Gustry/qgis_standalone_application

## Backwards Compatibility
Only for newer versions.

## Votes

(required)

**Comment by pcav** [comment]
On a second thought, this might be done simply with an user profile.

**Comment by ghtmtt** [comment]
what about customizing a UI without the map and all the GIS buttons and load with a profile and load it with a `--nogis`` flag.

**Comment by pcav** [comment]
I'm experimenting with the built-in customization, it may be enough.

**Comment by cbertelli** [comment]
There are several use cases for an extended use of alphanumeric data and a limited usage of geometric data. Sometimes specialists are requested to access geometric data to work on the thematic issues. Under this point of view, many things could be done to enhance the user experience and data safety. It's a frequent requirement in fields like history, demography and globally in social sciences. Maybe a modal interface that shows only specific icons and menu items useful for data management could be useful for everyone.
There is still space for enhancements on alphanumeric data – we still have a "DB Manager" which is not completely integrated and filtering data by attribute is not so easy as it should be. It could be a good opportunity to develop these features with an eye on these use cases and an orderly layout for data. The funny idea that a non-geometric table is a "layer" is at least confusing for users, even if an easy metaphor for GIS developers.

**Comment by nyalldawson** [comment]
I think to do this right you'd need to go further then the interface customisation permits.

I'd imagine something like:

1. Browser view on the left hand side, filtered to remove geo-specific sources like WFS/WMS/etc (and probably not showing GDAL provider based items (i.e. raster files) also) 

2. Map canvas replaced by tabbed views of attribute tables/forms

3. Filtered set of Processing tools, only showing those applicable for db applications (i.e. add a new flag to algorithms to control whether the algorithm is applicable for non-geo applications)

4. Filtered set of plugins, using a new metadata property to indicate db style plugins

5. I think it should also be a new executable (i.e. a new build target), not something based on app, and exposing a limited set of functionality via the iface interface

(In many ways it would be just like the old "browser" application, but with the attribute table/form functionality introduced and an improved interface)

FWIW, I think it's worth exploring.

**Comment by haubourg** [comment]
And, something people may also ask for, a revamped relation properties UI, with graphical relation view and editing. You know, this MS Access thing :)

**Comment by 3nids** [comment]
> Map canvas replaced by tabbed views of attribute tables/forms

=> Map canvas / attribute tables tabs would be nice too in main app!

**Comment by andremano** [comment]
Glad to see that what I am currently trying is not as crazy as I initially thought! I currently have a QGIS profile just to enter alphanumeric data into a Postgres database! It allows me to have drop-down lists of FK and codelist values, have a table or form view etc. At first glance it feels like an overkill, using QGIS just for data entry, but I haven't found any better tool. That said, I think this **_nogis_** profile is an idea worth exploring!!
![33c63698-b9ff-4760-b257-4585d24fd9d9](https://user-images.githubusercontent.com/6665872/75157846-431b1700-5715-11ea-91cf-4ac064076ec0.jpg)

**Comment by ivn951** [comment]
I try to launch my proposal: **QGIStudio Data Manager**, in which it is possible to analyze spatial and non-spatial data, with the peculiarities exposed by @pcav, in modular or autonomous form.

**Comment by Saijin-Naib** [comment]
I see a similar purpose (in different directions) between your QEP and what I'm asking for in this FR.

**Comment by EmilienAlvarez** [comment]
I really like the idea of Q without GIS! There's an application I've been thinking about : [Here](https://twitter.com/EmilienAlvarez/status/1268181534261104640).
This is a useful application that only requires the editing and viewing of vector files and their tables of attributes. I would like to allow an association to easily use this application to manage its bike repair projects, but QGis may be a bit scary the first time for a non-geomatician.

**Comment by esnyder-rve** [comment]
I definitely see great value in something like this. I'm currently looking into using QGIS reports to do something that would otherwise be "hacking" a mail merge to maybe get working. For this I would definitely add better python coding stuff (maybe integration with Kite) and data visualization libraries. I would not get rid of the "GIS", but maybe a small map view panel for working with and previewing map data. This could be a beefed up Data Scientist IDE like thing with great visualizations and reports through Atlas.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
