### ISSUE TITLE
Snapping enabled on a configurable scale range

### ISSUE THREAD

**Issue by obrix** [qgis/QGIS-Enhancement-Proposals#167]
# Snapping enabled on a configurable scale range

**Date** 2020/03/04

**Author** Bertrand Rix (@obrix)

**Contact** bertrand.rix@oslandia.com

**maintainer** @obrix

**Version** QGIS 3.12

# Summary

This is a proposed addition of two parameters in the advanced per layer snapping configuration. Those parameters allow the user to enable feature snapping only on a specified map scale range when drawing new features. 

This is useful as with some feature heavy layer, when panning over large area, the index allowing efficient neighbors search might be rebuilt several times which in certain cases is a pretty heavy task that is impacting user experience. Furthermore snapping in those cases might be useless because of the differences between the current map scale and features present in the canvas.

Those two parameters are a way to enable snapping only when the user really need it, it avoid for the user to have to enable/disable snapping constantly when working on huge dataset because of performance reason. 

## Proposed Solution

Add two parameters minScale and maxScale to the per layer advanced snapping parameters.
When current scale of the map is in the [minScale, maxScale] range snapping is enabled. Otherwise it is disabled and thus the index is not recomputed.
Default value for minScale and maxScale is -1.
When minScale is equal to -1 minScale limit is ignored.
When maxScale is equal to -1 maxScale limit is ignored.
When minScale and maxScale are -1 snapping is enabled at any scale.

### Example(s)

![SnappingParameters](https://user-images.githubusercontent.com/19537259/75871017-35981800-5e0c-11ea-9967-b38f8f2714d0.png)

### Affected Files

A branch with an implemented working prototype is available here : https://github.com/obrix/QGIS/tree/snapping_zoomlvl_optim

## Performance Implications

This should improve performance when snapping over large layer harboring many features. The suiting configuration for proper scale limit remains in the hand of the user.

## Backwards Compatibility

Break the compatibility with older project file as the new parameters are serialized and read from it.

## Votes

(required)

**Comment by 3nids** [comment]
If this is per layer configuration, it won't work on simpler configuration?
Wouldn't it be better to set this as a global setting of the snapping config rather than per layer?
Ot turned differently, why is it interesting to set it per layer?

**Comment by nyalldawson** [comment]
I've no strong opinions on the feature itself, but just one small request: could you avoid "-1" as an alias for "not set"? It makes sense to a programmer, but to anyone else it's a nonsense value 😁

**Comment by obrix** [comment]
@3nids I imagine we can have relevant scales to enable snapping that are different for different layers. For example a line layer for roads and a point layer for cities : we might want to enable snapping on cities from a large scale, while enabling snapping on road on a much smaller scale. Thus the per layer configuration.


@nyalldawson I agree with you, as you can see on the branch my first version had a third parameter which was a checkbox to specifically enable/disable the limits on snapping and no magic value. After discussing this with @troopa81 I removed it. If I keep the implementation without checkbox I can probably find something more explicit for the user in the final version.

**Comment by 3nids** [comment]
>  I imagine we can have relevant scales to enable snapping that are different for different layers. For example a line layer for roads and a point layer for cities : we might want to enable snapping on cities from a large scale, while enabling snapping on road on a much smaller scale. Thus the per layer configuration.

Let's wait for real use-case, no? I think we should provide simpler configuration before trying to answer the most complex cases.
In the same manner, I think we should offer the possibility to have global tolerance settings in the advanced config (instead of per layer).

I would propose to introduce as a global setting and eventually extend it if required by someone.

**Comment by obrix** [comment]
@3nids I was just illustrating. This development comes from real use cases from 2 of our clients that have been bothered by the performances of the index rebuilt coming from specific layers. They do not want to disable snapping on all layers with the same parameters, they just want to optimize out the layers that are giving them issues.

**Comment by 3nids** [comment]
> They do not want to disable snapping on all layers with the same parameters, they just want to optimize out the layers that are giving them issues.

OK, but this just sounds way too complex to me here. 
Let's say you have a project with 30 layers, that's 30 times the config. 
I think this requires at least a global setting and an option to turn it per layer.
This manner this option would also be available for someone not using the advanced snapping config.

**Comment by troopa81** [comment]
@3nids I understand your point. A global configuration for all snapping parameters (including tolerance and this scale range) will be interesting. But this is not the way it's design currently.

My opinion will be to make it consistent with the actual way of configuring (I mean per layer configuration) and maybe add a way of setting this configuration globally later.

**Comment by obrix** [comment]
@3nids The optimization is disabled by default on all layer (-1 here, on something more explicit in the final version). So the configuration is only done when the user specifically needs it on a layer. No configuration needed by default.
I agree though that giving the possibility to the user to configure a global setting may be a good idea.

**Comment by 3nids** [comment]
> @3nids The optimization is disabled by default on all layer (-1 here, or something more explicit in the final version). So the configuration is only done when the user specifically needs it on a layer. No configuration needed by default.
That's the point. If I use this, I want it to be set the same for all layers. Hence the default config.

I think that this (and the tolerance for the future) should be offered as global, even for the advanced configuration, with the option to set it per layer.

**Comment by obrix** [comment]
@3nids Okay make sense that way.

**Comment by obrix** [comment]
I have implemented the requested following changes : 
- A global configuration to be applied by default on all layers
  * A global button to enable/disable scale limit for snapping 
  * Global minScale and maxScale values to be applied for all layers
  * When minScale and maxScale are not specified for a layer, the global values are used. Otherwise the minScale and the maxScale of the layer are used.
- A more explicit "disabled" value for the unused limit :  
  * When minScale or maxScale is set to 0, which is the default value, the limit is considered not set and is not used. It is displayed as NULL to the user.
- Snapping limit on scale is only available in advanced snapping settings

Here is a view of the snapping toolbar with the action to enable/disable snapping limitation and the two values minScale and maxScale

![SnappingToolbar](https://user-images.githubusercontent.com/19537259/76763803-14341600-6794-11ea-83c6-acddddbd42f5.png)

Here is a view of the advanced settings panel with 3 example layers
![advancedSettings](https://user-images.githubusercontent.com/19537259/76763809-15fdd980-6794-11ea-8c06-f60e4fed5404.png)



If everybody agree I will now create a PR to discuss the implementation details if needed.

**Comment by nyalldawson** [comment]
@obrix looking at that screenshot, I think:

- "NULL" is not appropriate terminology here -- it should be "not set" or "no maximum/no minimum".
- it would be preferable to use the existing QgsScaleWidget instead of the spin boxes -- that gives better UI, and allows for setting directly to current canvas scale. 
- I'm not sure about adding these widgets to the toolbar though -- they make the toolbar much longer then it currently is, and I can't see them being used often enough to justify this. Better to put them in the advanced settings dialog only?

**Comment by 3nids** [comment]
> I'm not sure about adding these widgets to the toolbar though -- they make the toolbar much longer then it currently is, and I can't see them being used often enough to justify this. Better to put them in the advanced settings dialog only?
yes, please. Maybe just keeping the toggle in the toolbar but leaving the configuration in the dialog (then the toggle might shown only once the config has been set, otherwise it makes no sense). Or show the 2 comboboxes within a `QgsFloatingWidget`

Regarding the icon, the idea is nice, but I wouldn't repeat the magnet in there. What about having a generic scale dependency icon?

**Comment by obrix** [comment]
@nyalldawson 
* I chose NULL to keep something short, I also tried "NoLimit" but "Not set" seems fine.
* I can look into that, it seems there even is a QgsScaleRangeWidget which might be appropriate.
* I have no strong feelings about keeping them in the toolbar, maybe we can just keep the action button as suggested by @3nids but I think It can get confusing without the parameters by the side of it.

@3nids 
Could you elaborate on why you would not keep the small magnet ? I think this is rather explicit but I am open to others proposals. Is the generic scale dependency icon existing already ?

**Comment by 3nids** [comment]
> QgsScaleRangeWidget which might be appropriate.

you won't be able to use it as a delegate for the table, as it's across two columns (or you need to adapt).

> I have no strong feelings about keeping them in the toolbar, maybe we can just keep the action button as suggested by @3nids but I think It can get confusing without the parameters by the side of it.

just remove it from the toolbar then
or I wonder if it wouldn't make sense to have a menu for all the toggles (intersection, topological and scale dependency). No strong opinion here. I guess the easy way is just not to show it in the toolbar.

> Is the generic scale dependency icon existing already ?

not that I am aware of

> Could you elaborate on why you would not keep the small magnet ? I think this is rather explicit but I am open to others proposals. 

I was thinking something like this, but it's not satisfying when swittching normal/dark mode:

![image](https://user-images.githubusercontent.com/127259/76838879-d3400e00-6834-11ea-959e-96bc3cba6519.png)

**Comment by obrix** [comment]
> you won't be able to use it as a delegate for the table, as it's across two columns (or you need to adapt).

Okay thanks.

> I was thinking something like this, but it's not satisfying when swittching normal/dark mode

I see, to be frank I think the magnet included between the scale values icon is more appropriate to describe the feature. But if more people request the change I will do it.

**Comment by obrix** [comment]
The feature has been implemented as a PR that has been merged [here](https://github.com/qgis/QGIS/pull/35110). Closing.
