### ISSUE TITLE
Adding 322 Public Domain Humanitarian SVG Icons to QGIS instillation package 

### ISSUE THREAD

**Issue by MhdT** [qgis/QGIS-Enhancement-Proposals#168]
# QGIS Enhancement: Adding 322 Public Domain Humanitarian SVG Icons to QGIS instillation package 

**Date** 2020/03/18

**Author** Mhd Tamer @MhdT

**Contact** C4ITServices@gmail.com 
**maintainer** @MhdT

**Version** QGIS 

# Summary

Adding Humanitarian SVG Icons to QGIS instillation package.
This icon developed by UNOCHA and released to the public domain
https://www.unocha.org/story/iconography-part-un%E2%80%99s-humanitarian-efforts-ocha-releases-new-humanitarian-icons

## My Section

(optional) Insert custom sections wherever needed

## Proposed Solution

Add the 322 SVG icon to QGIS instillation package.
The QGIS optimized version of this SVG icons (with style parameters ) located 
https://github.com/MhdT/QGIS-Resources/tree/master/UNOCHA%20Humanitarian%20IconsSVG%20v2

## Performance Implications

Read and load 322 small SVG file 

## Backwards Compatibility

Not applicable (for adding resource files)

## Votes

(required)

**Comment by nyalldawson** [comment]
Looks great to me. I had a quick browse through the proposed svg repository and they all look nicely and correctly parameterised. It's a definite +1 from me

**Comment by pcav** [comment]
+1

**Comment by timlinux** [comment]
Huge +1 from me too - we have been using UN-OCHA icons for many years and they are great quality, very useful icons.

**Comment by haubourg** [comment]
Same here ! great move

**Comment by elpaso** [comment]
I'm -0: shouldn't be better to distribute them through the resource sharing plugin?

**Comment by MhdT** [comment]
> I'm -0: shouldn't be better to distribute them through the resource sharing plugin?

I understand your point clearly, but considering that I am targeting humanitarian workers who use GIS tools with minimum knowledge to produce simple maps, so you can say that I am trying to flatten the curve :) (learning curve) or minimizing number of steps required to create a map.
It's worth it finding ways to make QGIS out of the box ready for humanitarian workers.

**Comment by alexbruy** [comment]
-0 from me. We can't include every set of icons to accommodate needs of different type of workers. There are other set of icons with good quality out there which are not part of QGIS installation.

**Comment by nyalldawson** [comment]
> There are other set of icons with good quality out there which are not part of QGIS installation.

I'd argue that we should assess and include these by default too. The default symbol set we currently ship with qgis is really quite limited, yet I'd guess that a large percentage of our users never search beyond this and always just limit their choices to to default selection. Shipping a larger selection by default is highly desirable in my opinion*.

* So long as the symbols are of professional quality, which this set is.

**Comment by haubourg** [comment]
> I'd argue that we should assess and include these by default too. The default symbol set we currently ship with qgis is really quite limited, yet I'd guess that a large percentage of our users never search beyond this and always just limit their choices to to default selection. Shipping a larger selection by default is highly desirable in my opinion*.

I'm with Nyall here. Our default symbol set should be a lot better without using the qgis sharing plugin - which very few users know about.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
