### ISSUE TITLE
Best form view editor, like http://sqlitebrowser.org 

### ISSUE THREAD

**Issue by juanmafont** [qgis/QGIS-Enhancement-Proposals#169]
# QGIS Enhancement: Best form view editor, like http://sqlitebrowser.org

**Date** 2020/03/29

**Author** Juanma Font (@juanmafont)

**Contact** user at domain dot tld

**maintainer** @user

**Version** QGIS 3.X

# Summary
The 'form view' could be improved as the editor of the 'db browser for sqlite' program, this editor allows editing columns with several rows. See: http://sqlitebrowser.org This application also uses the QT libraries
## My Section

(optional) Insert custom sections wherever needed

## Proposed Solution

![Screenshot_2020-03-29_17-10-21](https://user-images.githubusercontent.com/6154911/77852686-44da6d80-71e0-11ea-93ec-ebb6c6538626.png)
(optional)

### Affected Files

(required if applicable)

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

**(required)**

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by pcav** [comment]
I agree that this could and should be improved. Could you please give a list of specific improvements?

**Comment by juanmafont** [comment]
Yes, I saw after send request that multi-row editor is posibled, so
IMHO try clone" DB Browser for sqlite"  form -> Edit database Cell:

   This form is quite intuitive, powerful and simple.

  it has:

 -  Multi row editor (automatic)
 - Manual Selector for different content type into cell to edit ->
(Text,Binary, Image, JSON, XML)
 -  Switch button to 'Automatically adjust the editor mode to the
loade data type'
 - Switch button to 'Pretty print on loading, compact on saving'

   Try 'DB Browser for SQlite' and open a geopackage file with it to
see into action.

  I send a video screen capture to see DB Browser in action while edit
a database.


On 3/29/20, Paolo Cavallini <notifications@github.com> wrote:
> I agree that this could and should be improved. Could you please give a list
> of specific improvements?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/qgis/QGIS-Enhancement-Proposals/issues/169#issuecomment-605652643


-- 
El que no quiere razonar es un fanático; el que no sabe razonar es un
necio; el que no se atreve a razonar es un esclavo.
W.Drummond.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
