### ISSUE TITLE
Dynamic Client Registration

### ISSUE THREAD

**Issue by leedahl** [qgis/QGIS-Enhancement-Proposals#170]
# QGIS Enhancement: Dynamic Client Registration

**Date** 2020/04/19

**Author** Michael Leedahl (@user)

**Contact** michael.leedahl@maxar.com

**maintainer** @user

**Version** QGIS 3.12

# Summary

Implement RFC 7591 for Dynamic Client Registration.
Dynamic Client Registration offers a user to register a QGIS installation on their machine with an authorization server so that they can make authorization request on behalf of an application they wish 
to connect to using OAuth 2.0. Currently, if I am not mistaken, QGIS support OAuth 2.0 to request an access token.  This assumes that the user has a client id and secret in advance in order to request a token.  It would be nice if in the QGIS UI, a user could register their instance of QGIS with an authorization server to retrieve and automatically populate the OAuth 2.0 configure dialog with the registration information obtained through the dynamic client registration response.

## Proposed Solution

I propose to implement dynamic client registration by adding a registration tab to the OAuth 2.0 dialog.  The tab would allow all the fields specified in RFC 7591 and indicate which ones are required.  I further propose to update the documentation in the users guide to explain the fields on the new tab.  The documentation would also explain what dynamic registration is and how to it is used with some example scenarios outlined.  I also propose to modify the code files or add additional files to implement the backend calls to a registration server.  I would accomplish these tasks as part of the Open Geospatial Consortiums Testbed 16 as a participant in the MAP thread for the Data Centric Security task.  There will also be an Engineering Report that covers the use of Dynamic Client Registation.

### Affected Files

qgsauthoauth2edit.cpp
qgsauthoauth2edit.h
qsauthoauth2edit.ui
qgsauthoauth2method.cpp
qgsauthoauth2method.h
qgso2.cpp
qgso2.h

## Performance Implications

The user only needs to register with an authorization server the first time they wish to connect to a specific authorization server.  Once registered, the client id, secret, etc. will be store in the keyring.  The
registration takes a few seconds or less that initial time.  After that, the performance is the same as it currently is for OAuth 2.0.

## Backwards Compatibility

This would be a new feature that doesn't change how the current OAuth 2.0 functionality works.  Existing OAuth 2.0 connections would continue to work they way they have always worked.  This is a step done to assist a user in configuring an OAuth 2.0 connection.

## Votes

(required)

**Comment by haubourg** [comment]
Hi, I have the feeling that a QEP is not really necessary here. You could go directly with a Pull Request, unless your work have heavy impacts, either on the User interface or the API. 
Regards

**Comment by leedahl** [comment]
Okay.  The only impact on the UI would be an additional tab to the auth module.  However there is currently the software statement tab which is covered by the RFC however, that is just one method of registration shown in the RFC.  So I suppose there is the question of adding a new tab with full support and leaving the software statement tab as legacy or replacing the software statement tab with a registration tab.

**Comment by securedimensions** [comment]
Adding an additional tab to implement the RFC by submitting the required information is a good enhancement. This is one approach to mitigate the use of long term credentials in the authorization_code flow. The other option to not rely on long term credentials is to use PKCE with the authorization code.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
