### ISSUE TITLE
Postgres Raster Import

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS-Enhancement-Proposals#174]
# Postgres Raster Import

**Date** 2020/05/12

**Authors** 
- lead & QGIS implementation: Alessandro Pasotti (@elpaso) 
- GDAL implementation: Even Rouault (@rouault)

**Contact** elpaso at itopen dot it

**maintainer** @elpaso

**Version** GDAL 3.2 / QGIS 3.18

# Summary

With the new QGIS data provider native support for Postgres Raster and the new temporal capabilities that have been implemented also for Postgres Raster, this format is ready for a broader usage and integration in the QGIS application.

The only missing functionality is the ability to import a raster layer into an existing Postgres DB.

This proposal will allow to import any QGIS supported raster format into an existing Postgis database with optional tiling and overviews, the functionality will be available from the QGIS browser panel through drag & drop (with an intermediate dialog to allow setting of options) and it will be made available to plugins and further menu actions integration through the `QgsRasterFileWriter` core API.

## Proposed Solution

While a direct implementation into QGIS would have probably been a little quicker, we decided that a GDAL implementation is the right thing to do in order to make the functionality available to the vast software ecosystem using GDAL. 
The QGIS implementation will mainly consist of:

- the integration of the new GDAL functionality
- GUI dialog to set the import options
- QGIS tests
- QGIS documentation

### Affected Files

- GDAL library driver files
-  `QgsRasterFileWriter` 
- QGIS Postgres provider data items

### GDAL PostgisRaster driver enhancements

The existing GDAL PostgisRaster driver is read-only. The planned work will allow whole raster import to be done (CreateCopy() interface, typically used by the `gdal_translate` utility) or read-write scenarios (Create() interface, as exercised by QGIS raster file writer, or `gdalwarp` utility). PostGIS raster tables can potentially store raster objects of different resolution, size or alignment within a same table. To limit implementation complexity, we will restrict creation, and updated, of raster tables to tables with constraints enforcing tiles of same size, resolution and alignment, or untiled content. Overview creation will also be possible.

## Performance Implications

None

## Further Considerations/Improvements

None

## Backwards Compatibility

None

## Issue Tracking ID(s)

None

## Votes

(required)

**Comment by jgrocha** [comment]
@elpaso I've developed a [raster to postgis](https://gitlab.com/geomaster/raster2postgis) import, as a plugin, and it works nice. It supports in-db rasters or out-of-db rasters. If we want out-of-db rasters, we need something like I did in the plugin: upload the rasters, store it on the backend filesystem and them import it on the db. In my setup, I'm able to import rasters easily.

I'm quite motivated to help in this QEP. Thanks for pushing it.

Unfortunately, the plugin was never approved (no comments!), but I have some QGIS users using it on a daily basis.

**Comment by gioman** [comment]
> Unfortunately, the plugin was never approved (no comments!)

@jgrocha why?

**Comment by gioman** [comment]
@jgrocha it is still awaiting approval? I cannot see it in https://plugins.qgis.org/

**Comment by jgrocha** [comment]
![Screenshot from 2020-05-26 11-59-23](https://user-images.githubusercontent.com/163681/82893155-7e152c80-9f48-11ea-88aa-56e306d1c950.png)

**Comment by rduivenvoorde** [comment]
@jgrocha is it possible that that is a local plugin?
I cannot find it on plugins.qgis.org either (and I am admin there, so also should see unapproved ones)
I see a 'None' which happens if a plugin version is removed or so...

![Screenshot-20200526130344-496x353](https://user-images.githubusercontent.com/731673/82893477-5a0a1900-9f51-11ea-8072-7e19aa62c3bb.png)

Can you try to upload a new version?

**Comment by gioman** [comment]
@jgrocha well it seems that my account on https://plugins.qgis.org/ has no more the permission to see unapproved plugins (I had it, as as well the permission to approve, even if I never used it). Sorry I can't help here. I also see here https://gitlab.com/geomaster/raster2postgis/-/issues/7#note_246045028 that I pushed to approve the plugin.

**Comment by jgrocha** [comment]
@rduivenvoorde I'll check and upload it again, if necessary. 

Let's close the discussing about the plugin and focus on this QEP. I'm fully supporting this QEP (and we can avoid the plugin approval discussing).

I've just mentioned the plugin, because it already addresses some technical issues and to show how I am motived to help. Just that.

**Comment by rduivenvoorde** [comment]
@jgrocha if you upload it I could approve, so people could try (maybe as experimental?)

**Comment by gioman** [comment]
@elpaso would the functionality allow to import raster using Processing (so with the possibility to import data in batch mode)?

**Comment by elpaso** [comment]
@jgrocha nice plugin, but what me and Even are planning to do here is a bit different: 
1. PG raster write support (with no out-of-db support) will be added to GDAL, and this is the biggest part of the work, it will make the PG raster export functionality immediately available to any tool that uses GDAL.
2. integration of the new GDAL functionality with QGIS GUI and drag and drop from browser workflow, (@gioman) I didn't plan to do anything in particular for processing but as long as it uses the QGIS API for raster conversions (https://qgis.org/api/classQgsRasterFileWriter.html#details) it should work out of the box.

**Comment by nyalldawson** [comment]
>  it should work out of the box.

Well - kind of :wink:  we'd need a way to specify pg output locations. Currently all the raster output widgets only accept file based paths.

**Comment by elpaso** [comment]
@nyalldawson I thought that the little browser integration we did recently would have been able to pick up the PG stored connections doesn't it?

**Comment by nyalldawson** [comment]
It's only used for vector outputs -- we'd need to extend the raster output widget to add the direct save to db UI. (There was no need till now!)

**Comment by 3nids** [comment]
proposal has not been marked as eligible for grants 2020
see https://lists.osgeo.org/pipermail/qgis-developer/2020-June/061439.html

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
