### ISSUE TITLE
QGIS Server, OGC tests and Continuous Integration

### ISSUE THREAD

**Issue by pblottiere** [qgis/QGIS-Enhancement-Proposals#175]
# QGIS Server, OGC tests and Continuous Integration

**Date** 2020/05/15

**Author** Paul Blottiere (@pblottiere)

**Contact** blottiere dot paul at gmail dot com

**maintainer** @pblottiere

**Version** QGIS 3.16

# Summary

QGIS Server continues to increase in popularity so we have to keep focusing on its robustness. Currently, QGIS Server is certified for WMS 1.3.0 (hopefully for OGC API Features soon too) and OGC tests are performed every night on `master` to ensure that we're still compliant. For the record, nightly HTML reports are available [here](http://test.qgis.org/ogc_cite/).

However, considering that these tests are performed on ``master`` branch once a day, OGC compliancy is checked **after** a new development have been merged. Of course, when we have doubts, "someone" manually tests the new feature or the bugfix before merging, but this situation is far from being optimal and can lead to regressions. Moreover, it can be hard and frustrating to not be able to run these OGC tests locally during the development phase.

This proposal will allow to run compliancy tests both locally - in a simple and direct manner - as well as for each Pull Request, focusing on the WMS 1.3.0 testsuite for now.

### pyogctest

OGC tests are performed with TeamEngine and may be executed through a Web Browser or thanks to a REST API. In case of the REST API, results can be returned in XML, EARL (RDF/XML) or HTML. In any case, it's not a very friendly or efficient working environment for a developer. So the purpose is to provide a more built-in testing environment for developers and/or new comers.

The first step will be to create a Python package named (for example) `pyogctest` allowing to easily run OGC tests and specialised for QGIS Server. These OGC tests are provided in Docker images on [Docker Hub](https://hub.docker.com/u/ogccite) and need a map server URL. So we could use `pyogctest` as below:

```` bash
$ pyogctest https://qgisserver
````

In other words, `pyogctest` will:

1. download and run the corresponding testsuite docker image
2. deduce the right URL according to the tests to execute (`https://qgisserver?SERVICE=GetCapabilities&VERSION=1.3.0&SERVICE=WMS` in case of the WMS 1.3.0 service)
3. execute the testsuite thanks to the TeamEngine REST API
4. parse the results to provide an explicit report

The report could be generated in HTML for nightly tests (which still have a strong interest for end-users communication) but the default output would be like `pytest`. Some basic options will be available:

- `-v` for verbosity
- `-p` for a specific .qgz project 
- `-r` to display tests matching a regular expression
- `-s` to select an OGC service (only 'wms130' will be available for now)
- `-o` to select the output format ('html' or 'stdout' by default)

For example:

````bash
$ pyogctest -v -s wms130 https://qgisserver
data_independent::basic_elements::version_negotiation::negotiate-no-version PASSED
data_independent::basic_elements::version_negotiation::negotiate-basic_elements-version PASSED
...
...
````

Source code for `pyogctest` will be hosted in a dedicated repository.

Moreover, it should be noted that a running QGIS Server is still necessary with a specific project and data. These files will be provided through `pyogctest`.

#### GitHub Actions

The second step is to integrate these WMS 1.3.0 OGC tests in the QGIS CI mechanism thanks to
GitHub Actions. A Docker image will be used to run a QGIS Server instance and `pyogctest` will execute OGC tests and display results "a la" `pytest`.

Concretely, this implies to add a new workflow in the `.github/workflows` directory of QGIS which will:

- build a Docker image with QGIS Server according to the current branch
- launch a docker-compose YAML script to run QGIS Server and NGINX
- execute `pyogctest`

### Nightly tests

Currently, scripts to run OGC tests are available in the [CertifSuite repository](https://github.com/qgis/QGIS-Server-CertifSuite). These scripts will be updated to use `pyogctest` instead.

### Documentation

The documentation on [OGC Conformance Testing](https://docs.qgis.org/3.10/en/docs/developers_guide/ogcconformancetesting.html) will be updated accordingly.

#### QGIS repository

The `tests/testdata/qgis_server/ets-wms13/` directory will be cleaned.

### Affected Files

- a new repository for `pyogctest`
- `tests/testdata/qgis_server/ets-wms13/` in [QGIS](https://github.com/qgis/QGIS) source code
- `.github/workflows` in [QGIS](https://github.com/qgis/QGIS) source code
- `testsuite/wms-1.3.0` in [QGIS-Server-CertifSuite](https://github.com/qgis/QGIS-Server-CertifSuite)
- `developers_guide/ogcconformancetesting.rst` in [QGIS-Documentation](https://github.com/qgis/QGIS-Documentation)

## Performance Implications

None

## Backwards Compatibility

None

## Votes

(required)

**Comment by pblottiere** [comment]
## Progress report

#### pyogctest

A Python tool named [pyogctest](https://github.com/pblottiere/pyogctest) has been implemented to run OGC tests in command line for the WMS 1.3.0 testsuite. 

#### GitHub Actions

 From now on, ``pyogctest`` is integrated with GitHub Action in QGIS continuous integration mechanism to avoid regressions for WMS 1.3.0: https://github.com/qgis/QGIS/pull/38644.

#### Nightly tests

``pyogctest`` is also integrated with QGIS-Server-CertifSuite for the nightly tests: https://github.com/qgis/QGIS-Server-CertifSuite/pull/16. 

#### Documentation

The documentation chapter about OGC and conformance tests is up-to-date: https://github.com/qgis/QGIS-Documentation/pull/6100.

#### QGIS repository

Finally some legacy files for conformance tests have been cleaned from the QGIS repository: https://github.com/qgis/QGIS/pull/38698.

## Conclusion

Thanks a lot to everyone who made this possible, it's a huge step forward for QGIS Server QA :+1:.

**Comment by haubourg** [comment]
Great job @pblottiere !

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
