### ISSUE TITLE
Kill evis

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#176]
# QGIS Enhancement: Kill evis

**Date** 2020-05-18

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall dot dawson at gmail dot com

**maintainer** NONE (and that's the problem!)

**Version** QGIS 3.14

# Summary

Let's kill the evis plugin for QGIS 3.14. It's completely unmaintained and full of legacy code, with zero integration between the plugin and the rest of QGIS. If we kill it for 3.14 then it gives organisations time to adapt (and possibly develop a 3rd party plugin version if desired) prior to the next LTR release (3.16).

There has been NO changes made to this plugin (aside from fixes to avoid breaking QGIS compilation) for over 10 years. In 2010 a bug fix was made to this plugin. In the following 10 years the ONLY changes have been compilation fixes.

We've previously put out calls for interest in community members stepping up to maintain this plugin, with zero interest.

![image](https://user-images.githubusercontent.com/1829991/82162411-8685bb80-98e7-11ea-8ec5-8f78ed277365.png)

## Comparison of feature set

The evis plugin offers:

- connection to custom database services. We do NOT want to expose this anymore -- QGIS already has multiple database connection levels (db manager, browser) and the ongoing effort is to remove this duplication and offer a single, unified approach to database connections and management (via browser). Even worse, the evis plugin does a very basic handling of database queries by writing the results directly to a csv file and then re-reading in this file using the delimited text providers. There's lots of issues with this approach, including loss of field types.

- the "evis event browser" dialog: this is the main component of the plugin. It shows a dialog allowing users to "browse" through a table using next/previous buttons. This functionality is already available in the main QGIS attribute table dialog, with the main attribute table version offering much better UX (including respecting the user's form configuration). 

- viewing images attached to features: already available via the main attribute table form, via the "external resource" widget. 

- show "compass bearing" form an attribute: shows a (very ugly) arrow on top of features showing the "compass bearing":
![image](https://user-images.githubusercontent.com/1829991/82162272-8a650e00-98e6-11ea-891f-1d7e76e11917.png)
Better supported via a normal marker symbol layer with data defined rotation. (same applies to "compass offset" setting)

- "relative path" handling for attached documents. Already support by core "external resource" widget.

- "evis id tool": basically a very limited version of the identify tool, which opens the evis event browser instead of the normal attribute form.

Almost all of the plugin's functionality is already offered by core, maintained features.

## Proposed Solution

Kill it for QGIS 3.14, and notify users that the plugin was outdated and unmaintained, and that interested users should first investigate the native equivalents of evis' functionality OR fund/develop a 3rd party python based plugin which takes advantage of standard QGIS functionality (e.g. native attribute forms).

### Affected Files

all of evis

## Performance Implications

None

## Code Maintainence Implications

Great! We can drop a ton of unmaintained legacy code!

## Further Considerations/Improvements

N/a

## Backwards Compatibility

N/a

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by alexbruy** [comment]
Huge +1 from me. I also proposed to drop it several times.

**Comment by nirvn** [comment]
I have never used eVis so I can't fully appreciate the minuses (if any). But on the basis of the strong arguments for removal, big +1.

**Comment by lucamanga** [comment]
Kill it!

**Comment by luipir** [comment]
+1. I do not know how is using it, nor read user messages about it.

**Comment by persts** [comment]
eVis filled a feature gap at the time it was created. If those gaps have been filled to provide the same functionality in a more accessible and elegant way then it clearly time to retire the outdated code.

**Comment by nyalldawson** [comment]
Implemented for 3.14
