### ISSUE TITLE
OpenLitterMap data import plugin

### ISSUE THREAD

**Issue by xlcrr** [qgis/QGIS-Enhancement-Proposals#182]
# QGIS Enhancement: OLM2QGIS

**Date** 2020/05/25

**Author** Seán Lynch (@xlcrr)

**Contact** info@openlittermap.com

**maintainer** @xlcrr

# Summary

Plastic pollution is a global epidemic yet high quality open geospatial data is significantly lacking. [OpenLitterMap](https://opengeospatialdata.springeropen.com/articles/10.1186/s40965-018-0050-y) is empowering people to share data, however litter mapping is a relatively new field of GIScience that remains largely unexplored. By enabling the easy import of OLM data into QGIS, we can encourage GIS users around the world to start exploring the data and developing new science on the state of plastic pollution

## Proposed Solution

OpenLitterMap data is already accessible as a CSV by [Country](http://openlittermap.com/world/Malawi/download) (Malawi), [State](https://openlittermap.com/en/world/United%20States%20of%20America/Florida) (Florida) or [Town/City/Village](https://openlittermap.com/en/world/The%20Netherlands/North%20Holland/Amsterdam/download) (Amsterdam) however there is no way to import this data to QGIS easily and we need to improve OLM to make filterable json endpoints available too.

### Example(s)

https://medium.com/@littercoin/what-can-open-data-do-anything-28f326f68af8?source=---------4------------------

### Affected Files

na

## Performance Implications

na

## Further Considerations/Improvements

TBC

## Backwards Compatibility

na

## Issue Tracking ID(s)

na

## Votes

+1

**Comment by NathanW2** [comment]
Good idea but this should really just be a 3rd party plugin that users can
install. 3rd party plugins don't require a QEP

**Comment by nyalldawson** [comment]
I think this qep has been opened because it's a prerequisite for the grant program.

But I believe this enhancement should be ineligible for the current round of grants, because it quite clearly is a new feature, and the current grant round explicitly forbids new feature funding.

**Comment by rduivenvoorde** [comment]
@xlcrr would it not be better to handle this on the serverside? 

For example if the export would be a plain geojson file, one could just use the geojson-url into QGIS and it will always be uptodate because it is fetched during rendering.

Another advantage would be, that the url could be 'filtereing' for certain kind of litter, like only MacDonald stuff or so, by just adding it as a query parameter to the url (NOTE: this off course needs a little smarter backend there then a plain geojson dump).

**Comment by xlcrr** [comment]
Thanks for the feedback. Applied for the current grant program. This plugin is something I have been meaning to build for several years, but we are still dealing with internal OLM development before this is a priority.

In the future we will open up filterable json API endpoints with query params etc. This does not exist yet, as open citizen science data on plastic pollution is not supported yet despite permanent global pollution and significantly unexplored geospatial investigation.

If anyone would like to build this plugin, or join the research on litter mapping, or help out at OpenLitterMap (which is not yet open source but it will be once we achieve MVP) you are all welcome to download OpenLitterMap data and start using it and building with it. However, OpenLitterMap is changing, and the future OLM2QGIS plugin will need to be maintained as OLM develops.

If anyone would like to help out at OLM, including building the OLM2QGIS plugin, several co-founder positions are listed [here](https://angel.co/openlittermap/jobs)

Thanks!

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.

**Comment by xlcrr** [comment]
Thanks for the update @nyalldawson 

The OLM2QGIS plugin was eventually developed open source by the QGIS community - [we launched it on a live QGIS workshop](https://www.youtube.com/live/7-v3yelHESw)! Integrating all OLM data into QGIS has never been easier.

You can find the plugin here

https://plugins.qgis.org/plugins/openlittermap/

and the source code here

https://github.com/NaturalGIS/openlittermap

Happy mapping!
