### ISSUE TITLE
Documentation Grant Proposal

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS-Enhancement-Proposals#183]
# QGIS Enhancement: Documentation Grant Proposal

**Date** 2020/05/23

**Author** Matteo Ghetta @ghtmtt, Håvard Tveite @havatv

**Contact** matteo dot ghetta at gmail dot com

**maintainer** @ghtmtt @havatv

**Version** QGIS 3.16

# Summary

QGIS Documentation is a great resource for new and power users. We have way more developers (that develop at a high rate) than doc writers, and this is leading to a number of missing feature descriptions.

This Grant Proposal aims to clean the queue of old release related issues in order to have a cleaner and more up-to-date manual. We think that it is easier for new people to document more recent features than old ones.

For this we will:

* make an issue triage for all the issues tagged with label 3.x (where x <= 12)
* go through (and close) issues labelled ToDocOrNotToDoc?
* perform a general issue triage in order to have the cleanest environment possible

Enlarging the QGIS community is very important: we need more motivated people to contribute to the documentation (hoping that the documentation is just a starting point to get into our community).

This Grant Proposal will try to increase the number of contributors to documentation and bring new people into the doc team. For this aim we will:

* update the Documentation Guidelines section with images and new step-by-step examples
* add video tutorials with specific examples and trouble shooting
* provide webinars (2 webinars, 1h hour each) where people can get into the QGIS documentation system. 

### Affected Files

Many different files, depending on the issue(s)

## Performance Implications
NA

## Backwards Compatibility

NA

## Issue Tracking ID(s)

https://github.com/qgis/QGIS-Documentation/issues

## Votes

(required)

**Comment by mbernasocchi** [comment]
@ghtmtt is this a grant 2020 proposal? if yes can you add the label? Ciao

**Comment by ghtmtt** [comment]
> @ghtmtt is this a grant 2020 proposal? if yes can you add the label? Ciao

cannot do that (limited permissions?)

**Comment by 3nids** [comment]
This proposal is directly funded by the org, it is hereby removed from the grant 2020 process.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
