### ISSUE TITLE
QGIS Server documentation enhancement - grant proposal

### ISSUE THREAD

**Issue by vpicavet** [qgis/QGIS-Enhancement-Proposals#184]
# QGIS Enhancement: QGIS Server documentation enhancement

**Date** 2020/05/29

**Author** Vincent Picavet (@vpicavet), Oslandia

**Contact** vincent dot ml at oslandia dot com

**maintainer** @vpicavet

**Version** QGIS 3.16

# Summary

QGIS Server has been heavily developed during the last years, and saw a major overhaul. Using QGIS server requires various level and areas of knowledge : OGC specifications, QGIS project configuration, System configuration for the server, deployment, monitoring, etc.

Current QGIS server documentation has improved lately, but is still not complete and up-to-date.

This Grant Proposal intends to improve the overall documentation quality and completeness concerning QGIS Server.

We will : 
- **review current QGIS Server documentation** to identify missing parts and informations to complete
- Go through all **issues marked as needing documentation** and concerning QGIS server ( https://github.com/qgis/QGIS-Documentation/issues?q=is%3Aissue+is%3Aopen+server ) and add corresponding documentation
- add **schemas** and corresponding explanations for various **QGIS Server deployment** options
- write a **complete tutorial** for QGIS Server setup, from scratch to a running instance
- explain how QGIS server can work with **3d party tools** ( e.g. QWC2, Mapproxy )
- initiate a **FAQ** for QGIS Server usage ( e.g. how to work with Oracle ? )
- integrate into the documentation a **feature matrix** for QGIS Server, comparing it to other OGC servers
- document current **limitations of QGIS Server**compared to other OGC servers, and potential workarounds (e.g. cut labels when tiling)

### Affected Files

- Only documentation files

## Performance Implications

N/A

## Further Considerations/Improvements

We will try to anticipate future documentation needs concerning QGIS server 3.16, discussing with developers currently working on feature PRs.

## Backwards Compatibility

N/A

## Issue Tracking ID(s)

- https://github.com/qgis/QGIS-Documentation/issues?q=is%3Aissue+is%3Aopen+server

## Votes

(required)

**Comment by 3nids** [comment]
This proposal is directly funded by the org, it is hereby removed from the grant 2020 process.

**Comment by haubourg** [comment]
@benoitdm-oslandia could you share here what has been achieved in the task list ? I check what I know being done already 


- [ ] -     review current QGIS Server documentation to identify missing parts and informations to complete
- [ ] -     Go through all issues marked as needing documentation and concerning QGIS server ( https://github.com/qgis/QGIS-Documentation/issues?q=is%3Aissue+is%3Aopen+server ) and add corresponding documentation
- [ ] -     add schemas and corresponding explanations for various QGIS Server deployment options
- [ ] -     write a complete tutorial for QGIS Server setup, from scratch to a running instance
- [ ] -     explain how QGIS server can work with 3d party tools ( e.g. QWC2, Mapproxy )
- [ ] -     initiate a FAQ for QGIS Server usage ( e.g. how to work with Oracle ? )
- [ ] -     integrate into the documentation a feature matrix for QGIS Server, comparing it to other OGC servers
- [ ] -     document current limitations of QGIS Servercompared to other OGC servers, and potential workarounds (e.g. cut labels when tiling)

**Comment by haubourg** [comment]
List of related PRs :

- **MERGED** Separate QGIS desktop and server documentation [#5930](https://github.com/qgis/QGIS-Documentation/pull/5930) 
- **MERGED** Add QGIS Server missing environment variables [#5936](https://github.com/qgis/QGIS-Documentation/pull/5936)
- **MERGED** Follows Add missing env var [#6069](https://github.com/qgis/QGIS-Documentation/pull/6069)
- **MERGED** Undocumented WMS parameters [#6005](https://github.com/qgis/QGIS-Documentation/pull/6005)
- **MERGED** Complete server properties [#6011](https://github.com/qgis/QGIS-Documentation/pull/6011)
- **MERGED** fix (SRC)HEIGHT/(SRC)WIDTH parameters documentation [#6110](https://github.com/qgis/QGIS-Documentation/pull/6110)
- **MERGED** [Website] Add specific item for server documentation [#803](https://github.com/qgis/QGIS-Website/pull/803)
- **MERGED** Reflow "Installation on Debian-based systems" for QGis server [#5941](https://github.com/qgis/QGIS-Documentation/pull/5941)
- **MERGED** getting started: fix bash to enable/start systemd socket/service [#5992](https://github.com/qgis/QGIS-Documentation/pull/5992)
- **MERGED** Qgis server containerized deployment [#6030](https://github.com/qgis/QGIS-Documentation/pull/6030)

**Comment by benoitdm-oslandia** [comment]
> @benoitdm-oslandia could you share here what has been achieved in the task list ? I check what I know being done already
> 
 * [x] review current QGIS Server documentation to identify missing parts and informations to complete
 * [ ] Go through all issues marked as needing documentation and concerning QGIS server (https://github.com/qgis/QGIS-Documentation/issues?q=is%3Aissue+is%3Aopen+server) and add corresponding documentation
 * [x] add schemas and corresponding explanations for various QGIS Server deployment options >  PR [#184](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/184)
 * [x] write a complete tutorial for QGIS Server setup, from scratch to a running instance
 * [X] explain how QGIS server can work with 3d party tools (e.g. QWC2, Mapproxy) > PR [#184](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/184)
   ==> in next PR 
 * [X] initiate a FAQ for QGIS Server usage (e.g. how to work with Oracle ?)
   ==> in next PR 
 * [X] integrate into the documentation a feature matrix for QGIS Server, comparing it to other OGC servers 
   ==> in next PR but may be not relevant and too difficult to maintain 
 * [ ] document current limitations of QGIS Server compared to other OGC servers, and potential workarounds (e.g. cut labels when tiling)
   ==> will not be done

**Comment by vpicavet** [comment]
Almost all points have been achieved, even if documentation is a never-ending task, and will need further refinement with QGIS server evolution.

Thanks @benoitdm-oslandia, I now close this issue.
