### ISSUE TITLE
QGIS Server and performance monitoring

### ISSUE THREAD

**Issue by pblottiere** [qgis/QGIS-Enhancement-Proposals#185]
# QGIS Server and performance monitoring

**Date** 2020/05/27

**Authors** 
  - Paul Blottiere (@pblottiere)
  - Alessandro Pasotti (@elpaso)

**Contact** blottiere dot paul at gmail dot com

**Maintainer** @pblottiere

**Version** QGIS 3.16

# Summary

QGIS Desktop and the underlying core library is in constant evolution: map rendering process, data
providers, ... But since QGIS 3.0, the map renderer used by QGIS Server is the same as the one used by the desktop application. It's very handy but this also means that QGIS Server rendering time is affected by every changes (the good, the bad and the ugly) made in the core library. However, from a map server perspective, a lost in rendering or data fetching performances might be very troublesome.

How can we easily monitor QGIS Server performances to avoid regressions on the development branch?

It's a very broad question but it raises a basic need: performances monitoring. A project currently exists, named [QGIS Server PerfSuite](https://github.com/qgis/QGIS-Server-PerfSuite), and the purpose of this proposal is to improve this infrastructure to become a more useful and relevant tool.

## Proposed Solution

Test scenarios are already executed every day to compare performances between QGIS 2.18, the last release, the LTR and the development branch. Daily and monthly reports are currently available [here](http://test.qgis.org/perf_test/graffiti/).

**Upgrade**

As can be seen, the first step is to upgrade the releases currently tested. We need to replace the QGIS 3.4 and 3.6 releases by 3.10 (LTR) and the future 3.14.

**Anomalies detection**

An important point, currently missing, is the automatic detection of anomalies. Tests are performed and results are stored in a database, then an HTML report is generated. However results themselves are not analysed and a regression may go undetected if someone doesn't look at reports on a regular basis.

A tolerance threshold has to be fixed with an alert mechanism. In practice, if the rendering time increases by `5%` on a specific scenario (daily and monthly), an email is sent to the underlying team, and measures can be taken.

**Test scenarios and datasource**

It's hopeless to test all the possible existing configurations but mainstream workflows are already extremely relevant. For example, a simple ``GetMap`` request on a project with vector layers implies to:

- parse the WMS request and open the project
- configure the layers
- fetch the features from the datasource
- render the features/labels on the map with the correct symbology
- prepare and send the response back to the client

The two main components are the feature **geometry** and the **datasource**.

QGIS Server PerfSuite comes with several scenarios for the WMS ``GetCapabilities`` and ``GetMap`` requests and the data is stored in a PostgreSQL database with Points, Lines and Polygons.

Here, we propose to add test scenarios with the same data, but on various broadly used datasource: **Geopackage**, **Shapefile** and **SpatiaLite**.

**Multi clients scenarios**

QGIS Server PerfSuite is based on [graffiti](https://github.com/pblottiere/graffiti), a simple Python tool which:

- defines test scenarios
- sends ``GetMap`` and ``GetCapabilities`` requests toward a map server  according to a specific YAML configuration (``BBOX``, ``LAYERS``, ...)
- measures the response time and store the results in a database for a later  analysis as well as the rendered image
- generates an HTML report with statistics for each scenario

An important improvement would be to simulate several clients. Actually, ``Graffiti`` sends a simple request and waits its response before sending another. It's an interesting way to work to observe specific configuration (like cache mechanisms), but it's not very representative of an actual usage.

### Affected Files

- [QGIS Server PerfSuite](https://github.com/qgis/QGIS-Server-PerfSuite)
- [Graffiti](https://github.com/pblottiere/graffiti)

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

**(required)**

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
