### ISSUE TITLE
Refactoring SLD code

### ISSUE THREAD

**Issue by rldhont** [qgis/QGIS-Enhancement-Proposals#187]
# QGIS Enhancement: Refactoring SLD code

**Date** 2020/05/29

**Author** René-Luc DHONT (@rldhont)

**Contact** rldhont at 3liz dot com

**maintainer** @rldhont

**Version** QGIS 3.16

# Summary

Currently the code for reading and writing SLD is divided into 3 classes:
* QgsVectorLayer
* QgsSymbolLayerUtils
* QgsOgcUtils

This makes the maintenance and evolution of the code very complex. It would therefore be necessary to gather and reorganize the existing code, either by extending QgsOgcUtils, or by creating a new dedicated class QgsOgcStyleUtils.

This structure also poses problems compared to the tests. It is difficult to have a complete picture of the tests concerning SLD and because it surely lacks some.

Finally we could take the opportunity to add support for reading the SLD for raster layers in QGIS Desktop and QGIS Server. A plugin already exists http://plugins.qgis.org/plugins/SLD4raster/ and the writing support is already integrated into QGIS.

## Proposed Solution
I would therefore suggest the following developments:
* Refactoring code : extending QgsOgcUtils or creating QgsOgcStyleUtils
* Refactoring of tests and extension of those
* Added SLD read support for raster layers
* Added tests to SLD read support for raster layers
* Verification and extension of tests for writing SLD for raster layers

### Affected Files

* qgsvectorlayer.h
* qgsvectorlayer.cpp
* qgssymbollayerutils.h
* qgssymbollayerutils.cpp
* qgsogcutils.h
* qgsogcutils.cpp

## Performance Implications

Unknown

## Backwards Compatibility

**(required)**

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
