### ISSUE TITLE
 Create QgsProcessingParameterGeometry

### ISSUE THREAD

**Issue by rldhont** [qgis/QGIS-Enhancement-Proposals#188]
# QGIS Enhancement:  Create QgsProcessingParameterGeometry

**Date** 2020/05/29

**Author** René-Luc DHONT (@rldhont)

**Contact** rldhont at 3liz dot com

**maintainer** @rldhont

**Version** QGIS 3.16

# Summary

There is already a parameter of type QgsProcessingParameterPoint and QgsProcessingParameterExtent but no QgsProcessingParameterGeometry to define linestring or polygon as parameter for algorithms.

For examples, the algorithm longitudinal profile has to used a Line vector layer as a parameter. So the user has to create a layer to draw the line then uses the algorithm.

## Proposed Solution

1. Create the class `QgsProcessingParameterGeometry` with `geometryType`
```
QgsProcessingParameterGeometry
{
  QString name;
  QString description;
  QgsWkbTypes::GeometryType geometryType;
}
```
2. Add methods to `QgsProcessingAlgorithm`: `parameterAsGeometry` and `parameterAsGeometryCrs`
3. Create a Widget to let user drawing the requested geometry
4. Create tests

### Example(s)

(optional)

### Affected Files

* qgsprocessingparameters.h
* qgsprocessingparameters.cpp
* qgsprocessingalgorithm.h
* qgsprocessingalgorithm.cpp

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

**(required)**

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by nyalldawson** [comment]
Can you expand on your plans for the widget interaction? (Also, isn't this clearly in bulletin of the "no new features" requirement for grants?)

**Comment by dmarteau** [comment]
ATM, Qgis enable creating new geometries in the UI by creating a new editable layer, clearly it is possible to use this path for creating geometries passed to algorithms as vector layer input. 

IMHO, the purpose here would be to provide a convenient way to create a way  to pass simple geometries without requiring a layer. The use case is to easily  create algorithms that may be used in plugins implementing algorithms  that would need to manipulate geometries in atomic way.  You may consider this as a "toolbox" feature.

**Comment by dmarteau** [comment]
Already implemented with https://github.com/qgis/QGIS/pull/38638

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
