### ISSUE TITLE
unable to save auxiliary storage

### ISSUE THREAD

**Issue by Gildae53** [qgis/QGIS-Enhancement-Proposals#189]
# QGIS Enhancement: Title

**Date** 2020/06/01

**Author** John McLellan (@user)

**Contact** jmc67@iinet.net.au

**maintainer** @user

**Version** QGIS 3.12.2

# I cannot save a Project after working on it as an error message appears stating...UNABLE TO SAVE PROJECT..."unable to save auxiliary storage. ('Cannot open C:Users/../App Data/Local/Temp/QGIS3-vKZUne/*.qgd for input')

**(required)**

## My Section

(optional) Insert custom sections wherever needed

## Proposed Solution

I have tried searching all forums, some people state the problem is Windows Security in Win 10 but I do not have this activated. I also use AVG which does not delete Temp folders. Somehow the Temp folder that QGIS is using to store information on the project is getting deleted, and this is verified when I go to the Temp folder and it is not present... This is very frustrating as I cannot think of any other program that has this problem and it has to have something to do with QGIS itself and not windows. Any help appreciated.

### Example(s)

(optional)

### Affected Files

(C:Users/../App Data/Local/Temp/../*.qgd)

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

**(required)**

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by gioman** [comment]
@Gildae53 wrong place, bugs are reported here https://github.com/qgis/QGIS/issues anyway before filing please check if the issue has already beenhttps://github.com/qgis/QGIS/issues?q=is%3Aissue+is%3Aopen+auxiliary been reported https://github.com/qgis/QGIS/issues?q=is%3Aissue+is%3Aopen+auxiliary+
