### ISSUE TITLE
qgis_process run .model3

### ISSUE THREAD

**Issue by anakaine** [qgis/QGIS-Enhancement-Proposals#200]
# QGIS Enhancement Proposal: Run .model 3 using qgis_process

Date 2019/02/27

Author anakaine (@anakaine)

Contact anakaine at gmail dot com

Maintainer @nyalldawson

Version >= QGIS 3.16+

# Summary

The proposal is to permit QGIS to run .model3 model files from the command line / cli using qgis_process. This is mentioned as a potential feature enhancement here: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/140

## Proposed Solution

Extending qgis_process to permit the running of .model3 files from the command line / prompt / cli. Ideally model parameters should be able to be included via names switches, eg: --InputFileAOI "dog.shp" --StatsType "Maximum Area". 

## Performance Implications

Should be able to run the model headless. 

## Backwards Compatibility

Not Required

**Comment by nyalldawson** [comment]
This already works.... 🤨

**Comment by anakaine** [comment]
Well, that's embarassing @nyalldawson, sorry. 

So, I've been looking for some documentation on how to use - is there a place to start? Sorry.

**Comment by kannes** [comment]
This is very well hidden indeed. The help when running `qgis_process` gives some hints but the easiest way to start is to open your model as processing tool (from the toolbox), then click "Advanced" and "Copy as qgis_process Command". This will give you the full invocation of your current settings in the tool dialog. What a great little helper that is!
