### ISSUE TITLE
Add z/elevation slicing and filtering to map renders

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#201]
# QGIS Enhancement: Add z/elevation slicing and filtering to map renders

**Date** 2020/11/19

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall dot dawson at gmail dot com

**Version** QGIS 3.18

# Summary

Many types of spatial datasets include an elevation or z component. While the QGIS 3D framework gives users one way to explore z based data, there's also use cases where this data needs to be handled in special ways in a 2D map render.

Some examples of elevation-aware datasets which can be useful to visualise in 2d include:
- building interior datasets with overlapping features at different elevations corresponding to the different levels of the buildings
- pipeline and asset datasets containing features at different levels below ground
- drill hole samples with different values at different elevations below ground
- point clouds

This proposal covers adding the ability to set a z range filter on a map render, causing only features which fall within this range to be rendered in a 2d map. While the proposal covers the underlying API work only, it is believed that future follow up work could expose some form of "z range slider" widget to users to allow them to interactively set z range filters on a QGIS map canvas. Additionally, z ranges could be exposed for layout map items, allowing individual layout maps to have their own individual z ranges set.

## Proposed Solution

The QgsMapSettings class will be extended with the addition of members for setting and retrieving the map's z range.

```
    /**
     * Returns the range of z-values which will be visible in the map.
     *
     * \see setZRange()
     * \since QGIS 3.18
     */
    QgsDoubleRange zRange() const;

    /**
     * Sets the \a range of z-values which will be visible in the map.
     *
     * \see zRange()
     * \since QGIS 3.18
     */
    void setZRange( const QgsDoubleRange &range );
```

By default, the z range will be set to a maximal range -- ie it will be initialized to the maximum possible range:

```
   QgsDoubleRange mZRange { std::numeric_limits< double >::lowest(), std::numeric_limits< double >::max() };
```

Similarly, QgsRenderContext and QgsMapCanvas will be extended with equivalent getters and setters for the z range filter. 

(Filters set on the QgsMapSettings object will be passed to all QgsRenderContext's used internally during the map render)

This is implemented in this commit: https://github.com/nyalldawson/QGIS/commit/7ab5ec96192a4a71f604473681f83abe9d143cf8

## Layer type support

Initially, only the point cloud layer renderer will consider the map's z range filter and skip rendering any points which fall outside the specified range (see https://github.com/nyalldawson/QGIS/commit/7ab5ec96192a4a71f604473681f83abe9d143cf8#diff-8e2551a24e2c3eb717e74de83bb5abe813ed9c1c11becdeac17cad4f55d7b2c3R110).

Future work could extend the vector layer renderer and allow it to filter features based on z range also.

### Affected Files

QgsMapSettings, QgsRenderContext, QgsMapCanvas and the different map layer renderers.

## Performance Implications

None

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

N/A

**Comment by haubourg** [comment]
Wow, I'd never imagined such a feature and this is a great idea!
+1

**Comment by anvpires** [comment]
+1
This is a great idea.

**Comment by wonder-sk** [comment]
Sounds good to me!

I guess at this point as we do not deal with vertical datums, we would not try to interpret / reproject Z coordinates, right?

And once we support vertical datums - do you have any thoughts how this would be done? Integrate information about vertical datum to the QgsCoordinateReferenceSystem, so that destination CRS of map settings would also define vertical CRS, so that the Z range would be expected to be in that vertical CRS and Z coordinates from different map layers would get transformed?

**Comment by nyalldawson** [comment]
> I guess at this point as we do not deal with vertical datums, we would not try to interpret / reproject Z coordinates, right?

That's correct -- there is code in QgsGeometry::transform to control whether the z coordinate is transformed along with x/y, but it's skipped by default and we don't use it in master anywhere.

> And once we support vertical datums - do you have any thoughts how this would be done? Integrate information about vertical datum to the QgsCoordinateReferenceSystem, so that destination CRS of map settings would also define vertical CRS, so that 
the Z range would be expected to be in that vertical CRS and Z coordinates from different map layers would get transformed?

I'd need to look into this further, but my current rough thoughts are:
- we want to keep everything possible handled at the proj level. proj already handles compound crs definitions consisting of horizontal + vertical components, so we'd want to hook into/expose this, and then let proj determine the correct coordinate operation which also transforms the z values.
- this may take the form of adding a new Type enum to QgsCoordinateReferenceSystem, with selected values from the proj PJ_TYPE enum (e.g. "Geographic2D", "Geographic3D", "Vertical", "Projected", "Compound" ). This would be exposed to users when selecting / viewing CRS information
- We'd add api to get the sub crses associated with compound crs (raising an exception for any non-compound crses), and api to create a compound crs from a horizontal + vertical component crs
- we'd then need to ensure that the destination crs in map settings is a compound crs when desired, and if it is, we ensure that geometry z values are correctly transformed during rendering (this also would apply to 3d maps). Probably this will take the form of requiring the user to select a compound or geographic3d crs for their project - but we may also need split this choice and let users pick a horizontal + vertical crs separately. 
- we'd also need to consider if we need to extend the current GUI for handling coordinate operations to vertical operations too - e.g. allowing users to pick which vertical grid shift to apply for a project
- (add processing algorithms to apply vertical transforms to a dataset)

There's a fair bit to unpack there, and it's not the kind of change we should just bolt on without working through all the implications of it.

So for now, z = whatever the z value is in the dataset, completely untouched :laughing:

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
