### ISSUE TITLE
Locale support for numeric input and display: revision and enhancements

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS-Enhancement-Proposals#210]
# QGIS Enhancement: Revision and completion of locale support for numeric input and display

**Date** 2021/02/23

**Author** Alessandro Pasotti (@elpaso)  & Alexandre Neto (@SrNetoChan)

**Contact** elpaso at itopen dot it

**maintainer** @elpaso

**Version** QGIS 3.20

# Summary

During the years support for locale number formatting (decimal separator and thousands separator) has been introduced and improved inside QGIS UI but there are still some places in the QGIS UI were number formatting options are not taken into consideration.

This leads to inconsistencies in the UX/UI and and overall perception of unprofessional GUI development from people using locales that do not use the english locale settings for numeric formatting.

## Proposed Solution

We propose a systematic approach where we will go through all the GUI elements of QGIS and identify/fix all the remaining number formatting issues, writing automated tests were possible and useful.

Note that there are a few places were we do not want to display localized numbers, specifically when displaying input strings to be passed to external programs (like GDAL utilities for example).

It is important for developers (both QGIS C++ core and Python)  to have a good reference/best practice list for writing locale-aware UIs, we propose here to write a few dedicated paragraphs to the QGIS official developer docs and a few examples to the Python QGIS cookbook.

## Votes

(required)

**Comment by pcav** [comment]
Agreed fully, this is a PITA for non English users.

**Comment by rduivenvoorde** [comment]
See for example this User list message: https://lists.osgeo.org/pipermail/qgis-user/2021-June/049049.html

**Comment by anitagraser** [comment]
Hi @elpaso and @SrNetoChan, have you already sent a final report for this funded enhancement? I understand that https://github.com/qgis/QGIS/pull/43831 was the main PR but I haven't been able to locate the report yet. It would be great if you could add a link in https://github.com/qgis/PSC/issues/56.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
