### ISSUE TITLE
Notarizing QGIS for macOS

### ISSUE THREAD

**Issue by PeterPetrik** [qgis/QGIS-Enhancement-Proposals#218]
# QGIS Enhancement: Notarizing QGIS for macOS

**Date** 2020/03/19

**Author** Peter Petrik (@PeterPetrik )

**Contact** peter.petrik@lutraconsulting.co.uk

**maintainer** @PeterPetrik 

**Version** QGIS 3.20/3.22

# Summary

Beginning with macOS 10.14.5 systems, QGIS has to be notarized. At the moment, users have to do security exception to allow installation and launch of the QGIS on their systems (as stated on the download section on the webpage: "On first launch, please right-click on the QGIS app icon, hold down the Option key, then choose Open.")

# Proposed solution

The description how to notarize the application in in the offical Apple [documentation](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution). Aim of this exercise is to make required steps for the QGIS and the libraries packaged in the all-in-one bundle for PRs and LTRs. This is to be deployed on the QGIS official macOS server to be run automatically.

### Example(s)

<img width="495" alt="Screen Shot 2021-03-19 at 15 53 39" src="https://user-images.githubusercontent.com/804608/111799518-61792500-88cb-11eb-9423-571bbc14784f.png">

### Affected Files

https://github.com/qgis/QGIS-Mac-Packager

## Issue Tracking ID(s)

https://github.com/qgis/QGIS-Mac-Packager/issues/31

**Comment by dponti** [comment]
Peter, 
What is the current status of this enhancement - is there a time frame for a fix? I recently upgraded to a new MacBook Pro that requires Catalina or above and am having this notarization issue. Furthermore, security constraints by my agency will not allow for a workaround for running software that is not notarized (eg. Option-Open does not provide an Open button and I have no ability to except QGIS in the Security preference pane (this option is grayed out even after authenticating to make changes). Thanks for any updates you can provide. Thank you!

<img width="413" alt="Screen Shot 2021-09-17 at 12 53 44 PM" src="https://user-images.githubusercontent.com/26747679/133846080-e7b57247-eca7-45e8-af68-cfb03c681083.png">
.

**Comment by dponti** [comment]
Peter, 
What is the current status of this enhancement - is there a time frame for a fix? I recently upgraded to a new MacBook Pro that requires Catalina or above and am having this notarization issue. Furthermore, security constraints by my agency will not allow for a workaround for running software that is not notarized (eg. Option-Open does not provide an Open button and I have no ability to except QGIS in the Security preference pane (this option is grayed out even after authenticating to make changes). Thanks for any updates you can provide. Thank you!

<img width="413" alt="Screen Shot 2021-09-17 at 12 53 44 PM" src="https://user-images.githubusercontent.com/26747679/133846080-e7b57247-eca7-45e8-af68-cfb03c681083.png">
.

**Comment by gioman** [comment]
> by my agency

@dponti maybe your agency could consider supporting the necessary work, as far as I know a grant has not been given for this task (https://blog.qgis.org/2021/05/04/qgis-grant-programme-2021-results/).

**Comment by PeterPetrik** [comment]
The grant did not go forward, but I got some small funding to try to fix this one this year from the QGIS packaging money. I am not sure yet how is the feasibility this year.

**Comment by andreasneumann** [comment]
The QGIS PSC decided in May to fund this development - see https://lists.osgeo.org/pipermail/qgis-psc/2021-May/009364.html
@PeterPetrik , this is in addition to the MacOS packaging budget.

**Comment by agiudiceandrea** [comment]
Hi @PeterPetrik, what is the current status of this enhancement?

**Comment by PeterPetrik** [comment]
@3nids took over macOS packaging, best to ask him

**Comment by nickbearman** [comment]
Hi @3nids do you have an update on this? The only other thread I can see is https://github.com/qgis/QGIS/issues/32167 with no newer updates (unless I am missing something, please correct me!). Thanks

**Comment by nickbearman** [comment]
@PeterPetrik do you know what is happening here? Do you have any update from @3nids ?
Thanks!

**Comment by PeterPetrik** [comment]
Notarization will be probably implemented as part of https://github.com/qgis/QGIS-Enhancement-Proposals/issues/270 by OpenGIS

**Comment by nickbearman** [comment]
> Notarization will be probably implemented as part of #270 by OpenGIS

Thanks @PeterPetrik

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
