### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by aleixpol** [qgis/QGIS-Enhancement-Proposals#220]
# QGIS Enhancement: Flatpak support

**Date** 2021/03/22

**Author** Aleix Pol Gonzalez <aleixpol@kde.org>

**Contact** aleixpol@lde.org

**maintainer** @aleixpol

**Version** QGIS X.X ?

# Summary

The goal of this issue is to officially support QGIS builds for flatpak hosted in flathub.
Listing: https://flathub.org/apps/details/org.qgis.qgis
Packaging Sources: https://github.com/flathub/org.qgis.qgis
Current usage stats: https://klausenbusk.github.io/flathub-stats/#ref=org.qgis.qgis&interval=infinity&downloadType=installs%2Bupdates

## My Section

I started with QGIS packaging back in 2018 because my father, who is an architect, needed to use it in his Ubuntu machine and was unable with the current packaging back then.

I've been keeping up with it since, initially only supporting the latest version, since recently supporting the latest lts as well as the last release proper.

I was pointed to suggest it because issues created by Flatpak users kept being claimed to be unsupported, even though there's only a few packaging issues.

An important advantage of using flatpak is that it allows us to target any linux distribution.

## Proposed Solution

You can feel free to CC me if there's an issue with the packaging that I can help with.
I also have >15 years of experience developing C++ and Qt. My main focus isn't packaging per se. 
The packaging is based on org.kde.Sdk which I also maintain.

### Example(s)

```
flatpak install flathub org.qgis.qgis
flatpak run org.qgis.qgis
```

## Performance Implications

None that I know of.

**Comment by nyalldawson** [comment]
Thanks @aleixpol! Last step would be to announce this QEP on the QGIS user and QGIS developer lists so that we can start getting feedback...

**Comment by nyalldawson** [comment]
How would you propose we handle issues which are specific to the flatpak version? Would they be filed against the flathub repo or on the main QGIS bug tracker? (And if the answer is the main tracker (ideally), are you actively monitoring this?)

**Comment by nyalldawson** [comment]
(I should add that I'm supportive of this move, and think that there's a lot of value the project gets by officially supporting a flatpak based installer :+1: )

**Comment by lucamanga** [comment]
👍  for flatpak version, with two packages one regarding LTR and one the current version.

**Comment by m-kuhn** [comment]
This is very welcome
@aleixpol has a long record as an active contributor to the open source / KDE / flatpak ecosystem. Having a maintainer like him committed to this is a very good base for a solid product.

**Comment by rduivenvoorde** [comment]
@aleixpol Thanks for all the work you already did. 
Also note that flatpak was already more or less 'official' (at least to me):
https://qgis.org/en/site/forusers/alldownloads.html#flatpak
(ah now I see the comment of @gioman about not officially supported...)

**Comment by aleixpol** [comment]
> How would you propose we handle issues which are specific to the flatpak version? Would they be filed against the flathub repo or on the main QGIS bug tracker? (And if the answer is the main tracker (ideally), are you actively monitoring this?)

For me the easiest is to keep the packaging issues in flathub's repository. I don't think I can disable the issues over there so it would stay.

I understand using github.com/qgis/qgis/ issues is better though. Maybe it would make sense to have a flatpak label there. I see there's a linux one though without anything opens, so we're either awesome there or tagging doesn't work as well as it could. https://github.com/qgis/QGIS/labels/Linux

I imagine that, at least for starting, we can have a mix of both for now and see where we fail.

> Isn't the crux that we have to make clear (to bugfixers/maintainers) that flatpak(permission)-related issues should be moved to the flatpak issue list?

Bugs needs addressing no matter what. If we move lists or whatever is an implementation detail. But yes, as discussed above, let's discuss what a "flatpak issue list" means.

**Comment by jgrocha** [comment]
Thanks for this proposal @aleixpol 
Since I'm not familiar with flatpak and you are definitely an expert, let me ask if hardware acceleration like OpenCL/CUDA work with flatpak? I'm using nvidia proprietary drivers on Ubuntu, for instance. (I could have tried by myself, but I'm just being lazy and I'm asking you.)

**Comment by aleixpol** [comment]
> Since I'm not familiar with flatpak and you are definitely an expert, let me ask if hardware acceleration like OpenCL/CUDA work with flatpak?
Flatpak supports using the proprietary drivers from nvidia, so it should work. I haven't tested it or know anyone who might have.

**Comment by aleixpol** [comment]
There hasn't been much comments on the topic for the last few months, how do we proceed here?

**Comment by rduivenvoorde** [comment]
@aleixpol what is your proposal exactly. 
I think (for me) Flatpak support is 'offical' as you are packaging AND available for issues.
Do you want more information in the 'Flatpak' paragraph in our docs? https://qgis.org/en/site/forusers/alldownloads.html#flatpak
Feel free to change (or sent me info what you think is essential).

Some things, I am not sure of, and could maybe added (my feeling is that peeps trying out QGIS this way are (like me) no fervent flatpak users...):

- after the described install/run, I have QGIS 3.20, how to start the LTR (which you also package, you do say?)?

- I see the flatpak QGIS uses a different profile folder then our standard one: `~/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default`... 
Is that because of the sand boxing? Should/can we (re) use your other folder? I tested:
- `flatpak run org.qgis.qgis --profiles-path /tmp/qgispro` which failed to save something (flatpak permissions?)
- but `flatpak run org.qgis.qgis --profiles-path /home/richard/.local/share/QGIS/QGIS3` succeeded, and (at least I had all my plugins and models...)

- are there other limitations/obvious flatpak things an average QGIS user should be aware of?

**Comment by aleixpol** [comment]
> @aleixpol what is your proposal exactly.
> I think (for me) Flatpak support is 'offical' as you are packaging AND available for issues.
> Do you want more information in the 'Flatpak' paragraph in our docs? https://qgis.org/en/site/forusers/alldownloads.html#flatpak
> Feel free to change (or sent me info what you think is essential).

For me, the important thing is that I don't get issues from frustated users that they were told that a bug report should be opened elsewhere downstream because they flatpak is not supported. Much like here: https://github.com/qgis/QGIS/issues/44630#issuecomment-895782172
 
> Some things, I am not sure of, and could maybe added (my feeling is that peeps trying out QGIS this way are (like me) no fervent flatpak users...):
> 
>     * after the described install/run, I have QGIS 3.20, how to start the LTR (which you also package, you do say?)?

You have to install one or the other, you can't do both. At least not easily.

>     * I see the flatpak QGIS uses a different profile folder then our standard one: `~/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default`...
>       Is that because of the sand boxing? Should/can we (re) use your other folder? I tested:

That's correct. Flatpak uses ~/.var to store files. This way every application doesn't need to see all your private files.

>     * `flatpak run org.qgis.qgis --profiles-path /tmp/qgispro` which failed to save something (flatpak permissions?)

It sure depends on how your /tmp/qgispro is set up. I have personally never used --profiles-path.

>     * but `flatpak run org.qgis.qgis --profiles-path /home/richard/.local/share/QGIS/QGIS3` succeeded, and (at least I had all my plugins and models...)
> 
>     * are there other limitations/obvious flatpak things an average QGIS user should be aware of?

The biggest thing to note has been how to install 3rd party plugins. It's described in the README.
https://github.com/flathub/org.qgis.qgis

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
