### ISSUE TITLE
QGIS telemetry

### ISSUE THREAD

**Issue by hf97** [qgis/QGIS-Enhancement-Proposals#224]
# QGIS Enhancement: QGIS telemetry

**Date** 2021/04/30

**Authors** 
- Hugo Ferreira (@hf97)
- Filipe Barbosa (@flipsboy)
- Nuno Morais (@dancrossss)
- Áureo Benedito (@AureoBenedito)
- Jorge Rocha (@jgrocha)

**Contacts**
- hugoanf97 at gmail dot com
- filipebarbosa96 at hotmail dot com
- a77368 at alunos dot uminho dot pt
- aureojoel3 at gmail dot com
- jgr at geomaster dot pt

**Maintainers**
- @hf97
- @flipsboy
- @dancrossss
- @AureoBenedito

**Version** All new releases.

# Summary

This proposal is being developed as a project of University of Minho computer science degree under the guidance of teacher Jorge Gustavo Rocha, avid contributer to the qgis community.

Nowadays, most software resort to some form of telemetry to improve user experience.

This being a open source project we bring a proposal to the QGIS community to add these same features to this software but always with a focus on user privacy and following every rule of data protection regulations. To give full control to the user, by default, all collected data options will be turned off.

Data about QGIS usage can be collected from different sources. This proposal reviews all possible sources of information about QGIS usage. All this information should be centralized and processed to generate reports about QGIS usage.

Data can be collected on servers (when downloading, check updates, getting the news feed), can be collected on QGIS Desktop and QGIS Server.

#### Schema

<img src="https://user-images.githubusercontent.com/40798729/116679647-b2883880-a9a2-11eb-895c-8ef633581451.png" width="750">

##### Downloads

- Track each download (if possible)
  - On qgis.org.
  - On https://qgis.org/ubuntu.
  - Snap downloads.
  - Flatpak.
  - Ask others offering QGIS downloads (LUTRA MacOs download).

- Information about downloads:
  - Quantity.
  - Version.
  - Operative System.
  - Location.
  - Date.

#### 1.2 Collected data on QGIS Server application

- Protocols. WMS, WFS, WMTS, etc.
- Number of requests.
- Location.
- Date.

#### 1.3 Collected data on QGIS Desktop application

The collected data will be the following:

- At start:
  - Version
  - Operative System
  - Active plugins
  - Start time (to estimate usage time)
  - Generate session ID for each running instance
  - Interface:
    - Language
    - Locale
    - UI Theme
- During operation
  - Plugin installation
  - Providers used
    - for each layer added, the provider type is recorded
  - Project storage type (open/write)
    - File based, PostgreSQL, GeoPackage

#### 2.1. QGIS Interface.
On the UI side, 3 changes will be made.

##### Home screen.

<img src="https://user-images.githubusercontent.com/40798729/116679600-a43a1c80-a9a2-11eb-8979-406123b0d424.png" width="750">

This pop-up will appear the first time QGIS is opened asking the user if they want to share their data and unless yes or no is pressed will appear every time QGIS is opened.
Later the option can be changed.

##### Help menu options.

<img src="https://user-images.githubusercontent.com/40798729/116679537-8a98d500-a9a2-11eb-9818-3a49cc214b1f.png" width="750">

A new "Collected logs and diagnostic data" option will be added.

When selected, the user will be redirected to a folder named "Logs" in the program installation directory with a ZIP containing all the collected telemetry and logs.

##### Settings menu.

<img src="https://user-images.githubusercontent.com/40798729/116679494-7ce34f80-a9a2-11eb-9770-f54f2de92aac.png" width="750">

A new category in the settings menu called "Telemetry". In here the user can choose between opting in or out.
It also contains all the information about the privacy policies.

#### 2.2. File types.

The telemetry will be saved in a JSON file.

<img src="https://user-images.githubusercontent.com/40798729/116679311-4ad1ed80-a9a2-11eb-9414-bbe41544805e.png" height="750">  

Also, there will be created a log file with the logs from the session that won't be sent to the server. 

#### 2.3. Saving and sending the data.

A folder will be created in the program installation directory called "Logs" containing the two files above in a ZIP.
This data will be sent once a week (still pending). If there is no internet connection the old data won't be overwritten and the new one will be added to the end of the file.

#### 3. Server side additions

The server will receive the files and populate a database with the corresponding data. The aggregated data from this database can be checked from a dashboard or using an API.

In every check update and news feed request the location (only country) from the request will be saved.

#### 3.1. Database architecture. Conceptual model.

<img src="https://user-images.githubusercontent.com/40798729/116679421-663cf880-a9a2-11eb-8c0f-b677ae628992.png" height="750">  

#### 3.2. Dashboard and API.

- Versions in use.
- Most used plugins.
- Most used Operating System.
- Most used providers.
- etc.

#### Why we collect ?

To provide you with the best possible experience. This information will help improve the software in performance and stability, track the most used features and other information about the program to help us understand if what we implement is working as expected and useful.

#### What we collect ?

- Track downloads of the software (on qgis.org, snapcraft, flatpak. etc)
- Track check version requests
- Track news feed requests
- Information from QGIS desktop usage provided by users
- Information from QGIS server usage provided by users

#### Sharing

All this information is aggregated and anonymized soon as it is received on the server side. All data goes to a PostgreSQL database. There is no way to recover or isolate data from a specific user. Collected data can be visualized on a usage dashboard, to be developed. Usage data can also be provided via API.

#### How to control your data

You can choose if you want to send us your data anytime, by either opting out the first time you open the software or by going to the Settings > Options > Telemetry menu.

You can also review the data we collect on your personal computer by going to the help tab and choosing the "Collected logs and diagnostic data" option.

#### Changes to this Policy

This Privacy Policy is current as of the Effective Date set forth above. We may change this Privacy Policy from time to time, so please be sure to check back periodically. Any changes to this privacy policy can be checked on our website.

### Affected Files

https://github.com/qgis/QGIS

**Comment by nyalldawson** [comment]
Can you share more detail about the C++ changes you plan to make to do the tracking and uploads?

I think it's important for organisations to be able to completely disable any telemetry support (including removing all user facing settings for it) for enterprise setups, eg via a flag in the settings ini file.

**Comment by jgrocha** [comment]
> Can you share more detail about the C++ changes you plan to make to do the tracking and uploads?
> 
> I think it's important for organisations to be able to completely disable any telemetry support (including removing all user facing settings for it) for enterprise setups, eg via a flag in the settings ini file.

Thanks for the feedback @nyalldawson 

Let me understand your point: in those enterprise setups, even if the user might be willing to share usage data, it can not turn it on, right? All options related to telemetry would be hidden and disabled. 

I hadn't thought about that possibility, but it seems easy to implement. Setting a flag is good enough to hide GUI related options, but any advanced user can go there and change it. This solution is somewhat limited.

The plan is to separate the logging from the upload. Using your example, a large organization can have logs enable for all users, but uploads disabled. They can use the logs internally. 

Even a user can use its own logs for his selfish statistics, without sharing them. If we use a stable JSON format and open source tools available on our repo, anyone can process the logs, even if they don't share them.

**Regarding C++ code**

We plan to add logging at three stages, if telemetry is enabled. In summary (for QGIS Desktop):
* on startup (to capture version, os, active plugins, startup time, interface language, locale, ui theme)
* on adding layers, data about the provider (just the provider type or it can be overridden by the provider and report additional data)
* on saving project (project storage type)

On QGIS Server (TODO):
* we already have many useful information being logged during server operation; we can use that
* TODO is when and how we configure the upload of telemetry data (environment variables?)

To upload the logs, the code is more confined to just this function. It will be easy to read. The proposal is to upload the data on every QGIS usage or daily, weekly oy monthly, depending on the user preference.

**Comment by roya0045** [comment]
Having generic information may be useful but I have a hard time seeing how that can be used. One case that may add value is registering the crash instance and the crash ID. This could be useful to document unreported crashes and priorise them.

Also I'm not sure if documenting on startup is that useful. Sometimes you need to have multiple instances running and sometimes of different version (though that may be an edge case).

On save/add data may be too much. I think upload on crash and seldomly on normal close would be adequate.

Collecting data is a balancing act between gathering useful info, not filling the receiving served with useless duplicated junk and keeping things anonymized and to a minimum and not leaking information about potential attack vectors.

**Comment by jgrocha** [comment]
We know that crashes are already captured on Windows, but not on Linux. We need to further investigate how to record a crash. If this can be recorded, we can add this option. This is a good point!

On QGIS startup, we generate a session id to identify the activities of that session. Users can have multiple instances running simultaneously, without any problem.

The goal of storing the provider on add actions is to know better what providers are effectively used. As you might know, GDAL is trying to discard unused providers to lower the maintenance effort. For less used providers, we can ask more support (in term of PR reviews, backports, etc) for the contributors willing to keep them in the core.

We do fully agree about storing the minimal necessary information. That's the purpose of this discussion: what is useful of not.

Thank you @roya0045 for helping us to identify the most important data to record.

**Comment by roya0045** [comment]
If one goal is to identify provider then yes, using project save may be a good way. Though sending the information directly on save may be suboptimal as saving can be done rapidly. Maybe on project close it would be safer. That way you can read the data of the project. Another way would be the use the recent project list and simply read the antry of those projects do detect those providers.

Using that approach from time to time is less prone to rely on trigger that might be spammed.

**Comment by elpaso** [comment]
@jgrocha I'm sorry, but honestly, I don't like this proposal.

It may be just me but disabling telemetry is the first thing I do on any software that supports it and if I have a choice between alternatives I choose the software that doesn't have telemetry at all.

Last but not least I don't see a point for QGIS Server at all: there is no direct user interaction here and everything can be easily logged without any further implementation or, if you really want some more information you could always easily write a plugin to log all you need.

If you really want to proceed I would recommend to make a build-time switch to disable it completely.

Also, I think that your energies should be better applied to enhance other aspects of QGIS.

**Comment by roya0045** [comment]
@elpaso I agree with you on that. I think the gist was to have a school project that wouldn't require too much QGIS knownledge, be standalone and possibly integrate other aspect. 

Though for such a thing I expect that the timeframe of a school trimester may be far to short to get things properly reviewed and  merged (if it gets there).

**Comment by nyalldawson** [comment]
@jgrocha 

> We plan to add logging at three stages, if telemetry is enabled.

Right, but how are you going to implement this? Will there be new classes (QgsTelemetry? QgsUserActivityLogger ?) introduced? Which library will these sit in (core/gui/app)? What signals or triggers will be used to append items to the log? Will it be exposed to Python for plugins to utilise? 

And then deeper questions...

How will you stop a malicious plugin from collating the log files on a local install and processing them/uploading them somewhere? What if an organisation wants to enable logging but have their own plugin push the logs to an internal location for analysis?

**Comment by haubourg** [comment]
Hi, 
apart from the ethical issues we need to discuss on the lists more than on a QEP, here are some of my thoughts :

- I don't see any interest in logging QGIS server, like @elpaso 
- I would be very interested in being able to collect the statistics inside of my organisation as a GIS administrator. So I would for sure create this plugin to track user's issues if QGIS does not allow it natively. (It is a perfectly fair approach inside a closed professional IT network, I already track QGIS opening and project openings via a plugin to have activitity statistics). 
- The process must really be secured also on the logger server's side so that we don't gain funny guys pushing fake data and ruining our efforts to gather some useful information.
- I bet some big companies concerned  by leaking usage information might want to stress the whole system to ensure no sensible data is collected. Expect some work here to achieve a very high quality standard for securing the telemetry process.

**Comment by ismailsunni** [comment]
Perhaps it can be implemented as a generic telemetry plugin (or extending @haubourg 's plugin if it's open-source). Then the user can set the server where the data uploaded (or use their own server). Another feature, user can set which information is uploaded and which is not.

I think the collected data on point 1.3 is already available, only need to push it somewhere.

**Comment by PeterPetrik** [comment]
> Ask others offering QGIS downloads (LUTRA MacOs download).

There is no such thing as Lutra macOS package. All macOS packages are developed here https://github.com/qgis/QGIS-Mac-Packager and released on qgis.org

**Comment by jgrocha** [comment]
> > Ask others offering QGIS downloads (LUTRA MacOs download).
> 
> There is no such thing as Lutra macOS package. All macOS packages are developed here https://github.com/qgis/QGIS-Mac-Packager and released on qgis.org

Thank you @PeterPetrik for the clarification.

**Comment by jgrocha** [comment]
> Hi,
> apart from the ethical issues we need to discuss on the lists more than on a QEP, here are some of my thoughts :
> 
>     * I don't see any interest in logging QGIS server, like @elpaso
> 

The point related with QGIS Server is just to estimate the number of QGIS Server instances running. We don't have any idea if we have 100 instances or 1000 of QGIS server running in production. But we can drop this point, since it is not relevant for the  proposal core.

>     * I would be very interested in being able to collect the statistics inside of my organisation as a GIS administrator. So I would for sure create this plugin to track user's issues if QGIS does not allow it natively. (It is a perfectly fair approach inside a closed professional IT network, I already track QGIS opening and project openings via a plugin to have activitity statistics).
> 

Good to know! Let's join our efforts to make this happen in a way that is useful for all.

>     * The process must really be secured also on the logger server's side so that we don't gain funny guys pushing fake data and ruining our efforts to gather some useful information.
> 

We were not considering that in the proposal, but that's a very good point! We'll try to find a solution to make it quite hard to push fake usage statistics to the server.

>     * I bet some big companies concerned  by leaking usage information might want to stress the whole system to ensure no sensible data is collected. Expect some work here to achieve a very high quality standard for securing the telemetry process.

That is our main purpose from the start. We would like to contribute with the best practices related to gathering and processing usage data statistics. 

Thank you for your feedabck @haubourg !

**Comment by jgrocha** [comment]
> Perhaps it can be implemented as a generic telemetry plugin (or extending @haubourg 's plugin if it's open-source). Then the user can set the server where the data uploaded (or use their own server). Another feature, user can set which information is uploaded and which is not.
> 
> I think the collected data on point 1.3 is already available, only need to push it somewhere.

Fully agree @ismailsunni in the sense that many of the information is already somewhere. The purpose of this QEP is to review all things we already have and make it more clear and more useful.

We are doing our home work and all this feedback is very useful for us. Thank you.

**Comment by pathmapper** [comment]
> The point related with QGIS Server is just to estimate the number of QGIS Server instances running. We don't have any idea if we have 100 instances or 1000 of QGIS server running in production.

I doubt this is representative, but fwiw here are some [geoseer](https://www.geoseer.net/) numbers from last year:
https://www.geoseer.net/blog/?p=2020-06-04_geospatial_server_software

Regarding this QEP: 
I'm also trying to avoid telemetry where I can. 
I can understand that it would be nice to have some usage statistics for project evaluation, but if it's opt-in (what it should) then you would get fragmentary telemetry data from only a part of QGIS users which wouldn't be representative (like the geoseer example above).

If you don't get a full picture through telemetry, I wonder if it's worth all the hassle with implementation, maintenance, privacy issues and compliance with data protection regulations like the [GDPR](https://gdpr.eu/).

**Comment by nyalldawson** [comment]
Having given this some thought over the last week, I'm -1 to introducing telemetry to QGIS. I don't think the benefits justify the cost here.

**Comment by andreasneumann** [comment]
@jgrocha - I also have reservations about these telemetry plans. I don't see much value if only a small fraction of our users have this active. And it comes with an extra infrastructure burden, additional GDPR problems, etc.

**Comment by elpaso** [comment]
Apparently I'm not the only one who thinks that telemetry is a very bad idea, this is what is happening to audacity https://www.theregister.com/2021/05/07/audacity_telemetry/

**Comment by jgrocha** [comment]
> Apparently I'm not the only one who thinks that telemetry is a very bad idea, this is what is happening to audacity https://www.theregister.com/2021/05/07/audacity_telemetry/

I was also worried about this decision!

**Comment by jgrocha** [comment]
Thank you all for the great feedback provided! You are awesome :-)

As the majority pointed out, it is not clear how the benefits justify the cost. In this case, I'll close the proposal.

The project itself will continue as an academic project.
