### ISSUE TITLE
New QGIS Community Proposal

### ISSUE THREAD

**Issue by esnyder-rve** [qgis/QGIS-Enhancement-Proposals#229]
# QGIS Enhancement: New Community for the Community

**Date** 2021/07/30
**Revised** 2022/07/29

**Author** Ethan Snyder (@esnyder-rve)

**Contact** ethan dot snyder at rve dot com

**Maintainer** Ethan Snyder

**Version** N/A

# Summary

The creation of a user-friendly community for the QGIS community.

## Current Problems

QGIS has a large community (this is a good problem to have). Many of the current platforms are single-threaded and get cluttered/lost by the volume of postings. We also have a multi-faceted community with people needing help with regular QGIS usage, pyqgis scripting, plugin development, and core QGIS development just to name a few. This variety of users are being funneled into one general channel (minus the QGIS-Users and QGIS-Developers mailing lists). Plus, there are User Groups doing their own things, as well as the variety of languages the QGIS community speaks being an international community.

The current QGIS community is broken into several platforms:
* IRC - Old & limited, good for it's time, but not for modern chat.
* Matrix - Fixes many issues with IRC, but is single-threaded and not managed by QGIS (managed by OSGeo)
* Mailing Lists - Outdated and has certain limitations (such as html messages vs plain text, images vs no images, etc...). Also the forum-ability through Nabble has been lost.
* Telegram - Basically a giant group chat which is very cluttered and some questions/discussions get lost.
* Facebook - Although official, some people don't like using Facebook (such as their TOS, "big tech").

The best thing about Open Source projects is the community, and as such, we need a nice place for the community to gather and help each other in a beginner/user friendly place.

## Searching for a solution

What we need for such a great community is something that is:
* One server, and one central spot for everyone
* Multiple rooms/channels for organized discussion about various topics
* Something with easy permissions and moderation
* Cross platform for all to access
* Easy for all to use
* FOSS is preferred, but not necessarily a must

## Proposed Solution

[Revolt](https://revolt.chat) is a FOSS alternative to Discord with completely free hosting with no feature paywalls. It's goal is to be a Discord competitor for being a feature-filled modern community chat platform.
It supports:
* multiple rooms/channels for organized discussion
* Image/file upload for uploading maps, datasets, python scripts, etc..
* Custom emojis
* Integrated voice chat (with video coming soon)
* Rich text formatting with Markdown & KaTeX support
* Bridge-able to other platforms (bridge bots exist for Discord and Telegram)
* Custom theme support
* Allows custom clients
* Commitment to 100% free platform [Revolt GitHub](https://github.com/revoltchat)
* Many more features to come (Revolt is still in a stable beta and under active development)

Screenshot:
![Screenshot 2022-07-29 105230](https://user-images.githubusercontent.com/61027950/181786475-ee132045-f86a-4b05-8073-c553721a3235.png)

Create an account for Revolt: https://revolt.chat/publicbeta
To join the QGIS server: https://app.revolt.chat/invite/eRTmS1ZV

For an overview video regarding this community, please see this [QGIS Open Day Session](https://www.youtube.com/watch?v=nrvTnkGNzSw).

## UPDATE!
This QEP has been completely revised since the original posting recommending Rocket Chat.

## Votes

PSC has reviewed and likes the Revolt platform. Once the community has received enough commitment and usage, it will be given official status and placed onto the QGIS site.

**Comment by ambarja** [comment]
It is a good idea, from my point of view I would like to be in discord, because it is more accessible for the creation of different communication spaces.

**Comment by esnyder-rve** [comment]
The reason I didn't choose discord is because it's not FOSS. It's free (with paid premium options), and very easy to setup and use (I'm active on several discord servers, plus I run one). There currently is an unofficial QGIS Discord Server, but some on the QGIS team want to stick with FOSS. There does exist bridge bots to bridge Discord and Rocket Chat though.

**Comment by skampus** [comment]
I really miss the Nabble-like structuring.
I see that Rocket Chat, being a chat, doesn't have the possibility to open threads or sort conversations.
It's true that github is not free but it seems to me that github's Discussions are a nice way to have threads ordered and easily searchable.
The existing QGIS Telegram group is quick and easy to use, but it's not the best place to start a discussion as the mailing list currently is via Nabble.

thank you for opening the discussion on this topic.

stedano

**Comment by esnyder-rve** [comment]
You sort of can have threads in Rocket Chat. By replying to a message, it becomes "threaded" in a way.
![Threaded Reply](https://user-images.githubusercontent.com/61027950/127861624-11f37020-7025-466e-a929-aea543176521.png)

But, yes I also miss Nabble. It was a way to have a forum and a mailing list all in one.

**Comment by esnyder-rve** [comment]
Also, if anyone is interested, there is an unofficial QGIS Discord server that can be used either officially, or as reference for features to discuss here. [Unofficial QGIS Discord Server](https://discord.gg/KArRdE3Hm6)

**Comment by strk** [comment]
@esnyder-rve why you cannot connect to https://matrix.to/#/#qgis:osgeo.org ? What prevents you from joining ?

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
