### ISSUE TITLE
Drop Official Support for GRASS C++ Plugin 

### ISSUE THREAD

**Issue by PeterPetrik** [qgis/QGIS-Enhancement-Proposals#234]
# QGIS Enhancement: Drop GRASS C++ Plugin

**Date** 2021/10/05

**Author** Peter Petrik (@PeterPetrik )

**Contact** peter dot petrik at lutraconsulting dot co dot uk

**maintainer** @PeterPetrik 

**Version** QGIS 3.24+

# Summary

Maintained [GRASS Processing Provider](https://github.com/qgis/QGIS/tree/master/python/plugins/grassprovider) and the modern [GRASS-GIS](https://grass.osgeo.org) covers the functionality that was previously covered by native [C++ GRASS Plugin](https://github.com/qgis/QGIS/tree/master/src/plugins/grass)

Currently, the code section receives [minimal attention](https://github.com/qgis/QGIS/commits/master/src/plugins/grass) from the developers. Also, it is not fixed in the regular bug-fix sprints before releases (at least from 2019 we reply to issues to use QGIS Processing and that plugin is unmaintained).

## Proposed Solution

From QGIS 3.24: 

- Change title/description in Plugin Manager to "GRASS  7 (not officially supported)" or similar
- Close all open bugs filed against the GRASS Plugin with a notice that it is officially unsupported, and direct them to the GRASS-GIS and GRASS QGIS Processing. Similarly, we immediately close any newly opened reports against the GRASS Plugin with the same message.
- Add CMake option (`-DWITH_GRASS_PLUGIN`) to be able to build QGIS with GRASS but without Plugin

From QGIS 4.0
- remove [C++ GRASS Plugin](https://github.com/qgis/QGIS/tree/master/src/plugins/grass).

### Affected Files

https://github.com/qgis/QGIS/tree/master/src/plugins/grass

## Further Considerations/Improvements

- no maintenance of the code
- improves compilation speed
- helps packagers

## Backwards Compatibility

n/a

## Issue Tracking ID(s)

https://github.com/qgis/QGIS/issues?q=is%3Aissue+is%3Aopen+-label%3AFeedback+label%3A%22GRASS%22+-label%3A%22Processing%22

## Votes

ping @blazek

**Comment by PeterPetrik** [comment]
yep, this is only about plugin. Provider & processing should is not part of this QEP

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
