### ISSUE TITLE
Drag and drop form actions: expose QgsAttributeForm object to Python

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS-Enhancement-Proposals#251]
# QGIS Enhancement: Drag and drop form actions: expose QgsAttributeForm object to Python

**Date** 2022/05/02

**Author** Alessandro Pasotti (@elpaso )

**Contact** elpaso at itopen dot it

**maintainer** @elpaso 

**Version** QGIS 3.28

# Summary

Since https://github.com/qgis/QGIS/pull/45461 it is possible to add action buttons to the drag and drop forms.

This proposal is to add new "Drag and drop form" scope to Python actions that will automatically expose the current form to the Python code as a ``form`` local variable.

This will make it possible to manipulate all elements of the form including the values of the widgets.

## Proposed Solution

Implement a new "Drag and drop form" scope for Python actions.

Expose the current form to the Python code as a ``form`` variable.

### Example(s)

![immagine](https://user-images.githubusercontent.com/142164/166222953-d91c9a5c-dfce-4539-8ee5-60364ddc2056.png)

![form-action](https://user-images.githubusercontent.com/142164/166223061-f59b67c3-3462-45eb-b8ba-7fa6810d5a2c.gif)

### Affected Files

qgsattributeform and qgsaction

## Performance Implications

None

## Backwards Compatibility

None

## Votes

(required)

**Comment by elpaso** [comment]
CC: @andreasneumann : this might be interesting to you too...

**Comment by esnyder-rve** [comment]
Would there be something to check the scope?
Such that:
```py
if scope.IsForm:
    form.blah()
else:
    somethingElse()
```

So that this one action could be used both inside a feature form, and outside as a right-click context menu item.

As one who uses actions and drag & drop forms a lot, I'd look forward to this.

**Comment by elpaso** [comment]
> Would there be something to check the scope? Such that:

No, that's not planned, but you could check for ``form`` being defined or use a try-except.

**Comment by nyalldawson** [comment]
Sounds fine to me -- but what approach will you use to expose this? (I.e what's the technical details? :) )

**Comment by elpaso** [comment]
@nyalldawson still a draft: https://github.com/qgis/QGIS/pull/48445

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
