### ISSUE TITLE
[WIP] QGIS 3D general enhancement proposal

### ISSUE THREAD

**Issue by Asnaia** [qgis/QGIS-Enhancement-Proposals#252]
# QGIS 3D general enhancement proposal

**Date** 2022/05/13

**Author** [Oslandia](https://oslandia.com/en/)

**Contact** evren@oslandia.com

**maintainer** @benoitdm-oslandia @ptitjano

**Version** QGIS 3.26

## Summary

As part of the [OpenLog consortium](https://oslandia.com/en/openlog/), Oslandia is in the process of developing a drillhole data visualization plugin supporting 3D, cross-section, and strat/strip log views.

The development effort is split into two separate projects:
1.  a standard python plugin, the [OpenLog plugin](https://gitlab.com/geolandia/openlog/openlog-qgis-plugin)
2.  a PostGreSQL database, the [xplordb database](https://gitlab.com/geolandia/openlog/xplordb)

In addition, Oslandia intends to implement a series of major features into the 3D module of QGIS. Although the operational end goal of the consortium is to provide a drillhole data viewer in QGIS, the feature list was built with the aim to provide enhanced UI/UX, performance, end-user documentation, and capability for all users while preserving scalability, maintainability, and stability.

Three main axes of development, based on varying levels of usage universality, are being considered here:
1. fundamental usage features refer to critically needed capabilities that should be added as soon as practically feasible, these features involve basic 3D viewer indicators, controls, or modes of interaction.
2. generic usage features refer to widely beneficial capabilities that will find use regardless of domain of application, these features involve intermediate 3D viewer labeling, views, or modes of interaction.
3. situational usage features refer to less commonly requested capabilities that will find use in a diverse range of applications and which implementation does not compromise the overall end-user experience. 

## Feature proposals

| Feature                                                            | Usage       | Category                | Issue/PR |
| -------                                                            | -------     | --------                | ------   |
| display Cartesian axis indicator / 3D compass                      | Fundamental | Indicators/Interaction  | https://github.com/qgis/QGIS/pull/48109   |
| improve camera control doc                                         | Generic     | Doc                     |          |
| display 3D bounding box outline with labels, titles, and tick-marks | Generic     | labeling/Interaction   | https://github.com/qgis/QGIS/issues/48539  |
| define 6 plane (NSWEUD) clipping                                   | Generic     | Interaction             |    https://github.com/qgis/QGIS/issues/48541 |
| display multiple 3D views (NSWEUD)                                 | Generic     | Interaction             |          |
| display applied style legends                                      | Generic     | labeling               |  https://github.com/qgis/QGIS/issues/48543  |
| display regular cuboid 3D grids                                    | Situational | Asset                   |          |
| set vertical exaggeration                                          | Situational | Interaction/Interaction |          |
| build and display 3D cross-section                                 | Situational | Indicators              |          |
| project 3D cross-section to 2D planes                              | Situational | Indicators              |          |
| overlay raster/vector/annotation data onto cross-section planes    | Situational | Indicators/labeling    |          |

### Cross-section overlays

![image](https://user-images.githubusercontent.com/28084331/169525361-616aa5b4-2507-4fca-950b-5287787ea763.png)

### 2D Surfaces and 3D volume display

![image](https://user-images.githubusercontent.com/28084331/169525494-55a206ba-c5c5-4324-8f1b-17121010db65.png)

### Cross section projection box

![image](https://user-images.githubusercontent.com/28084331/169525662-2bb835ac-619e-442d-89e9-a36770e6355d.png)

### Bounding box and 3D compass

![image](https://user-images.githubusercontent.com/28084331/169526252-1ab45c2b-390b-452f-8382-f110a42d0535.png)

## Backwards Compatibility

This proposal concerns new features, backwards compatibility is not required.

## Votes

(required)

**Comment by vpicavet** [comment]
This QEP is intended to share our development roadmap and context, and discuss features and general orientations.

@Asnaia could you add a [WIP] label to the title, so as to clarify that the QEP content will be modified later on according to reactions, or whenever further details are needed ?

Some example illustrations would be welcome a well :-)

**Comment by Asnaia** [comment]
> @Asnaia could you add a [WIP] label to the title, so as to clarify that the QEP content will be modified later on according to reactions, or whenever further details are needed ?

Done
 
> Some example illustrations would be welcome a well :-)
 
Coming soon

**Comment by roya0045** [comment]
In regards to geologic uses, have you looked into the gempy library. It would be too big as a plugin but some aspect may be useful as inspiration for a more complete representation of the information provided by sampling.

**Comment by jo-chemla** [comment]
Jumping on the bandwagon here as we (iconem, cities/monuments 3d-scans producer and consumer for ~10years) do produce a lot of georeferenced 3d-data (meshes, pointclouds) and by-products (eg orthophotographies, be it nadir Z top-down views that can be expressed as standard geotiffs, or cross-sections, elevations etc) - that probably look a lot like geological slices. 

I wanted to know what in your field is the agreed upon standard for representing non top-down orthos/cross-sections. Parsing through the [geotiff spec](https://docs.ogc.org/is/19-008r4/19-008r4.html) (looking for `height` or `elevation`) indicates that it is meant to support the 3D height component transformation - via tags like `ModelTiepointTag, ModelPixelScaleTag`, but I've never stumbled upon geotiff data & files that do have these information embedded. If I'm not mistaken, I did find once a reference to incorporating the 3d matrix transform from CRS coordinate system to image space within a 3d world file equivalent, but did not find broad use and tooling - still gdal & co? Would love to know if you have some guidance as we can probably learn a lot from it. I'm thinking both representation - ecosystem of tools that can read - but also editors, to write that information, convert between vertical CRS, apply matrix transforms etc. 

At the moment, the path we are considering - not at the file level, but at the item/asset level - would be to use a STAC catalog of items following the [stac-extensions/perspective-imagery](https://github.com/stac-extensions/perspective-imagery) for photos, and an equivalent extension for 3d, non-nadir orthos - where for now we store the bbox information (center, axes orientation and scale). Thanks for the feedback, and looking forward to better support for such 3D assets (or generic 2D projections) within qgis!

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
