### ISSUE TITLE
QGIS Enhancement: Improve the Color Swatches Interface

### ISSUE THREAD

**Issue by abodsalas** [qgis/QGIS-Enhancement-Proposals#254]
# QGIS Enhancement: Improve the Color Swatches Interface

**Date** 2022/06/14

**Author** Andres Bodini (@abodsalas)

**Contact** abodsalas@gmail.com

**Version** QGIS 3.24

# Summary
The Color Swatches interface is inefficient. Only a few color are shown at the same time. Many times the colors don't have a name and a text 'Untitled' is shown.

## Proposed Solution

Use smaller squares to show the colors, and display its name when hovering over the swatches.
Don't show any name in case it is 'Untitled'.

### Example(s)

![Mockup of new Color Swatches](https://user-images.githubusercontent.com/54449155/173682533-06d5332c-4031-4a7a-8500-42eb83d18d15.png)

## Backwards Compatibility

No backward compatibility is required.

## Votes

(required)

**Comment by roya0045** [comment]
Do you still plan on implementing this? It's somewhat late for 3.24 and it seems many would like this change.

**Comment by geomenke** [comment]
I love this idea. If a color swatch has no name, the RGB/hexidecimal value could be used.

**Comment by abodsalas** [comment]
> Do you still plan on implementing this? It's somewhat late for 3.24 and it seems many would like this change.

Sorry I don't know c++ programming. I just though that the design of color swatches could significantly improve.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
