### ISSUE TITLE
In nightmapping many menus are barely readable since the new update

### ISSUE THREAD

**Issue by stalefish57413** [qgis/QGIS-Enhancement-Proposals#256]
Hello,
sorry im not used to github and i hope this is the right place to post this.

**Since the latest update the font color changed on a lot of menu items, making them barely readable.**

Readability of the new font color is bad:
![dj1fefhbsaw91](https://user-images.githubusercontent.com/116839357/198374827-df5eafa4-8e3c-49b3-9e42-3586ab250f5c.png)

You can barely tell which boxes are checked:
![a7fanndcmbw91](https://user-images.githubusercontent.com/116839357/198374820-ad267b7f-9e7d-43be-800d-2c1fb2ee490b.png)

**Comment by nicogodet** [comment]
Fixed by https://github.com/qgis/QGIS/pull/50701 and reported in https://github.com/qgis/QGIS/issues/50674

**Comment by rduivenvoorde** [comment]
@stalefish57413 note that this github repo is for Enhancement Proposals (see other 'issues' in this repo).

To report an *issue* with QGIS go to https://github.com/qgis/QGIS/issues/ see https://qgis.org/en/site/forusers/support.html

Closing this one
