### ISSUE TITLE
Remove GeoNode Provider

### ISSUE THREAD

**Issue by giohappy** [qgis/QGIS-Enhancement-Proposals#262]
# Remove GeoNode Provider

**Date** 2023/01/23

**Author** Giovanni Allegri (@giohappy)

**Contact** giovanni.allegri@geosolutionsgroup.com

**maintainer** @giohappy

**Version** QGIS 3.30

# Summary

GeoNode core provider has proved to be a useful option to browse and load data from remote GeoNode applications, but now it suffers several drawbacks:

- it doesn't support GeoNode 4 (which is the current stable version) since it introduced breaking changes to the API and data models
- it lacks maintainers, except core developers that keep it working as it is by applying the changes required by QGIS's platform
- there's a valid alternative which is the [QGIS GeoNode Plugin](https://geonode.org/QGISGeoNodePlugin/) developed the past year by [Kartoza](https://kartoza.com/) in collaboration with [GeoSolutions](https://www.geosolutionsgroup.com/), which is managed and maintained under the umbrella of the GeoNode organization.

The [QGIS GeoNode Plugin](https://geonode.org/QGISGeoNodePlugin/) enhances the capabilities offered by the core provider, it supports both GeoNode 3 and 4, and it's easier to maintain, extend and keep it aligned with the progress of GeoNode.
[Here you can watch a video](https://youtu.be/p0R7NPSgsI0) presenting the plugin. The plugin is already available on the official [QGIS Plugins repository](https://plugins.qgis.org/plugins/qgis_geonode/).

Having both the Provider and the Plugin is confusing for users. Both are visible inside the Data Source Manager. For this reason, a workaround was implemented for the plugin to replace the GeoNode provider inside the DSM when the plugin is loaded. This isn't, of course, a proper solution and, in more recent versions of QGIS, it doesn't work very well creating even more confusion.

## Proposed Solution

For all the reasons stated in the Summary, and given the benefits offered by the new [QGIS GeoNode Plugin](https://geonode.org/QGISGeoNodePlugin/), we propose to dismiss the core GeoNode provider.

We're not aware of specific sections inside QGIS documentation dedicated to the GeoNode provider. If they exist they will be removed as well.

The work will be undertaken by Andrea Aime ([aaime](https://github.com/aaime) - [GeoSolutions](https://www.geosolutionsgroup.com/)) who is already a contributor to QGIS and has a history of high quality submissions to the project

## Timeline

We would like to implement this change to the next release, 3.30, and would like to ask for a feature freeze exception if the work is not completed by the date of the feature freeze.

## Backwards Compatibility

In terms of functionality, the new plugin supports GeoNode 3, so it can be a replacement of the core provider from the end users perspective.
Of course, it doesn't replace the core provider in terms of programming API.

## Votes

(required)

**Comment by elpaso** [comment]
Big +1, IMHO it was a mistake to add it in core in the first place.

**Comment by nyalldawson** [comment]
> IMHO it was a mistake to add it in core in the first place.

I wouldn't go that far -- it was a period in time before all your hard work in allowing plugins to extend data source manager and browser, so there wasn't really the option for a fully integrated plugin like we have nowdays.

But anyway, that's all historic and I'm +1 to remove for 3.30!

**Comment by giohappy** [comment]
The PR is reeady https://github.com/qgis/QGIS/pull/51584.

Some checks are failing but they don't seem related to the PR.

**Comment by giohappy** [comment]
closed with https://github.com/qgis/QGIS/commit/31d058d1529de572b771405f4366d63f6a7ad8b4
