### ISSUE TITLE
Support AWS Redshift cloud data warehouse in QGIS

### ISSUE THREAD

**Issue by reflectored** [qgis/QGIS-Enhancement-Proposals#272]
# QGIS Enhancement: Support AWS Redshift cloud data warehouse in QGIS

**Date** 2023/05/05

**Author** Alexey Karandashev (@reflectored)

**Contact** lexkar at amazon dot de

**maintainer** @reflectored

**Version** QGIS 3.X

# Summary

[Amazon Redshift](https://docs.aws.amazon.com/redshift/latest/mgmt/welcome.html) is a fully managed, petabyte-scale data warehouse service in the cloud that supports spatial types and functions defined by [OGC Simple Feature Access Standard](https://portal.ogc.org/files/?artifact_id=25355).  AWS Redshift is available as a [free trial](https://aws.amazon.com/redshift/free-trial/).

Redshift enables the customer to analyze (spatial) data across warehouses, operational databases and data lakes, as well as creating and deploying machine learning models. Redshift customers that would like to visualize and work with the sheer amount of the data using QGIS currently require additional intermediate steps to visualize a limited amount of the data in QGIS.

We would like to provide the QGIS Redshift support to our current and future customers. QGIS exposure to Redshift customers will bring new users to QGIS.

## Proposed Solution

We would like to add a new provider for AWS Redshift to QGIS. I have prepared a [pull request](https://github.com/qgis/QGIS/pull/53018) for that.

I have looked into providing AWS Redshift support as a plugin. AWS Redshift driver requires a deeper integration, equivalent to other database providers in QGIS e.g. PostGIS, to achieve the same level of experience for our customers.

AWS is willing to provide support, AWS credits (for the CI Redshift provider tests) and everything that is necessary.

### Affected Files

See the [PR](https://github.com/qgis/QGIS/pull/53018) for a list of files.

## Backwards Compatibility

I don't expect any backward compatibility issues.

**Comment by nyalldawson** [comment]
In the light of https://github.com/OSGeo/gdal/pull/8238, I would be very reluctant to see this merged 👎

@reflectored if you want open source software to support Amazon services, it might be a good idea to first push Amazon to support open source software...

**Comment by haubourg** [comment]
In the light of the previous experiences with proprietary and big vendors, where maintainers were forces to assume the maintenance and technical debt , I second Nyall's point of view.
 Please raise upstream in your organization that we need official and financial support to QGIS's project to have  our maintainers able to review this work.
Don't get me wrong, there is no anger. It is all about sustainability for us.

**Comment by reflectored** [comment]
@haubourg I understand your concern of ownership of the AWS Redshift provider.

AWS Redshift is officially committed to maintain the driver, I'm the current owner of the driver in the team. 

Moreover, as me and @nyalldawson discussed previously [here](https://github.com/qgis/QGIS/pull/53018#issuecomment-1539891290), I committed to refactoring the existing PostgreSQL driver while eliminating existing technical debt ([#1](https://github.com/qgis/QGIS/pull/52434) [#2](https://github.com/qgis/QGIS/pull/53307#pullrequestreview-1455425905) [#3](https://github.com/qgis/QGIS/pull/53307#issuecomment-1643522365)). These and further contributions to the PostgreSQL driver manifest my commitment to the AWS Redshift driver.

In addition, the AWS Redshift provider build and tests, similarly to PostgreSQL, can be turned off by a simple flag in CMake. The reward of attracting many new users to QGIS, who personally voiced their demand for an AWS Redshift driver to me, outweighs the low risk of the driver's abandonment.

Regarding the financial support, I kindly ask you to elaborate on that subject in private, please send me an email to lexkar@amazon.de.

**Comment by octave-ati** [comment]
Any news on this? This is for sure something that my company would be interested in using

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
