### ISSUE TITLE
"Select all objects" used with a filter in the Attribute table causes accidents with the multi edit tool or "Open Field Calculator"

### ISSUE THREAD

**Issue by PeterZamudio** [qgis/QGIS-Enhancement-Proposals#274]
# QGIS Enhancement: Selecting all objects in the Attribute table with Ctrl A

**Date** 2023/07/27

**Author** Peter Zamudio

**Version** QGIS 3.30.1

# Summary
When I set a filter in a Attribute table I have a reduced number of data sets. When I then press Ctrl A, not only the filtered data sets are selected but all the data sets from the whole table. We believe that this is wrong and it has already caused accidents amongst our workers. Also the select all objects button also selects the whole table and not just the filtered sets. Also previously selected objects stay selected in the background out of sight. Setting a filter should automatically unselect all data sets not in the filter and "select all objects" should only be able to select filtered objects. As it is with QGIS at the moment accidents will happen. Data will be changed with the multi edit tool or in the "Open Field Calculator" without the operator knowing what he has done. Or even worse data will be deleted.

I think it would be small changes to QGIS but a very very important.

## My Section

(optional) Insert custom sections wherever needed

## Proposed Solution
Setting a filter should automatically unselect all data sets not in the filter and "select all objects" should only be able to select filtered objects. Or of course all when no filter is set.

## Backwards Compatibility
none

## Votes

(required)

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
