### ISSUE TITLE
GSSAPI authentication not supported

### ISSUE THREAD

**Issue by pmbeau** [qgis/QGIS-Enhancement-Proposals#276]
# QGIS Enhancement: GSSAPI authentication not supported

**Date** 2023/10/12

**Author** Pierre Beau (@pmbeau)

**Contact** 

**maintainer** @pmbeau

**Version** QGIS 3.26

# Summary

I work on MacOS Ventura 13.2.
I try to add a PostGIS layer. The PostgreSQL db is on a distant server with Kerberos authentication.
I can already make it work with psql. I had to recompile PostgreSQL with --with-gssapi option.
When I try to connect to the PostgreSQL db with QGIS I have a popup asking for id and password and a message below saying 'GSSAPI authentication not supported'.
I noticed that when I do :
nm -g /Applications/QGIS.app/Contents/MacOS/lib/libpq.5.12.dylib | grep -i gss
I don't have all the symbols that I have when I do the same with my own compiled libpq.
Is the libpq in QGIS not compiled with the --with-gssapi option ?
If so is it possible to compile QGIS with this option ?

## My Section

(optional) Insert custom sections wherever needed

## Proposed Solution

(required)

### Example(s)

(optional)

### Affected Files

(required if applicable)

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

**(required)**

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by NathanW2** [comment]
Hey @pmbeau I think you have posted this in the wrong place.  Best to open the same ticket over at: https://github.com/qgis/QGIS/issues
