### ISSUE TITLE
QEP 28: Processing UI/UX Improvements

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS-Enhancement-Proposals#28]
# 
# QGIS Enhancement 28: Processing UI/UX Improvements

**Date** 2015/10/23
**Author** Victor Olaya
**Contact** volayaf at gmail dot com

**Last Edited** 2015/11/07
**Status**  Draft
**Version** QGIS 2.14
## Summary

This QEP proposes improvements in the Processing UI to make it more intuitive and less confusing for users 
## Rationale

Processing is a complex tool and it features a large number of elements. This can be indimidating for some users and rather confusing.

To avoid this, a simplified interface was proposed, in which algorithm providers are not shown, and a single "Geoalgorithms" category is added to the toolbox. Not all algorithms are added under that group, but just a selected group of them, and certain algorithms are renamed. 

This has proven to be a bad solution. Users are more confused, and when they find out that some algorithms are in the advanced mode but not in the simplified one, they report that as a bug. Mantaining the simplified interface is also a concern, since sometimes new algorithms are added but the corresponding entry for the simplified version is not added. That causes the algorithm to not be available in the simplified interface.

Additional problems have been reported, such as the lack of help. This QEP proposes some simple enhancements that might help aliviate that. 

Overall, the idea is to make Processing easier to understand. This QEP does not include any new analytical feature or similar improvement.
## Proposed Change

The following changes are proposed:
- Eliminate the simplified interface. Instead, the normal interface will be displayed all the time. To make it more friendly, only the "QGIS algorithms" will be enabled by default. A tip box on top of the toolbox will be added, telling first-time users that they can add more algorithms by enabling additional plugins.

When a search is performed and there are algorithms in disabled providers that match the search string, the user will be informed with a panel, and he will have the option of showing them

![1](https://cloud.githubusercontent.com/assets/2101651/11014572/1abef2b2-853d-11e5-8731-983a91041d93.png)

Disabled plugins can be enabled by just clicking on the Activate link.

![2](https://cloud.githubusercontent.com/assets/2101651/11014584/5302dc38-853d-11e5-81a2-efdd573fad1a.png)

This means that disabling a provider is now only a toolbox display option. Providers are always available, which will avoid errors when loading a model that contains an algorithm form a disabled provider (that failed before but will work fine now)
- Add a small help panel to the algorithm dialog. Currently, the algorithm panel has a help tab. This has two problems: the first one is that help is not seen inmediately after opening the dialog. The second, and most important one, is that the help is lacking for most algorithms, and a help template with parameter names is shown instead.
  
  Writing help files for all algorithms is a very long task, and we have not been succesful at it. It looks like full description of algorithms will not be available anytime soon. Instead of waiting for that and maintaining the help tab for a detailed algorithm content, a smaller panel is proposed. It would be placed in the side of the algorithm dialog, and it would display a short description of the algorithm. Having such a description for most algorithms (or at least for the ones in the "QGIS algorithms" group) is much more realistic and feasible. For those algorithms that have a full help file (for instance, GRASS algorithm, which have the original GRASS docs), the Help tab will be shown like it's done now, but this tab will be removed in case there is no help

See the picture below for an example

![image](https://cloud.githubusercontent.com/assets/381660/10785927/e2bae7cc-7db2-11e5-83e4-85e25e510f6d.png)

Short description are written in YAML format, like in this file:

https://github.com/volaya/QGIS/blob/ux_improvements/python/plugins/processing/algs/help/qgis.yaml

Adding more descriptions is just a matter of dropping a yaml file with a dictionary in that help folder, where keys are the algorithm console names and values are the short descriptions of the algorithms.
## Backwards Compatibility

Since the change is only cosmetic, it wouldn't have any effect on analysis features themselves, and would not break models or scripts from previous versions
## Prototype

An implementation of the above ideas can be found in this branch

https://github.com/volaya/QGIS/tree/ux_improvements

**Comment by anitagraser** [comment]
> For those algorithms that have a full help file, a "more info" link can be provided, which would open the corresponding page in the QGIS documentation.

For users with slow internet connections, it would be preferable to have the help directly in the application, just like we currently have for functions in the expression builder.

**Comment by pcav** [comment]
Agreed; please do not forget people *without* a connection, or those who pay by the traffic.

**Comment by anitagraser** [comment]
One idea was to convert the existing documentation in a format that Processing can display in the help doc and ship these help files with the install. It was also noted that there needs to be a way to localize the help texts.

**Comment by pcav** [comment]
I believe existing help (e.g. grass, gdal, otb) cannot realistically be rewritten, and should absolutely not be lost.

**Comment by volaya** [comment]
I have updated the proposal to include some of the comments and suggestions that people made. Also, there is a link to an implementatino of these ideas, in case anyone wants to test

If you try, notice that the PyYaml library is now needed and is not shipped with QGIS. It will have to be installed manually. If this functionality is finally added to Processing, we will have  to ship it with QGIS as a new dependency

**Comment by anitagraser** [comment]
What do you think about the following scenario:
Processing now suggests that I could activate the GRASS7 provider even though GRASS7 is neither configured nor installed on my system. Is there a way to check which providers "can" be activated?

**Comment by volaya** [comment]
Providers should be able to know if their dependencies are ready. To avoid doing all those checks in advance,(which might delay QGIS startup), i think processing should propose activating all providers that match the search, but then, when activating them, verify that dependencies are in place and, if not, open the config dialog.

What do you think of this?

**Comment by anitagraser** [comment]
That would be ok. I'm thinking if we need a way to let the user decide that a certain provider shouldn't be suggested anymore because s/he will/can not install it.

**Comment by volaya** [comment]
Implemented a first version of this behaviour. Thanks for the advice.

Any idea about how to move this QEP forward?. Being a UX/UI thing, I think it will benefit from some user feedback...

**Comment by NathanW2** [comment]
Well you are the owner of this area so maybe let's just have someone else
review the idea.

It's a +1 from me. Others?

**Comment by volaya** [comment]
I would say @alexbruy is also "owner" of the Processing area, so at least I guess we need his approval to make this change.

**Comment by alexbruy** [comment]
+1 Looks good for me.

**Comment by NathanW2** [comment]
Accepted.

I will update with the details a bit later

**Comment by volaya** [comment]
@NathanW2 Thanks! Let me know if I need to do anything else

**Comment by volaya** [comment]
Just made a PR with this: 

https://github.com/qgis/QGIS/pull/2546

**Comment by SebDieBln** [comment]
It's only a minor issue but can we avoid linking the word _here_?
This is problem widely seen on web pages these days and I think QGIS should be a shining example to everyone of how to do it right.
See the [W3C article](http://www.w3.org/QA/Tips/noClickHere) on this topic (or [click here](http://www.w3.org/QA/Tips/noClickHere) :wink:).

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
