### ISSUE TITLE
QGIS Enhancement: Allow a simple way to refresh external datasets manually

### ISSUE THREAD

**Issue by EwenH** [qgis/QGIS-Enhancement-Proposals#282]
# QGIS Enhancement: Allow a simple way to refresh external datasets manually

**Date** 2022/02/24

**Author** Ewen Hill @EwenH

**Contact** first name dot last name @ gmail etc

**maintainer** 

**Version** QGIS 3.34

# Summary

With any external web based dataset where the user has created a layer using http/s, I would like to request a refresh option on a right hand mouse click on layer to provide a "refresh layer" menu entry. This would allow novice users to easily requery datasets to be refreshed easily. This is not a big request and probably does not deserve a QGIS Enhancement so apologies if this is the case.

## Proposed Solution

1. When the RH mouse click on a layer is activated on an external web based layer, a new entry is added within the dynamic menu
- --------------
- ** Refresh layer **
- Duplicate layer
- Delete layer 
- --------------

2. Clear any local cache and 
3. Send a pull request to refresh the layer
4. Re-render the layer
5. Notify the user of the update via the background notification system popup.

### Example(s)

An example is a geojson layer from an external http/s source that shows wildfire burnt areas from line scans. I would to be able to allow users to requery this data set easily once users are notified of an update without the need to add a button or code or to restart QGIS. 

### Affected Files

tbc

## Further Considerations/Improvements

Whilst this could be extended in complexity, this should assist most use cases and does not further enhancements initially. The only other consideration is to move "change data source..." menu item to the section to just under the new refresh layer to have this all in one place.

## Backwards Compatibility

** not applicable **

## Votes

(required)

**Comment by gioman** [comment]
> . This is not a big request and probably does not deserve a QGIS Enhancement so apologies if this is the case

@EwenH yes, probably this is better suited for a normal enhancement request. QEP are usually accompanied by technical details on how is proposed to achieve the enhancement and also often are backed by someone that has interest in having things done.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
