### ISSUE TITLE
QGIS Enhancement: Authentication system revision (v1.1)

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#289]
# QGIS Enhancement: Authentication system revision (v1.1)

**Date** 2024/03/14

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall.dawson@gmail.com

**Version** QGIS 3.X

# Current situation

QGIS has an inbuilt secure store for user secrets, known as the "Authentication" system. The authentication framework is designed where secrets are stored in an encrypted sqlite database within the user's QGIS profile.

This database must be decrypted via a "master password" before secrets can either be read or stored in it by QGIS core or plugins. On some systems (linux, Windows) there is support for storing this master password within the user's operating system keychain/wallet, so that the user does not need to re-enter it when starting a new QGIS session. (Wallet storage is NOT currently available on Macos without user configuration tweaks, due to lack of notarization on the QGIS install. See https://github.com/qgis/QGIS/issues/46175).

# Summary

This proposal is a companion to https://github.com/qgis/QGIS-Enhancement-Proposals/issues/278 -- in that proposal I described several incremental enhancements to the QGIS authentication framework, but the consensus from that proposal was that further research is required prior to making any changes.

Accordingly, this grant application involves a deeper research effort into the changes proposed in https://github.com/qgis/QGIS-Enhancement-Proposals/issues/278, and, **ONLY if suitable**, implementation of those proposals.

Please see further details and in depth discussion in https://github.com/qgis/QGIS-Enhancement-Proposals/issues/278

This proposal is a joint proposal with @elpaso to leverage a wider set of expertise.

Note that I am deliberately **not** linking https://github.com/qgis/QGIS-Enhancement-Proposals/issues/278 directly with the grant request, as we are NOT proposing https://github.com/qgis/QGIS-Enhancement-Proposals/issues/278 as the final outcome of the grant. Rather, the changes in https://github.com/qgis/QGIS-Enhancement-Proposals/issues/278 will only be implemented during the grant if they are deemed to be **suitable** and **safe**. If not, then the changes proposed in https://github.com/qgis/QGIS-Enhancement-Proposals/issues/278 will not be implemented (or may be only partly implemented).

**Comment by troopa81** [comment]
Would the [proposal](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/278#issuecomment-1814059821) to abstract credential storage from @elpaso be studied or is it beyond the scope ?

**Comment by anitagraser** [comment]
Thank you for submitting your proposal to the [2024 QGIS Grant Programme](https://github.com/qgis/PSC/issues/60). The 2 week discussion period starts today. At the end of the discussion, the proposal author has to provide a 3-line pitch of their proposal for the voter information material. (For an example from last year check https://github.com/qgis/PSC/issues/58#issuecomment-1567892412)

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.

**Comment by anitagraser** [comment]
@nyalldawson as far as I can tell, this grant project has not been finalized yet. Is that correct?

**Comment by nyalldawson** [comment]
@anitagraser that's correct -- I'm out of the office for another week and a bit, I'll follow up after that!

**Comment by anitagraser** [comment]
@nyalldawson Hi Nyall. I hope you had a good well-deserved break. Any news regarding this grant project?

**Comment by nyalldawson** [comment]
@anitagraser nearly there! I've reworked the pull requests (https://github.com/qgis/QGIS/pull/60441, https://github.com/qgis/QGIS/pull/55144, https://github.com/qgis/QGIS/pull/55227 ) based on discussions with @elpaso, so now it's just waiting on review + approval. 

Should hopefully all be finalised before the end of week 🤞

**Comment by nyalldawson** [comment]
@anitagraser ok, all finalized now, and I've sent a report to the PSC mailing list
