### ISSUE TITLE
Improve UX of Raster Legend in the QGIS Layers Panel

### ISSUE THREAD

**Issue by OSHistory** [qgis/QGIS-Enhancement-Proposals#297]
# QGIS Enhancement: Improve UX of Raster Legend in the QGIS Layers Panel

**Date** 2024/06/07

**Author** Niklas Alt (@oshistory)

**Contact** 

**Version** QGIS 3.34 / QGIS 3.36

# Summary

A few versions back QGIS has started to expand raster files with a legend, once they are added to the layer-panel. We are working mostly with georeferenced historical maps, so for the most part the maps are simple RGB files with transparency. And often we add dozens of maps which make up a city. Leading to long lists of expanded legends informing about the fact that all maps are made up of RGBA color bands.

Additionaly we are relying on the opacity slider, which can be added to the layer tree, allowing for a convenient
way to control the opacity of the added maps. However the slider is only visible when the map is expanded in the layer-panel.

I have posted a while back on mastodon and have added some images for illustrative purposes:

https://fedihum.org/@oshistory/111821429135997460

![0e94cb033fe70ce2](https://github.com/qgis/QGIS/assets/9952252/dfd34578-3979-4e58-8c4d-c6f92e8e84e9)

## Proposed Solution

  - new raster layers are collapsed by default (users who need to inspect the legend can toggle it)
  - users can decided if they want the legend to be displayed. This could for instance be set within the Legend Tab of the Layer Properties panel. In fact, there already is an option to use a placeholder, maybe a simple boolean checkbox could serve as a graphical control item 
![0e94cb033fe70ce2](https://github.com/qgis/QGIS/assets/9952252/b0c97918-7351-4fc6-86c8-233b5a15b776)
  - maybe the legend and other UI Elements (like the mentioned opacity slider) could be seperated.

## Deliverables

*(required for QGIS grant submissions)*

### Example(s)

*(optional)*

### Affected Files

*(optional)*

## Risks

*(required)*

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

**(required if applicable)**

## Issue Tracking ID(s)

*(optional)*

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
