### ISSUE TITLE
Point cloud editing

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS-Enhancement-Proposals#309]
# QGIS Enhancement: Point cloud editing

**Date** 2024/12/03

**Author** Martin Dobias (@wonder-sk)

**Contact** wonder dot sk at gmail dot com

**Version** QGIS 3.42 and later

# Summary

Point cloud support in QGIS started with viewing capabilities (in QGIS 3.18), later we have added point cloud processing capabilities (in QGIS 3.32), and now the time should be ripe to add basic point cloud editing capabilities :smile:

Editing of point clouds is quite different from the usual vector layer editing. Most of the time, point clouds are edited in bulk by various processing algorithms due to the large quantity of points. Users sometimes may want to manually edit a point cloud after some initial processing (e.g. clipping, noise filtering, automatic classification) as a part of quality assurance before distributing point clouds or derived products to others. There are two main manual editing tasks that we are going to address:

1. editing of attributes of some points (e.g. Classification)
2. removal of points

The rest of the proposal details how we will implement these operations with interactive GUI in QGIS.

### Assumptions

We are going to do a couple of assumptions for point cloud editing to limit the scope:

- We only support changes of attribute values (most commonly Classification) and removal of points
  - We do NOT support changes to X,Y,Z coordinates of points, as that may require moving points between octree nodes (and re-balancing of nodes) or even reindexing the octree completely (if moving outside of its bounds).
  - This assumption could be removed in future with amendments to the proposal (how to store changes outside of the existing octree)
- We would only support editing of files that were converted to COPC files
  - We convert any non-indexed point cloud file to COPC at the first load, so that should not be an issue
  - In future we could support EPT or even other formats if needed
- We would not support VPCs in the initial implementation
  - But nothing in the proposal blocks addition of VPC support at some point later
- Only local files will be editable (i.e. no remote files)

### Overall editing workflow

Editing should behave similarly to how editing of vector layers and mesh layers works:
1. user first starts editing mode for the layer
2. user repeatedly uses interactive map tools to do modifications to the layer
3. user finishes editing mode, changes are either committed or rolled back

There will be one more caveat to that in point cloud editing - when changes are saved, we will not overwrite the original file. We will only store the changes in a QGIS-specific sidecar file (e.g. `data.copc.qpc` file for `data.copc.laz`) . The reason for this behavior is that saving changes to a COPC file can be very time consuming (e.g. take a couple of minutes), which may be blocking users from working efficiently. Saving to the sidecar file should be fast and so users should be able to save edits at any time. Only once all editing has been done, user may decide to export all changes to a new COPC file (using e.g. layer popup menu in the layer tree).

### Storage of edits

The general idea is that we have three levels of storage of point cloud data:

- **Level 0** - the original COPC (e.g. `data.copc.laz`) file with no changes at all. We had only this level by now.
- **Level 1** - sidecar file (e.g. `data.copc.qpc`) that contains edits already saved in QGIS
  - It would only exist if there are already some changes from a previous editing sessions saved
  - Only stores modified point cloud nodes from the COPC file (each node should typically be around ~50K points). Full content of a node is stored, not just changes.
  - Using a simple sqlite3 database for the data storage
    - Why sqlite3 db? Fast and easy to read/write data, without having to invent a new format. Good support for transactions and can handle multi-user editing (as long as it is not on network drive)
    - Database contains one table (e.g. `updated_nodes`) with the following columns:
      - `d`, `x`, `y`, `z` (all integer) - coordinates of the node in the octree
      - `node_data` (blob) - contains compressed node data with the modifications
- **Level 2** - in-memory editing buffer that contains edits from the current editing session in QGIS
  - It would only exist if the layer is currently in editing mode
  - Like Level 1, it only stores modified point cloud nodes
  - Instead of a database table, we can use in-memory hashtable: key = dxyz, value = node data blob

Access to point cloud data (e.g. when rendering):
- Traverse the octree as before to find nodes of interest (based on the spatial extent and desired resolution)
- For each node, we try to access its data in the following order:
  - use Level 2 (in-memory) if we are in editing mode and we have the node in the hashtable
  - else use Level 1 (on-disk) if we have the sidecar file and the node is in the database
  - else switch back to Level 0 (unmodified COPC file)

### API Additions

`QgsPointCloudLayer`
- `startEditing()` + `commitChanges()` + `rollback()` – like in vector layers
  - `startEditing()` starts editing session (initializes empty Level 2 storage)
  - `commitChanges()` would push changes from Level 2 (in-memory) to Level 1 (on-disk)
  - `rollback()` just clears Level 2 (in-memory)
- `changeAttribute( attributeName, nodeDxyz, map<pointIndex, newValue> )` - modify an attribute for some points in Level 2, does nothing if editing mode is not started
- `deletePoints( nodeDxyz, vector<pointIndex> )` - remove some points in Level 2, does nothing if editing mode is not started

Inner working of the editing API:
- Like with rendering, simply take existing Level 2 or Level 1 or Level 0 node, update contents of the node as asked and store to Level 2. Make sure to invalidate cached nodes for 2D rendering, trigger signal to refresh 2D/3D view

We will have full undo/redo support using map layer's undo stack, like with vector layers. Undo commands to add:
- Change attribute - keeps old and new values of the given attribute
- Add/remove point - keeps full copy of the deleted points to allow their resurrection

### GUI additions - Map tools

Editing of point clouds will be possible from 3D map canvas and from 2D map canvas - the primary focus of the implementation will be on 3D canvas, given that 2D canvas is quite limited when working with point clouds. Tools will be added to the 3D canvas first, and possibly later for 2D canvas as well. We have considered adding editing tools to elevation profile tool as well, but that would not add much value compared to implementation in 3D canvas, while requiring another implementation of the same functionality.

In the production use in other software, point clouds are typically cleaned by picking a small area of interest in 2D canvas, and then using 3D canvas (especially with side view) to edit/remove points. 3D canvas already has functionality to constrain its map extent (by axis aligned rectangle), and in the future this may be further improved by using clipping planes (allowing rotated rectangles).

We propose addition of two methods to pick points for change of attributes or removal:
- using polygon fence - similar to selection by polygon for vector layers (left click to add a point, right click to finish)
- using paintbrush-style tool - user-defined radius around mouse pointer would select points while the left mouse button is pushed

There will be two map tools added:
- change attribute tool - with an additional widget to select 1. attribute to modify, 2. target value, 3. optional filter for source points (e.g. pick only points where classification value is ground)
- delete points tool - with no additional widget (or optionally with filter for source points)

### GUI additions - Saving changes

When a user commits changes in the GUI, they only get saved to Level 1 (on-disk sidecar file). There should be a way in the GUI to see that the COPC file is modified  (e.g. in tooltip in layer tree, indicator on the right side in layer tree, information tab in layer properties), and a way (e.g. popup menu in layer tree) to:
- Save the edits to a new COPC file, or some other PDAL supported format. We will read only unmodified chunks from the original file, and merge with data from modified chunks from Level 1
- Discard all the edits

## Risks

This is a low-risk incremental addition to the point cloud support, not affecting other kinds of map layers, and not affecting point cloud layers that are going to be used in read-only mode.

## Performance Implications

There should be only negligible implications on the rendering speed when editing is enabled. In case of large amounts of manual edits, there may be issues with large consumption of RAM - this could be fixed by asking user to save changes when the number of updated nodes stored in RAM gets too large.

## Backwards Compatibility

There are no backward compatibility issues.

**Comment by nyalldawson** [comment]
@wonder-sk all sounds good to me 👍


One question I have is about how the editing tools will be exposed in a 3d map (since we don't yet have any other editing tools there). Will these just be new toolbar buttons in the 3d map window? Or do you have a different idea?

**Comment by wonder-sk** [comment]
> One question I have is about how the editing tools will be exposed in a 3d map (since we don't yet have any other editing tools there). Will these just be new toolbar buttons in the 3d map window? Or do you have a different idea?

@nyalldawson That's a good question! Initially, those could be just new toolbar buttons (or a single one with drop-down menu for multiple tools), but it would be good to have some plan for the future. For me the ideal solution (ready for future additions) would be to make 3D window a QMainWindow, just like with print layouts... but of course that does not play well with 3D canvas being docked/floating dock widget.

Maybe at some point we should try to look into Blender-style GUI, with possibly multiple viewports side-by-side, each with its own tools etc - 3D views could certainly benefit from it...

**Comment by troopa81** [comment]
I'm wondering about  **Level 1 - side car** file:
- Is it created automatically when we start editing a layer ? 
- Where is it created ? in the user profile ? in the qgz project file ? does the user has to indicate where he wants to store that file ?
- How do you link the copc layer with its side car file ? In the project with the side car full path ?

**Comment by wonder-sk** [comment]
@troopa81 

> Is it created automatically when we start editing a layer ?

Yes!

> Where is it created ? in the user profile ? in the qgz project file ? does the user has to indicate where he wants to store that file ?

It would be created right next to the original COPC file - so if the original file is `/home/martin/data/hello.copc.laz`, then the Level 1 sidecar file would be e.g. `/home/martin/data/hello.copc.qpc`

> How do you link the copc layer with its side car file ? In the project with the side car full path ?

They get linked by transforming the original file name (just using a different file extension with the same basename).

**Comment by rouault** [comment]
Has there been some discussions with PDAL usptream about the side car file? Does it really need to be a QGIS specific thing, or could there be a value of having PDAL itself recognize a side car file with edits, or maybe PDAL upstream wouldn't be too enthusiastic about that?

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
