### ISSUE TITLE
QGIS 3.22.4 Failing to Load in Thin Client

### ISSUE THREAD

**Issue by KobelF** [qgis/QGIS-Enhancement-Proposals#312]
**Date** 2024/12/12

**Version** QGIS 3.22.4

# Summary

QGIS is failing to load for users in windows 10 Vmware session. Usually clearing the thinstall folder fixes it but recently this has stopped working.
I have tried repackaging, but the same error keeps on occurring. It looks like this dll is causing the issue, I have tried giving the user local admin permissions and it seems to be loading. Is it possible to prevent the interaction with this file from the package?
I have looked through the package files and reg settings but can't see anything relating to it.

Here is the error from event viewer:
Faulting application name: QGIS Desktop 3.22.4.exe, version: 0.0.0.0, time stamp: 0x62134a88
Faulting module name: ntdll.dll, version: 10.0.17763.1911, time stamp: 0x0c372913
Exception code: 0xc0000005
Fault offset: 0x000000000000b9eb
Faulting process ID: 0x2ecc
Faulting application start time: 0x01db462b0e39e7d5
Faulting application path: \\domain.co.uk\thinapps\QGIS 3.22.4\bin\QGIS Desktop 3.22.4.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report ID: 6807e42a-3133-447c-98d9-bfc11e9a4298
Faulting package full name: 
Faulting package-relative application ID:

**Comment by gioman** [comment]
@KobelF this must be reported in the bug tracker, not here. Cheers!

**Comment by Gustry** [comment]
> Version QGIS 3.22.4

And this version is very old and not supported anymore by QGIS https://www.qgis.org/resources/roadmap/#release-schedule
