### ISSUE TITLE
add groups for themes

### ISSUE THREAD

**Issue by flosigime** [qgis/QGIS-Enhancement-Proposals#313]
# QGIS Enhancement: Add Groups for themes

**Date** 2024/12/17

**Author** Flo Sigime (@flosigime)

**Contact** flosigime at rdbb dot fr

**Version** QGIS 3.34

# Summary/Proposed Solution

We frequently use themes in QGIS, especially in archaeology. 
Sometimes, we end up with a very large number of themes, resulting in a lengthy and difficult-to-manage list. 
The idea is to organize these themes in a more streamlined way, grouping them together by subject, similar to how spatial bookmarks are managed.

here an example (but it'is often more)

![Capture d’écran 2024-12-17 113754](https://github.com/user-attachments/assets/480b61b9-585f-47d6-aed9-46f4b06489e4)

## My Section

*(optional)* Insert custom sections wherever needed

## Deliverables

*(required for QGIS grant submissions)*

## Risks

*(required)*

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

**(required if applicable)**

## Issue Tracking ID(s)

*(optional)*

## Votes ##

**Comment by haubourg** [comment]
Hi 
Unless you plan to implement this yourself and change significant part of QGIS behavior, this looks more like a feature request than a QEP. 
You can open an issue in QGIS/QGIS bugtracker to describe your proposed feature
