### ISSUE TITLE
QEP 34: Improve plot/graphs creation

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS-Enhancement-Proposals#34]
# QGIS Enhancement 34: Improve plot/graphs creation

:Date: 2015/03/19
:Author: Matteo Ghetta
:Contact: matteo.ghetta@gmail.com
:Status:  Draft 
:Version: QGIS 3.0
# . Summary

---

Right now the creation of high level plots and graphs is limited. **Statist** plugin and some **Processing** tools 
(QGIS geoalgorithms, R scripts, shell scrips..) are able to produce some usable plot, but not high level ones.
# . Proposed Change

---

Thanks to Processing one can add R scripts in order to produce high level plots, but it is worth to use some core
python library to create those plots (matplotlib, numpy, scipy...).

This enhancement proposal is for adding and additional menu (also embed it in Processing) so the user can create
high level plots with the attribute table fields.

Plots options:
- standard plots (histogram, scatterplots, pie charts, dnsity plots...)
- add trend lines
- add _value_ lines based on statistical computation of the attribute fields (median, mean, standard deviation...)
- plot custiomization (color, size, title, axes name)
- axes options (logaritm, flip axes..)
- interaction plot - layer (e.g. click on the point of the scatterplot and see the point on the map)
- plot exportation (jpeg, png, svg...)
# . Further Considerations/Improvements

---

It is also worth to include the possibility to visualize the plots in the print layout.

**Comment by NathanW2** [comment]
@ghtmtt

**Comment by dgobbett** [comment]
A key part of the OSGeo discussion 
(http://osgeo-org.1560.x6.nabble.com/graph-and-plots-improvements-td5194130.html#a5194176)
which led to this proposal, related to the Python pandas library. Pandas is a fast and powerful library for working with tabular data. Some examples :

# Read a CSV file into a dataframe
df = pandas.read_csv(self.yieldFile, skipinitialspace=True, nrows=1)

# filter to remove rows containing values in specified columns of the datafram
colNames = ['Latitude', 'Longitude', 'TMG_degrees', 'Speed_har_Avg']
for n in colNames:
    self.df = df[df[n].notnull()]

# calculate a new column over entire dataframe
df['Distance (m)'] = df['Distance (ft)'] * convert_ft_to_m

Hopefully you get the idea. Pandas seems to be growing in popularity, and together with geopandas (which integrates spatial IO) are a librarly of choice. I have used Pandas extensively in some code which I tried to integrate into a QGIS Processing Toolbox script, only to find that Pandas is not installed with QGIS. It would be a very powerful library to add to those that are included with the default distribution.

**Comment by wonder-sk** [comment]
From Qt 5.7 the Qt Charts module will be a part of Qt library and available under GPL - it looks like perfect candidate for all sorts of plotting within QGIS environment...

http://doc.qt.io/QtCharts/

**Comment by ghtmtt** [comment]
Oh yeah! This could be a filed that is worth to study! Thanks Martin

**Comment by ghtmtt** [comment]
What about thinking to include ``plotly``?

[https://plot.ly/python/offline](https://plot.ly/python/offline/)

A few months ago they decided to get open source and in my opinion it would be nice to include all the D3 plot types with the python API. The variety of plots is impressive and also the chance to have them interactive. 

[https://plot.ly/python/](https://plot.ly/python/ )

It seems a little bit tricky that the quickest way to plot is to inject the plot in a python notebook, anyway there are some ways to do that with a *normal* python script and put the result in a html file (and so in a QWebKit?)

**Comment by ghtmtt** [comment]
I think that with the development of the plugin Dataplotly http://plugins.qgis.org/plugins/DataPlotly/ this QEP can be closed

@NathanW2 what do you think?

**Comment by jakimowb** [comment]
I would really like to see the QtCharts library in the standard QGIS installation:

* it's already there, so why not including this "Qt-native" way to create 2D charts?
* GUI developers could use [QAbstractItemModels](https://doc.qt.io/qt-5/qabstractitemmodel.html) to visualite data as charts, like for QTableViews or QTreeViews (link [here](https://doc.qt.io/qt-5/qtcharts-barmodelmapper-example.html))
* it should be much easier to allow for interaction in both directions, e.g. to selecte a chart element ("Line") on screen to select a corresponding QgsFeature in a QgsVectorLayer and vice-versa.

**Comment by haubourg** [comment]
Just for the sake of showing yet another plotting method, @mhugo at Oslandia did a plugin based purely on QGIS map features and symbology to plot time series. though I was suspicious about it at start, it works really well and offers by the way the "sky is the limit" possibilities offered by QGIS symbology. 
See code and video here: 

https://github.com/Oslandia/qgis_well_log 

https://vimeo.com/303279452

of course, it's not a plotting/graph library but this can help in some contexts

**Comment by mhugo** [comment]
Just to complete what @haubourg wrote: the small Python library we made initially focused on "vertical" data series of an important amount of data points (from 100k to 1M) and we are working on extending it to "horizontal" graphs, in order to plot more generic time series data and scatter plots.

At the time, I looked into DataPlotly a bit. It seemed nice and user friendly, but I was skeptical about raw display performances (loading time especially). I do not know if it comes from plotly itself or from DataPlotly and if there are rooms for enhancements.

QtCharts is also a good candidate as pointed here and I think it can correctly handle large datasets (even from Python with some 0-copy trickery)

**Comment by ghtmtt** [comment]
DataPlotly can suffer with superlarge dataset. Basically it is loading all the plotly code (html + js) into a QWebView. 

We are currently running a crowdfunding campaign that will also refactor the code with, hopefully, some improvements.

Plotly itself offers a webgl integration (https://plot.ly/python/line-and-scatter/ and look for `Large Data Sets` section): but not for every plot type.

**Comment by mhugo** [comment]
@ghtmtt Ah good to know, I'll have a closer look, thanks

**Comment by PeterPetrik** [comment]
Can we use (Data)Plotly in C++ QGIS core/gui/app development? It would be maybe worth also to add some support/wrappers to C++ QGIS libraries, so we have single interface for plots for everyone in C++/Python. The implementation of this 'QgsPlot` API can be then based on whatever.

**Comment by ghtmtt** [comment]
Plotly offers different bindings for several different languages, here the official list:

https://plot.ly/graphing-libraries/

actually if one day dataplotly will be in core then we can think to provide C++ wrappers. cc @nyalldawson

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
