### ISSUE TITLE
QEP 38: Inheritable property collections

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS-Enhancement-Proposals#38]
# 
# QGIS Enhancement 38: Property framework

**Date** 2014/11/22
**Author** Nyall Dawson
**Contact** nyall dot dawson at gmail dot com
**Last Edited** 2016/03/19
**Status**  Draft
**Version** QGIS 3.0
## 1. Summary

This QEP concerns a system of managing and evaluating properties for an object. Properties are grouped in collections, and can be overridden in a specified order of precedence by storing them in a "stack" of collections. A specific property from a collection or stack is evaluated by passing a QgsExpressionContext to an evaluate function.

This proposal is being driven by a number of factors:
- to avoid the current multiple duplicate code paths involving storage, retrieval and evaluation of data defined properties and to make it easier to add data defined support to more things (eg diagrams) without incurring even more duplicate code. Currently labeling, symbology and composer all have their own methods for handling data defined properties, which makes maintenance of data defined code very difficult.
- to allow creation of other property types besides the current "data defined" (ie bound to field value or expression result) property, eg time based properties for a future in-built animation framework.
- to avoid the complexity of requiring users to write their own expressions to map values to colors, sizes, etc and apply scaling functions to these, and instead expose these to users in an interactive, flexible way. Think Mapbox studio's approach to zoom level styling:

![coyp4quvmaawdbs](https://cloud.githubusercontent.com/assets/1829991/17850412/6a0f285e-68a0-11e6-8719-cdf74afd061d.jpg)

but available for all property types. Eg data defined values can be set to preset ease in/ease out curves, or manually edited curves through an interactive GUI.
- enable the possibility of having live project wide colors. Ie a color palette could be created in the project properties, and color based properties "bound" to these colors. Altering the color would then automatically update every property which was bound to this preset color. This also brings the possibility of "color themes" for maps, eg binding properties to a predefined color types such as "highlights", "background features", etc, and then interactively changing all these color bound properties by applying a color theme to the project.
- to allow a system of inherited and overridden properties. Eg QGIS default label font overridden by a project default font and finally overriden by label font setting. The proposed composer rewrite (layouts work) would use this property inheritance to bind layout item properties to a dynamic template. Changes in the template would be reflected in all linked layouts, but individual items could overwrite the inherited properties as required. Layout item properties could then be set globally (eg, font size), per project (eg font family), via a "master template" and finally individually per layout item.
- the labelling engine has a need for predefined label styles. Label properties could be set globally, per project, via a predefined style, or overriden for a particular layer.

This proposal consists of both a framework for collecting, retrieving and evaluating properties, a GUI based method for transforming properties to colors/sizes/etc, and a GUI widget for controlling them.
## 2. Proposed Technical Solution
- Create an abstract base class "QgsAbstractProperty". Abstract properties have pure virtual methods for readXml, writeXml, creating and cloning, evaluating the property value against an expression context, and for returning any fields referenced by the property. The base class also implements setting a property as "active" or not.
- Classes derived from QgsAbstractProperty are QgsStaticProperty (a single unchanging value), QgsFieldBasedProperty (returns the value from the corresponding field), QgsExpressionBasedProperty (evaluates an expression and returns the result). In future a QgsTimeBasedProperty could also be added to handle calculation of a feature's "age" from the current map canvas time, in days/weeks/months/etc.
- A class "QgsPropertyCollection" would be created, which stores grouped map of multiple QgsAbstractProperty objects, each referenced by a integer key value. Properties within a collection are referenced by an integer key to avoid the cost of string creation and comparisons which would be required if a string key was used. The intended use case is that a context specific enum is cast to int and used for the key value (eg `QgsDiagramLayerSettings::BackgroundColor`). Collections have methods for storing/retrieving from XML, retrieving individual properties, returning a list of all fields referenced by active properties from the collection, and evaluating a contained property against a supplied expression context. 
- A class "QgsPropertyCollectionStack" which stores an ordered list of QgsPropertyCollections. QgsPropertyCollectionStack has a method for retrieving the value from the first QgsPropertyCollection for which a particular property is active.
## Transformers

QgsAbstractProperty objects may also have an optional QgsPropertyTransformer object set. QgsPropertyTransformer is an abstract base class for objects which transform the calculated value of a property. Initial implementations for transformers would include those which map a value into a scaled size (QgsSizeScaleTransformer) or color from a gradient (QgsColorRampTransformer).

The intention with transformers is to separate the calculation of a source value from a property (which may be taken from a static value, field, expression result, time based property, etc) from the calculations required to turn this value into a usable color, size, or numeric result.
## GUI Changes
- The existing QgsDataDefinedButton class would be reworked to instead rely on QgsProperties instead of QgsDataDefined objects. In addition to the current options available from the data defined button, the new widget's drop down menu would also show all available QgsPropertyCollections for which the property can be inherited. For instance, for layouts, this would show "Disabled", "From master template", "From project" and "QGIS Default". For labelling, this would show "Disabled", "From style",  "From project" and "QGIS Default". 

The existing "size assistant" option would be rewritten to use properties and transformers. The dialog will be split into two sections, the top section would show the property's value source (ie, a dropdown with choice of fields and expression entry, and possibly in future a gui for calculating a feature's age from the canvas time property), and spin boxes for the expected min and max value calculated by the source (with a button to auto-calculate these).

The lower half of the dialog would show the transformer settings corresponding to what the property is being used for. Eg, for a property setting a size value, the existing options from the size assistant will be shown (min/max size, scale method, preview frame). For a property corresponding to a color, the transformer settings will include selection of a color ramp, color corresponding to null values, and an option to reverse the color ramp. Numeric properties (eg distances, offset values, etc) would show a simple numeric assistant with min/max output values.

_Follow up work would involve adding a checkbox and collapsed group box between the value source section of the assistant and the transformer settings section for "apply curves". Checking and expanding this group would show a photoshop style interactive "curves" graph, which controls how input values are mapped to output values. The curves group would also include a combobox allowing for selection of presets like "ease in", "ease out", etc._
## 3. Examples

The following examples show how properties would be set for a vector layer's (vl) diagrams.

Setting a static override for a the diagram background color property:

```
vl.diagramLayerSettings().properties().setProperty(QgsDiagramLayerSettings.BackgroundColor, '#ff0000')
```

Setting an expression based outline width:

```
vl.diagramLayerSettings().properties().setProperty(QgsDiagramLayerSettings.OutlineWidth, QgsExpressionBasedProperty('rand(0,3)',True))
```

Field based outline width:

```
vl.diagramLayerSettings().properties().setProperty(QgsDiagramLayerSettings.OutlineWidth, QgsFieldBasedProperty('width_field',True))
```

Here's an example of a transformer used on a property. This will transform the value in the 'passengers' field (with values ranging from 0 to 10000) to an interpolated background color from the 'YlOrRd' ramp:

```
p=QgsFieldBasedProperty('passengers',True)
p.setTransformer( QgsColorRampTransformer(0, 10000, QgsStyleV2.defaultStyle().colorRamp('YlOrRd') ) )
vl.diagramLayerSettings().properties().setProperty(QgsDiagramLayerSettings.BackgroundColor,p)
```
## 4. Deprecations

The property system would deprecate the existing QgsDataDefined, QgsDataDefinedButton, QgsScaleExpression and QgsDataDefinedAssistant classes. Initially it would be implemented for diagrams, symbology, and labeling. Composer would adopt the properties framework when for the future "layouts" rework.
## 5. Voting History

(required)

**Comment by nyalldawson** [comment]
Work in progress PR here https://github.com/qgis/QGIS/pull/2857

**Comment by nyalldawson** [comment]
Update to reflect newest design

**Comment by timlinux** [comment]
Hi @nyalldawson this looks like a nice update. Personally I am not a fan of having ``V2`` classnames - since we are going to do an API cleanup for 3.0 it would be nice also to go into 3.0 with no legacy stuff and let v2 be dropped out of class names. There are two reasons I am not a fan:

1. We accumulate cruft in the code base over time that has to be maintained
1. Its very confusing as an API user trying to figure out which  of a bunch of similarly named classes we should be using.
