### ISSUE TITLE
QEP 46: Label path

### ISSUE THREAD

**Issue by mhugo** [qgis/QGIS-Enhancement-Proposals#46]
# 
# QGIS Enhancement 46: Labeling path

**Date** October 2015
**Author** Hugo Mercier
**Contact** hugo dot mercier at oslandia dot com
**Last Edited** 
**Status**  
**Version**
## Summary

A new labeling option is proposed for addition here. It allows two things :
- an option to smooth or simplify geometries on the fly before doing curved labels.
- to use a user-defined linear path for the drawing of a label. A new data field would be necessary to store that path. That geometry field will require a new datadefined widget in labeling properties. 

A user-defined path can be seen as an additional geometry on a layer, where the underlying model supports only one "geometry column" (see https://github.com/qgis/qgis3.0_api/issues/21 )
## Proposed solution

We propose the add a way for the user to use a different geometry object as support for the "curved" placement of a label.

The current version of QGIS allows to display labels along the linestring features in a "curved" manner.

![Curved labeling](https://raw.githubusercontent.com/mhugo/QGIS-Enhancement-Proposals/adv_labeling/curved_labeling.png)

However for linestrings defined with lots of control points (such as waterways) or with high curvatures, displaying correct labels can be either anaesthetic or very slow.

This is where using a path slightly different from the feature's geometry could be useful. For instance using a simplified version of the linestring could lead to a label faster to display or with smaller curvatures.

We then propose to allow the "curved" placement to use an arbitrary geometry, through a data-defined "label path" property. The data-defined property could point to a user-defined column or to an expression.

We also propose to add simplification / smoothing functions in core expression functions for that purpose.

This option for placement along a user-defined path would also be available for other types of features, like points and polygons.
## Core Changes

A new data-defined labeling property of type QgsGeometry is added for the definition of the label path ("labeling/dataDefined/labelPath").

This data-defined property could be of type string or QgsGeometry. String values will be considered as the string representation of a WKB.

QgsPalLayerSettings::registerFeature will be modified in consequence: if this new property is set and curved placement is enabled, it will be used as a support.

New simplification functions will be available in expressions. 
- simplify( geometry, tolerance ): Douglas Peucker
- (optional) visvalingam( geometry, tolerance): [Visvalingam’s algorithm](https://hydra.hull.ac.uk/assets/hull:8343/content)
- (optional) bendSimplify( geometry, tolerance): [Wang Müller's algorithm](http://web.cs.sunyit.edu/~poissad/projects/Curve/pdf/1998.pdf)

New smoothing functions will be available in expressions:
- smooth(geometry, iterations) : Chaikin subdivision algorithm (will smooth the curve, but increase the number of points)
## GUI Changes

A new tool will be available in the labeling toolbox for point, linestring and polygon layers. This tool will allow to draw a user-defined label path. It will be enabled only if the label path property is defined from an editable field (not an expression).

A checkbox will allow to automatically enable on the fly smoothing for curved labels placement (shortcut to the definition of an expression-based label path)
## Performance Implications

For the use case presented above, where the user wants to use an expression like "simplify($geometry)" as a label path, computing the simplification of the feature's geometry each time the label is drawn could be time consuming.

In this case, using an additional geometry field where the simplified geometry is stored (or multiple geometry fields for multiple scales) will be needed.
Providers supporting multiple geometry columns (PostGIS, Spatialite) will be modified to return QgsGeometry instead of WKT strings.

Moreover simplification / smoothing of a line needs to be done only on the visible part of the geometry on the current extent. Simplficiation / smoothing functions should be aware of the current visible extent for possible optimizations.
## Test Coverage

Unit tests will be added to the core part to ensure the label path feature works correctly.

**Comment by haubourg** [comment]
Hi, if I understand well, that QEP is only for line layers. I must point that currently curved label fails when curvature is too high at a given zoom level. 
Improving current curved labeling to have it work fast and readable dynamically would not only require a simplify function, but also a smoothing one. Suppressing node could generate high angles. preserving smooth angles and long enough paths to allow labeling engine to compute a label needs a fairly advanced (and maybe iterative) smooth-simplify algorithm.

**Comment by mhugo** [comment]
Hi. Actually we could easily extend this to any kind of layers, not only line layers.

About this and the simplification / smoothing function, here are two comments from @nyalldawson on the PR part:


A core change which would be required to accompany this would be to allow access to other geometry columns defined within a layer. Eg for many data formats (Postgis, spatialite) it's possible to have more than one geometry column. These additional geometries are currently just converted to wkb representations and displayed as text fields by QGIS (consequently bogging down use of the attribute table for layers with complex secondary geometries). Support should be added so that additional geometry columns are stored as QgsGeometry objects, and then the label path could be directly bound to the secondary geometry column without the expense of going through the expression engine. This would also allow for the following use case:

* Polygon layer with a secondary line geometry attribute
* Data defined label path is bound to line geometry
* User can add the layer a second time to QGIS, using the line geometry as the main geometry column
* User can then edit the line geometries using the existing digitizing tools, and the labels for the polygon layer will instantly update to reflect any changes to paths.



I've played with this a bit in the past and found that the default Douglas–Peucker simplification method doesn't help at all for curved labeling, as the sharp corners in the linear geometry are preserved. From my tests a better approach is:

* Use Visvalingam’s algorithm to simplify, as that removes sharp corners whilst preserving the overall shape of a line
* Combine smoothing with simplification (see http://qgis.org/api/classQgsGeometry.html#ab2f6d720b51f96686f3152a6dabfe201 ). Note that smoothing increases the number of vertices in a geometry, so it needs to be done after simplifying the geometry.
* Even better would be a "bend simplify" based on the algorithm described in http://web.cs.sunyit.edu/~poissad/projects/Curve/pdf/1998.pdf . It's a more effective method of maintaining the general shape of lines will removing small fluctuations.

**Comment by mhugo** [comment]
@nyalldawson I paste here your original comment about the obstacle geometry:

> Note that it's not sufficient to just use the alternative geometry when registering a label. Instead, labels needs to be able to register an optional "obstacle geometry" which can differ from the feature geometry. Otherwise the simplified/smoothed line feature would be used for the obstacle detection too, and could result on labels being placed over the rendered symbol for a line.

Without this obstacle geometry, it could give something like that: (dotted line is the simplified version)

![label_path_overlap](https://cloud.githubusercontent.com/assets/1618556/11037631/fb862884-86fe-11e5-9441-6c5d6f074a4f.png)

So ok to add an option to consider the original geometry as an obstacle. So that the placement algorithm will do its best to move the label out of the "spike" here.
But it should not avoid the label to overlap the original lines, in case no room is available. Is this how the obstacle works in the label engine ?

Then you were talking (on gitter) about a way to use visvalingram (or something else) only on one "side" of the label. I am not sure to follow. Could you develop ?

**Comment by SrNetoChan** [comment]
Not sure if this is the right place to post this, but maybe it could be though in this QEP as well.

Currently, when a user uses the label move tool (with data defined properties set), curved labels are transformed in horizontal ones. It would be nice, if the user could instead move the label along the path. For that, the Label's starting position would need to be saved relative to the path itself, maybe using a distance to the start point in layer's units, or, even better, a relative position in the line (from 0.0 to 1.0). This would be possible to do with the original path or user simplified one.

My appologies if this is not the right place to discuss this feature. If so, I will simply create a feature request.

**Comment by mhugo** [comment]
@SrNetoChan Seems and interesting feature. It is somehow related to the label path feature, so I'll try to add it here. Thanks!

**Comment by nyalldawson** [comment]
@mhugo Note that QGIS master now supports registering a different geometry to act as an obstacle from the geometry used for generating candidates. See:

https://github.com/qgis/QGIS/commit/9cc10e2a21a6d9fc6ea244b227c3e932951c9717
https://github.com/qgis/QGIS/commit/55ead85382b43ed2fe6bae1296201788002644d0
and https://github.com/qgis/QGIS/commit/6b0e7de9e215139d0c3395568dac1a2473635816

This should make it possible to use the original line geometry as an obstacle for other labels, while using a simplified/smoothed/... geometry for label candidate generation.

**Comment by mhugo** [comment]
@nyalldawson Great, thanks !

**Comment by mhugo** [comment]
Small updates of the text:
- point to https://github.com/qgis/qgis3.0_api/issues/21
- notice that simplification / smoothing functions could be optimized based on the current visible extent

**Comment by mhugo** [comment]
@SrNetoChan Hi. After thinking about it, I think your request is not related. You would need a way to manually fix the position of the label relative to the start of the line and have it as a data-defined property with corresponding tools.

**Comment by SrNetoChan** [comment]
Ok. Thanks for considering it.

**Comment by mhugo** [comment]
Apart from the simplification / smoothing function details which may be determined afterwards, I think the description is enough. If no other objection, @NathanW2 could you tag as final draft ?

**Comment by nyalldawson** [comment]
I'm +1 on this QEP. @NathanW2 do we need more +1s to accept this?

**Comment by timlinux** [comment]
:+1: from me too!

**Comment by mhugo** [comment]
@NathanW2 could it be tagged as accepted ?

**Comment by mhugo** [comment]
Just a slight update to mention the Chaikin algorithm as a smoothing algorithm.
I think we have two +1 here ... @NathanW2 could it be tagged as accepted ?

**Comment by NathanW2** [comment]
Sure thing.

**Comment by mhugo** [comment]
Thanks!

**Comment by fritsvanveen** [comment]
![2016-07-15 10_04_30-qgis fd88d91 - top10nl](https://cloud.githubusercontent.com/assets/20473145/16868227/bb80a642-4a76-11e6-9ce9-c882527450bd.png)
![2016-07-15 10_04_44-qgis fd88d91 - top10nl](https://cloud.githubusercontent.com/assets/20473145/16868226/bb7cac5e-4a76-11e6-8098-5f106a235851.png)
I have made a simple but dramatic improvement as you can see in the attached screendumps. All I did was shifting each individual character with it's own angle instead of shifting the whole label with the average angle. I think it is worth to implement this pending your improvement.
I am looking for someone with write access to implement this for me. Contact me if you are interested.

**Comment by pcav** [comment]
Quite nice, +1!

**Comment by haubourg** [comment]
@fritsvanveen Hi, Just to be sure to understand, what is the difference between curved labels and your actual proposal. In curved labels, each letter is rotated too. What we miss is :+1: 
- having curved label being drawn even if lines have too high curve frequency at a given scale (too much letter overlapping)
- being able to choose where on a line a label should be drawn (think of cartographers needing a label on  a watercourse to be at a specific place, but still curved).
- have curved labels even for polygons (think of the name of a big moutain chain, we like sometimes to have the label follow a curve on the map)..

**Comment by fritsvanveen** [comment]
@haubourg 
Currently the characters are effectively rotated at the baseline. This results in overlapping characters if the angle is upwards and too much space if the angle is downwards. My improvement effectively rotates characters at the mean line, which looks much nicer. It is really a very small change in code.
This is my code in FeaturePart::curvedPlacementAtOffset:
    ...
    if (li->max_char_angle_inside == 41) // for testing only , should be true
    {
        double dist = 0.9 * li->label_height / 2;  // 0.9 looks nicer
        if (orientation < 0)
            dist = -dist;
        start_x += dist * cos(angle + M_PI_2);
        start_y -= dist * sin(angle + M_PI_2);
    }
    // existing code follows
    double render_angle = angle;
    ...
and in FeaturePart::createCurvedCandidatesAlongLine:
         positions.append( _createCurvedCandidate( slp, angle_avg, li->max_char_angle_inside == 41 ? 0 : -li->label_height / 2 ) );
BTW I'm using the magic number 41 as a way to compare old and new.

**Comment by jwva** [comment]
As a cartographic user of QGIS, this seems like a simple but very effective improvement for curved line labels. I warmly support the implementation of this "very small change".

**Comment by haubourg** [comment]
@fritsvanveen Thanks for the explanation, it is much more clear now.  @mhugo any opinion?

**Comment by nyalldawson** [comment]
@fritsvanveen I've just given your changes a test drive. They certainly look much better for labeling over the line, but it breaks the placement if the curved labels are set to draw on top or below the line. Is this correct or did I apply your changes incorrectly?

**Comment by fritsvanveen** [comment]
I had already extended my code to work with all placements.
`      if (( !reversed && ( flags & FLAG_ABOVE_LINE ) ) || ( reversed && ( flags & FLAG_BELOW_LINE ) ) )
        positions.append( _createCurvedCandidate( slp, angle_avg, mLF->distLabel() + li->label_height / 2 ) );
      if ( flags & FLAG_ON_LINE )
        positions.append( _createCurvedCandidate( slp, angle_avg, 0 ) );
      if (( !reversed && ( flags & FLAG_BELOW_LINE ) ) || ( reversed && ( flags & FLAG_ABOVE_LINE ) ) )
        positions.append( _createCurvedCandidate( slp, angle_avg, -li->label_height / 2 - mLF->distLabel() ) );
`
Probably the middle _createCurvedCandidate( slp, angle_avg, 0 ) can be replaced by `slp`

**Comment by nyalldawson** [comment]
@fritsvanveen any chance you could open a pull request with your changes? That'd make it easier to test and we could move the discussion over there.

**Comment by fritsvanveen** [comment]
@nyalldawson finally got the code formatting right. I worked on a zip-file of the 2.15 code. I'm in the process of forking the master with git a then I can properly do a pull request.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
