### ISSUE TITLE
QEP 29: Label line supports

### ISSUE THREAD

**Issue by mhugo** [qgis/QGIS-Enhancement-Proposals#48]
# 
# QGIS Enhancement 29: Label line supports

**Date** October 2015
**Author** Hugo Mercier
**Contact** hugo dot mercier at oslandia dot com
**Last Edited** 
**Status**  
**Version**
## Summary

A high level of refinement for manual label placement maybe required for some users, when words or even letters of a label have to be placed precisely for example.

We propose to rely on label paths (see QEP on label paths) to implement this feature.
## Proposed solution

Here is a map with labels where such a free placement feature would be useful :

![Cadastre](https://raw.githubusercontent.com/mhugo/QGIS-Enhancement-Proposals/adv_labeling/cadastre.jpg)

For such advanced labeling needs, where the user may want to place every word precisely, we propose to model it thanks to a label path.

This will only be available for labels that have a size expressed in fixed map units. It does not make sense to precisely place letters of a label if letters of this label have a size dependent on the current zoom factor.

This kind of label path is represented by a multi-linestring, called **label support**. Each linestring of the multi-linestring is a line where part of the text may be placed.

Each segment of a linestring represents a position and angle for the label letters. When one of the linestring "overflows" (no room left for the remaining letters), remaining letters will be placed on the next linestring.

![Label annotation](https://raw.githubusercontent.com/mhugo/QGIS-Enhancement-Proposals/adv_labeling/label_annotation.png)

This allows the user to introduce artificial horizontal or vertical spaces.

Since such representation is low-level and hard to handle for the end users, tools will help to create lines where the final label will be drawn for common scenarios (a multi-line paragraph). For more advanced uses, the underlying multi-linestring will be available for modification by the end user.
## Core Changes

An new data-defined option to the labeling options, "Multilinestring for the free placement of letters" of type geometry will be added.

The labeling engine will be modified to draw these annotations directly, out of the global optimization. The glyphs will still be considered as obstacles for other automatically placed labels.

A helper function that outputs a multi-linestring of glyph placement for a multi-line paragraph (based on litterature on word wraping algorithms) will be added.
## GUI Changes

A new "label support" toolbox will be added, only enabled when labels are pinned, with the following buttons:
- "Use label supports": toggle button. Toggle a label between simple x/y/angle positioning and positioning by line supports. If no data-defined property is set for the corresponding properties of the layer, they will be created in the auxiliary storage (see QEP on auxiliary storage)
  - If the label was positioned by x/y/angle, then a straight horizontal line is created as its initial support.
  - If the label was using a support, the x/y/angle of the first part will be used as x/y/angle for the simple positioning
- "Show label supports": toggle button to display support lines of labels, if available
- "Add part": add a line support at the end of the current chain. This tool will allow to draw a linestring with the mouse.
- "Remove part": remove a line support
- "Reorder part": When a part is clicked, it will allow to move it forward or backward in the list of line supports.
- "Paragraph box": Helper tool. The user will draw a box. A dialog will be shown to specify options of the paragraph (interline size, text direction, etc.). Line supports will be created out of this box.
## Further considerations

Other helper functions could be added in the future, like a tool that outputs the medial axis of a polygon as a label path (for the labeling of large streets for instance)

**Comment by haubourg** [comment]
From a UX point of view, I expect user to use current data defined labeling toolbar, without even knowing dark magic underneath. 
"Place label glyphs on the segments of the label path"  is too obscure IMO. 
Here is the nominal sequence I expect as a user:
 - label a layer as usual
 - have data defined labeling toolbar available on any layer, even if data defined settings are not set and layer is read only
 - when moving or editing a label, QGIS should transparently store additional data in auxiliary datasource of the project (how to do when no project is saved yet?), maybe only for concerned label. 
 - curved tools should be available in data defined toolbar. User pick one to bend a curve, the it stores geometry in labeling path
- user modify label expression or text with that toolbar. If a line break is created or deleted, geometry path should probably be regenerated on the basis of a straight multiline (with breaks) 

Is that what you had in mind?

**Comment by mhugo** [comment]
> how to do when no project is saved yet?

Not a problem. A QgsProject always exist in memory even without project file.

Yes this is what I had in mind. But I will complete the document to better reflect this use case.

**Comment by mhugo** [comment]
Text updated

**Comment by mhugo** [comment]
@NathanW2 I would say this one is also in final draft

**Comment by mhugo** [comment]
I would like to move on these QEP. Some remaining questions / objections ? Could it be voted ?

**Comment by mhugo** [comment]
After discussions with @haubourg , this QEP answers to very advanced use cases and leads to complex code (complex to develop and hard to fund). I then close this QEP and will open another one that focuses on improvements to the curved labels

**Comment by haubourg** [comment]
I think that QEP should stay opened, the need is still there, but fundings were prioritized to the other  QEP required to achieve that.

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
