### ISSUE TITLE
QEP 49: Label mask

### ISSUE THREAD

**Issue by mhugo** [qgis/QGIS-Enhancement-Proposals#49]
# 
# QGIS Enhancement 49: Label mask

**Date** October 2015
**Author** Hugo Mercier
**Contact** hugo dot mercier at oslandia dot com
**Last Edited** 
**Status**  
**Version**
## Summary

This QEP is about the integration of a special kind of object which serves as a mask for the labeling engine.

Thanks to symbology options like "inverted polygon fill" and/or "shapeburst fill", it is possible with the current QGIS version to display maps where some parts are "highlighted", because the uninteresting parts have been masked out.

![Mask 1](https://raw.githubusercontent.com/mhugo/QGIS-Enhancement-Proposals/adv_labeling/mask_1.png)

However it may be desirable to also mask labels of the parts without much interest.

![Mask 1](https://raw.githubusercontent.com/mhugo/QGIS-Enhancement-Proposals/adv_labeling/mask_2.png)

Here we can see that some labels are chosen to still be displayed (name of the departments), but other are filtered out by the mask.

Legend items should also be filtered out if they are currently masked.

One last need would be to also consider the mask geometry as an obstacle during label placements. In this case, not only features will be filtered out of the mask geometry, but no label could overlap it.
## Proposed solution

The needs are:
- be able to hide labels based on a polygon geometry ("mask")
- be able to consider the mask geometry as an obstacle
- be able to visualize and manipulate this geometry (with a symbology)
- be able to set an option during atlas so that the mask geometry is the atlas polygon
- (option) be able to manually edit the mask geometry

We propose to add a concept of "mask geometry", that is global and unique for the current project.

The mask geometry can then be used by the labeling engine to hide some labels.
## Core Changes

A new project variable "@mask_geometry" will be added and will store the geometry of the mask. And then the ability to store geometries in a variable will be added.

A new labeling property will be available for each vector layer to use or ignore the mask geometry as an obstacle for the automatic placement of labels.
## GUI Changes

New functions will allow to easily convert a selection from a polygon layer to the mask layer. When multiple polygons are selected, the resulting mask geometry is the geometric union of all the polygon selections.

An option will also allow to make the geometry (the first one, or an union of all the geometries) of a vector layer the mask geometry.

A button will allow to show/hide the mask geometry as a canvas item and will allow the user to edit it with digitizing tools.

New labeling properties will be available for each vector layer allowing to use the mask geometry:
- a check box "Don't show labels inside/outside (with a dropdown) mask"
- a second nested check box enabled when the first is checked : "and consider the mask as an obstacle for labels"

A new toggle button in the legend will allow to filter out items if they are outside the mask.

A shortcut will be added in the application to create a (read only) vector layer from the mask geometry. This could be implemented by a virtual layer where the geometry is the @mask_geometry variable.
## Atlas integration

An option will allow to use the mask geometry as the atlas feature. This will be done by overloading the global mask geometry in the atlas expression context and make it change when the atlas feature changes.

Then if there is a "mask" vector layer (through virtual layer) its geometry will then be updated to reflect the current atlas geometry (in the composer). As well as labels that will be masked based on the current atlas geometry (if the corresponding option is enabled)

**Comment by wonder-sk** [comment]
Do I understand correctly that the mask would be used optionally for labeling of layers - some layers use it while others don't? Could each layer have a different mask?

What would the mask determine - no labels are allowed outside the mask - or no features will be used from outside?

I am not sure if it would be a good thing to have another type of map layer - is that really necessary? Adding of new layer type brings a lot of complications with data access, rendering, GUI interaction etc

From the point of view of the labeling engine, one just needs to define a geometry, so why not just introduce a means to define the geometry and not introduce a concept of mask layers at all? E.g. in GUI there could be two buttons - one to define mask geometry (from a geometry of a layer) - and another one to show/hide the mask geometry (as a canvas item).

For filtering of legend items, there is already a button with very similar functionality - that filters out items not shown in the current map view - maybe it would be best to have the new functionality integrated with the existing button.

**Comment by mhugo** [comment]
> Do I understand correctly that the mask would be used optionally for labeling of layers - some layers use it while others don't?

Yes

> Could each layer have a different mask?

No. There is only one mask for all the layers.

> What would the mask determine - no labels are allowed outside the mask - or no features will be used from outside?

Good question. I think it is no big deal if a label lies outside of the mask, as the images show. So no **features** should be registered outside of the mask

> I am not sure if it would be a good thing to have another type of map layer - is that really necessary? Adding of new layer type brings a lot of complications with data access, rendering, GUI interaction etc

> From the point of view of the labeling engine, one just needs to define a geometry, so why not just introduce a means to define the geometry and not introduce a concept of mask layers at all? E.g. in GUI there could be two buttons - one to define mask geometry (from a geometry of a layer) - and another one to show/hide the mask geometry (as a canvas item).

A "mask layer" is something that the user can place in the legend over or under other existing layers. And it can also be used for filtering labels.
Defining a new type of canvas item that can be manipulated in the legend as any other vector layer seems to me more complicated than adding a new type of layer with a very simple data model.

**Comment by mhugo** [comment]
After thinking a bit more about it, I agree with @wonder-sk. The label mask is nothing more than a geometry.
Updated the text to reflect these changes. There is one global mask geometry stored as a project variable and it can be automatically updated from a layer if the user chooses so.

**Comment by mhugo** [comment]
Updated text to explicit how a mask vector layer can be created.
@NathanW2 That's a final draft for me

**Comment by NathanW2** [comment]
@nyalldawson @wonder-sk @dakcarto comments?

**Comment by nyalldawson** [comment]
All good to me, except for:

> There is one global mask geometry stored as a project variable and it can be automatically updated from a layer if the user chooses so.

I think this should be revised. Ie, if the mask is intended to be set at a project level then this is OK, but the atlas/composer/etc should NEVER change project variables. Instead the atlas feature mask would be set in the atlas expression context scope (if the "using atlas feature as mask" option is enabled). Storing an atlas-set mask within a project variable is against how expressions contexts are designed to be used.

**Comment by nyalldawson** [comment]
Also note that you'd need to update the project variable storage code to handle qgsgeometry objects in qvariants (eg storing via wkt or the like).

**Comment by mhugo** [comment]
@nyalldawson thanks for reminding me the expression contexts. I've rephrased the last section to reflect this. And added a note on the core changes about the need to be able to store geometries in variables.

**Comment by nyalldawson** [comment]
Great - looks good to me, so +1 on accepting this.

One last thing I'm a bit unclear on: will the mask be used as a labelling obstacle or for filtering features which will be labelled? Ie, if a polygon or line is partially within the mask, does that mean it's going to be labelled within the mask or not at all? Similarly, if a point was just outside the mask but the label distance set far enough so that it's possible for the label itself to fall totally within the mask, would it be drawn? And the reverse of this: if a point is inside the mask, can its label be drawn outside the mask?

If the mask is used as an obstacle rather then a filter, you may need to add some handling to pal to allow obstacles to be a" never-ever-under-any-circumstances cover this obstacle" type. Currently pal will still cover obstacles if it calculates that the cost of not doing so and missing a label is higher than the cost of covering the obstacle.

**Comment by timlinux** [comment]
For me what is still unclear is : "How will the user actually define the mask?" - is the expectation that they copy and paste a feature from another layer into the project field in settings?

Also I am unclear of what happens when you have atlas scenes that need to e.g. set the mask to be all the non atlas features. Or what is the mechanism you have in mind for this?

**Comment by mhugo** [comment]
@nyalldawson good point. We should have an option for considering the mask as an obstacle as well.
> you may need to add some handling to pal to allow obstacles to be a" never-ever-under-any-circumstances cover this obstacle" type

Hmmm, thanks for pointing this. I thought this was already possible. So we need a way to have an infinite cost for covering an obstacle ?

> For me what is still unclear is : "How will the user actually define the mask?" - is the expectation that they copy and paste a feature from another layer into the project field in settings?

That is one possibility. The other one is to rely on new tools in the main application to show/hide the current mask and modify it thanks to something similar to the node tool.

> Also I am unclear of what happens when you have atlas scenes that need to e.g. set the mask to be all the non atlas features. Or what is the mechanism you have in mind for this?

Hmmm one possibility would be to define the mask geometry in atlas from an expression. Then it could be @atlas_geometry or difference(geom1, @atlas_geometry) or whatever ...

**Comment by nyalldawson** [comment]
> So we need a way to have an infinite cost for covering an obstacle ?

Yes. I also suspect there's a bug somewhere in pal (or a bad choice of costs) which results in labels sometimes being placed over obstacles when they really should not be. My suspicion is that the cost for excluding certain labels is too great, so it's less costly to cover an obstacle then skip labeling these features. I was planning on looking into this but haven't had a chance yet.


Another question: how will this be exposed in the labeling GUI? Will it be a new option (along the lines of "don't show labels outside mask")? If so, then:

> Hmmm one possibility would be to define the mask geometry in atlas from an expression. Then it could be @atlas_geometry or difference(geom1, @atlas_geometry) or whatever ...

could be done by just adding options "don't show labels outside mask", "don't show labels inside mask", etc. That's cleaner then falling back to expressions for this.

I'm also wondering if you are planning on reusing the data defined "show label" option for this? I'd say it's probably better for this to be a new option, rather then reusing the data defined option. That would leave the show label control free for users to use for other labeling requirements.

**Comment by mhugo** [comment]
@nyalldawson This would have to be refined during the implementation, but in the labeling properties GUI, there could be : 
- a new check box "Don't show labels inside/outside (with a dropdown) mask"
- a second nested check box enabled when the first is checked : "and consider the mask as an obstacle"

**Comment by mhugo** [comment]
Updated text to clarify mask as a filter / mask as an obstacle

**Comment by mhugo** [comment]
I would like to move on these QEP. Some remaining questions / objections ? Could it be voted ?

**Comment by timlinux** [comment]
👍 From me to add this feature - how about you @NathanW2 , @nyalldawson and anyone else who followed this thread?

**Comment by mhugo** [comment]
+1 from tim and @nyalldawson already gave a +1 earlier. @NathanW2 accepted ?

**Comment by NathanW2** [comment]
Yes. Will update tag later

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
