### ISSUE TITLE
QEP 54: Dropping fTools and GDALTools core plugins in favor of the Processing

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Enhancement-Proposals#54]
# QGIS Enhancement 54  (was 36): Dropping fTools and GDALTools core plugins in favor of the Processing

**Date** 2016/01/26
**Author** Alexander Bruy (@alexbruy)
**Contact** alexander dot bruy at gmail dot com
**Version** QGIS 2.16/3.0
# Summary

Functionality of the fTools and GdalTools plugins now available in the Processing framework. Also Processing brings some nice additions e.g. batch execution, scripting which was not available with fTools/GdalTools. Both fTools and GdalTools plugins does not receive much attention since the introduction of the Processing.

Now we have duplicated codebase and when bugs found we need to fix them twice: in the Processing code and in the code of the fTools/GdalTools. This increases maintenance costs and there is a chance that bug will be fixed only in one place, causing problems for users.

There were several discussions about this including one at the hackfest in Essen:
- http://lists.osgeo.org/pipermail/qgis-developer/2014-June/033359.html
- http://lists.osgeo.org/pipermail/qgis-developer/2015-May/037657.html
- http://lists.osgeo.org/pipermail/qgis-developer/2015-September/039106.html
## Proposed Solution

Consolidate developers efforts on Processing, as this is more feature rich and flexible plugin. fTools and GdalTools plugin will be removed (in fact GdalTools plugin will be kept, until we have multithreading support in Processing, as it does not block QGIS main window during long-running analysis). To keep most used tools in the usual place and avoid confusion Processing will create menu entries in the _Vector_ and _Raster_ menus, replacing removed algorithms with its own implementation. Algorithms available from menus will have same icons as old fTools/GdalTools tools, see screenshots below

![vector-menu](https://cloud.githubusercontent.com/assets/776954/12614072/5117c178-c506-11e5-9294-5d95e95d66b6.png)

![raster-menu](https://cloud.githubusercontent.com/assets/776954/12614076/55e4a3c4-c506-11e5-93a4-3e62a1e50cb8.png)

This also allow our documentation writers easily update documentation, as there are no GUI changes.

Advanced users that need more control on menus (add/remove some entries, create their own menus/submenus, etc) can customize menus from Processing options.

![processing-menus](https://cloud.githubusercontent.com/assets/776954/12776274/49c5fc8a-ca5d-11e5-98ed-e781a60117cd.png)

It is possible to choose which algs to show and where to put them. Menus and submenus should be specified in format

```
MenuName/SubMenuName
```

**NOTE**: if existing menu/submenu entry has "&" symbol it should be also specified.
### Affected Files

Directories `python/plugins/fTools` and `python/plugins/GdalTools` will be removed. Corresponding `CMakeLists.txt` file should be updated.

References to both plugins also should be removed from `src/app/qgspluginregistry.cpp` and `ms-windows/python_plugins.nsh`.

Processing code will be updated to create submenus in the _Vector_ and _Raster_ menus.
## Further Considerations/Improvements

In future more improvements can be made:
- implement custom dialogs for algorithms that available from menus
- create additional submenus with frequently and widely used algorithms to make them more visible
## Backwards Compatibility

As all tools will be available in the same menus with same icons and almost the same names there should not be any issues. The only difference is the GUI of the Processing dialogs, which are quite different from dialogs used in fTools/GdalTools. But as most of the users already familiar with Processing UI this also should not be a problem.
## Prototype

An implementation of the above ideas can be found in this branch
https://github.com/alexbruy/QGIS/tree/drop-ftools-gdaltools
## Votes

(required

**Comment by NathanW2** [comment]
Big +1 from me.  No need to have duplicate code, which is sometimes worse
just because it's old.

**Comment by pcav** [comment]
In principle +1.
Main issue: the GdalTools windows are non-blocking, Processing are. This is a major problem for long running analysis. This could be solved by the multithreaded implementation of Processing, but this is not available yet.
Before proceeding, please make sure no option is missing in Processing compared to GDALTools.

**Comment by NathanW2** [comment]
Do we have a main owner for the old fTools code is it really just anybody
at this point.  As this is removing that code I don't think it really
matters but just checking first.

**Comment by pcav** [comment]
Moreover: one missing functionality is the possibility of editing GDAL commands directly. Better implement it before removing the old plugin.

**Comment by rduivenvoorde** [comment]
@alexbruy can you maybe share some screenshots? As from what I understand there will be menu-items available too isn't it?

@pcav do you really think that is used a lot? Let's not wait on having ALL before proceeding?

**Comment by NathanW2** [comment]
I would assume this is for the next release so if it's done early there
should be enough time to move any missing functions before release.  Might
be a good idea to update the QEP with any things that need to be covered or
reasons they can't.

**Comment by pcav** [comment]
@rduivenvoorde do you mean command editing, or blocking windows? The first probably not, the second has a big impact on power users. Even if not very commonly used, I would not like to make people unhappy, because we'll end up having people sticking to obsolete versions, which is bad.

**Comment by volaya** [comment]
@pcav Implementing the ability to manually edit the command might be more complex than what it looks like, considering the Processing code underneath. Is it really something needed? I mean, you can edit the parameters (including the "additional commands" entry that some of them have), so you can have exactly the same. How many people actually tweak the console call?

About the GDALTools windows being not blocking, that should not be a problem once we have the multithreading execution. I guess it's worth working on that instead of keeping the two implementations.

As @NathanW2 says, this is something that will be ready for the next version, and multithreading is expected to be ready for that release as well.

**Comment by alexbruy** [comment]
@pcav as @volaya said, it is difficult to add direct editing of the GDAL commands to Processing. Instead we can add to algorithms "Additional commands" parameter, so you can adjust resulting command if necessary. Is it enough?

**Comment by alexbruy** [comment]
@rduivenvoorde yes, you are right. There will be menu items in the same places as fTools/GdalTools have, with same icons. I will add screenshoots

**Comment by alexbruy** [comment]
@rduivenvoorde screenshots added

**Comment by rduivenvoorde** [comment]
Wow, thanks Alex for adding these! 

Seeing this a big +1 !!!

Nice

**Comment by pcav** [comment]
@volaya  @alexbruy : about editing, I think your position is reasonable.
@volaya : about multithreading, wouldn't it be better to remove GDALTools only after merging mutithreading?
Still unsure having the same commands on the Processing toolbox and under separate menus: although codewise the duplication is removed, from the user point of view it is puzzling having two identical commands.
Sorry if I seem too critical, I think this is a big step forward!

**Comment by alexbruy** [comment]
@pcav menus only for novice users and to prevent confusion like "Where is all my geoprocessing tools?". If you don't need this menus, you can disable them in the Processing settings and they will not be created.

**Comment by pcav** [comment]
@alexbruy very nice - in the future we can always decide to switch them off by default, or enable user profiles (basic: menus enabled, no processing; advanced: the reverse)

**Comment by NathanW2** [comment]
@alexbruy I have made this final draft mainly because there isn't really much more to add unless others need it.

**Comment by volaya** [comment]
@pcav I added a change to this PR, allowing the user to configure the menu items from the Processing config. By default, it will replicate the ftools and GDALTools menus, but it can be easily configured to change that. @alexbruy just merged that PR and updated the description of this one, adding a screenshot and some text about it

About leaving GDALTools, you are right, maybe it is a good thing to only replace ftools at first and continue once we have the multithreading functionality ready

**Comment by pcav** [comment]
Thanks @volaya

**Comment by alexbruy** [comment]
I updated QEP, to reflect that we will keep GdalTools plugin until multithreading support in Processing will be availalble. This means that GdalTools will be here until QGIS 3.0, as multithreading in Processing is an API break.

@NathanW2 can we have vote on this? It would be good to have this merged early to get as much testing and feedback as possible before next release.

**Comment by NathanW2** [comment]
I'm happy with what this includes. If someone else is then good to go.

**Comment by volaya** [comment]
I think it is perfect like this, only with ftools replaced at the moment, and waiting for 3.0 to replace also gdal tools

so +1 from me also

**Comment by NathanW2** [comment]
Good to go

**Comment by alexbruy** [comment]
Code merged in master. Many thanks to all for productive discussion and valuable comments

**Comment by Gustry** [comment]
I tested just now. It's very very nice ! ! Thanks for your work ;-)

**Comment by NathanW2** [comment]
@alexbruy thanks!  I'm just clearing out the back log of QEPs.

**Comment by pcav** [comment]
Shouldn't this be left open for the GDALTools part?

**Comment by NathanW2** [comment]
Yes sorry.

**Comment by alexbruy** [comment]
GDALTools removed from master in qgis/QGIS@f40e914b769c2e09d884c6a67cfb41cb934a40a9
