### ISSUE TITLE
QEP 38: Remove irregular 'star' symbol from simple marker

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#56]
#  QGIS Enhancement 38: Remove irregular 'star' symbol from simple marker

**Date** 2016-04-06
**Author** Nyall Dawson (@nyalldawson)
**Contact** nyall dot dawson at gmail dot com
**Status** Approved
**Funding** N/A
**Version** QGIS 2.16

# Summary

The simple marker point symbology option includes a growing number of useful preset symbol shapes. One of these ("star" - see below) is a very ugly, distorted star symbol. It is extremely unlikely that users will be utilising this distorted symbol in their maps, so this QEP covers removal of the symbol.

![star](https://cloud.githubusercontent.com/assets/1829991/14297629/32b11254-fbc3-11e5-89bb-49d2df57d74a.png)

At some stage a standard star symbol was also added, with the confusing name of 'regular_star'. There are now two star symbols in the simple marker symbology. This QEP proposes that the distorted 'star' symbol be removed, and transparently replaced with the better 'regular_star' symbol for existing projects.

## Proposed Solution

The current distorted 'star' symbol will be removed, and the regular star symbol renamed as 'star' to take its place. If a project or data defined property references the 'regular_star' symbol, this will be treated as an alias for 'star'.

### Affected classes

* QgsSimpleMarkerSymbolLayerV2: `QgsSimpleMarkerSymbolLayerV2::prepareShape` will be modified to remove the distorted star polygon and return the standard star if the symbol name is either 'star' or 'regular_star'.

* QgsSimpleMarkerSymbolLayerV2Widget: description text for the data defined symbol name will remove the 'regular_star' option. Note that this value will still function, it will just be treated as an alias for 'star'.

## Votes

(required)

**Comment by timlinux** [comment]
Who death to the dodgy star...! :+1:

**Comment by NathanW2** [comment]
+1 death of a star

**Comment by nyalldawson** [comment]
I should have added that if this QEP is successful I will seek funding via joint sponsorship from the PSC  + a crowd funding campaign to implement these changes.

**Comment by m-kuhn** [comment]
[+1 death star](https://www.youtube.com/watch?v=Sv5iEK-IEzw)

**Comment by andreasneumann** [comment]
hm - maybe the star is already discarded and you still see it because it is light-years away

**Comment by slarosa** [comment]
I agree with @andreasneumann. Meanwhile that the star is still there, could we use the recent No Symbol renderer for it? Also we could insert a new marker to replace the star for example black_hole. thoughts?

**Comment by m-kuhn** [comment]
Is this still in **draft** status?
