### ISSUE TITLE
Spacebar Switches to Pan Tool.

### ISSUE THREAD

**Issue by adamold** [qgis/QGIS-Enhancement-Proposals#60]
# QGIS Enhancement: Title

**Date** 2016/05/14

**Author** Adam Old (@adamold)

**Contact** adamold@gmail.com

**maintainer** @user

**Version** QGIS 2

# Summary

Follow UI standards set by Adobe and other graphics software for navigating large documents while zoomed in and manipulating objects. In this case, improve navigating the map while using the "select features" tool or other tools. 

## My Section

(optional) Insert custom sections wherever needed

## Proposed Solution

Press and holding spacebar should switch to the pan tool while spacebar is depressed. This allows immediate access to panning without resetting tool. This is a common solution, and is widely used by those with graphics background. 

### Example(s)

see photoshop/illustrator 

### Affected Files

none attached

## Performance Implications

none

## Further Considerations/Improvements

none

## Backwards Compatibility

no effect on files. 

## Issue Tracking ID(s)

?

**Comment by nyalldawson** [comment]
Might be worth noting that this behaviour is present in composer, so adding it to canvas would help standardise behaviour across QGIS.

QEPs are usually created when someone plans to begin work on something. Are you planning to implement this change? If not, a feature request at http://hub.qgis.org/issues would be more appropriate.

**Comment by NathanW2** [comment]
This is already the case in the canvas. Space will enable a pan while enabled

**Comment by adamold** [comment]
It works like this in Print Composer, but not canvas. In QGIS 2.14 canvas space toggles the layer visibility.

**Comment by m-kuhn** [comment]
The "problem" is that it only works when the map canvas has the focus.

Alternative approaches would be to let the focus follow the mouse cursor (not sure if I like that) or automatically forward the focus to the mapcanvas from the layer tree (also not sure if I like that). Other ideas?

**Comment by adamold** [comment]
Ah, the window focus is very subtle (Mac OS), and you can select and interact with the canvas while it isn't in focus. It might be more obvious if the cursor changed to pan-hand when spacebar was depressed and canvas was in focus.
