### ISSUE TITLE
Add option for NULL data symbol in graduated style

### ISSUE THREAD

**Issue by adamold** [qgis/QGIS-Enhancement-Proposals#61]
# QGIS Enhancement: NULL data symbol in graduated style

**Date** 2016/05/18

**Author** Adam Old (@adamold)

**Contact** adamold@gmail.com

**maintainer** @user

**Version** QGIS 2.14.2

# Summary

When styling data as a chloropleth, it is important to be able to distinguish between measurements of 0 and NULL. There should be an easy option to add a null style. 

## Proposed Solution

add small button that would insert a style for either "other" falling outside the data range, or NULL, or ideally, both. 

### Affected Files

not sure

## Performance Implications

none?

## Backwards Compatibility

?

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by NathanW2** [comment]
Please open normal feature requests at hub.qgis.org. QEPs are for larger
scale chnages
