### ISSUE TITLE
QEP 64: move geocoder component into core

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS-Enhancement-Proposals#64]
# QGIS Enhancement 64: Move Geocoder Component into QGIS Core

**Date** 2016/06/11

**Author** Richard Duivenvoorde (@rduivenvoorde) et al.

**Contact** richard@qgis.org

**maintainer** @rduivenvoorde

**Version** QGIS 3.0
# Summary

With the proliferation of Geocoder componets, Paolo asked the develop list if it isn't time to incorporate geocoder functionality into core, see for more discussion this thread:

https://lists.osgeo.org/pipermail/qgis-developer/2016-June/043145.html
## Current python geocoder plugins:
- http://plugins.qgis.org/plugins/GeoCoding/
- http://plugins.qgis.org/plugins/GeoCodingKorea/
- http://plugins.qgis.org/plugins/navidata/
- http://plugins.qgis.org/plugins/pdokbaggeocoder/
- http://plugins.qgis.org/plugins/ru_geocoder/
- http://plugins.qgis.org/plugins/geopunt4Qgis/
- https://github.com/sookoll/qgis_plugin_inads_geocoder/
- http://plugins.qgis.org/plugins/pdokservicesplugin/
- http://plugins.qgis.org/plugins/mmqgis/
- https://github.com/lutraconsulting/qgis-discovery-plugin (database-based, not webservice)
## Proposed Solution

See mail thread. 

Usable libs (mentioned in email thread):
- http://www.gdal.org/ogr__geocoding_8h.html (see: http://www.itopen.it/geocoding-with-gdal/)
- https://github.com/geopy/geopy (python)
- https://pypi.python.org/pypi/geocoder (python)

Ideas:

Richard:
What about something like that:
- we creating a gui-widget/toolbar for a geocoding search
- we create a python api for it (actually: implement a buttonless plugin
  which registres the geocoder, and registres some slot/signals and does
  (part of) implementation)
- by installing this plugin(s) you registre one or more geocoders, AND
  the plugin author actually implements the calling/retrieving/parsing of
  the results. We can maybe do some general standards in core (or via
  gdal): like OGC-OpenLS interface, or OSM-based ones or so
- the core-geocoder gui then can look like the search bar in Firefox
  a little dropdown in which you can select WHICH geocoder you run by default
- this core geocoder widget can then also implement a small 'multiple
  result' list...

![firefox_and_simplewritesubmit](https://cloud.githubusercontent.com/assets/731673/15984658/eb51722e-2fd3-11e6-825d-d711cd5a9117.png)

A side note:
- some of the geocoders plugins Paolo lists, are 'one shot' geocoders:
  you sent one address and it returns one or two results. This is the
  geocoder I'm talking about
- some of the geocoder plugins accept a csv/list, you have to select
  some columnnames and you sent the list to a service and you get a list
  back (with info about misses etcetc). This is much harder I think to
  implement in a general way? Would be cool though...
  pdokgeocoder and MMQGISplugin have these...

Martin:
And I would not limit ourselves to just geocoding - there are other uses for that, e.g.:
- gazetteers - for example Discovery plugin [1]
- search in attributes of loaded layer(s)
  The API implementation could also take care of things like on the fly
  completion while user is still typing and running the queries in the
  background, so the GUI is not blocked. So a search plugin would only
  take care of processing search/geocoding/gazetteer query and response,
  all the rest would be handled by QGIS.

Nathan: I quite like how the Locator bar in Qt Creator work by also allowing
prefixs for searching:
- c - Class search
- . - method search

Alessandro: I guess that the most reasonable implementation would be having the most common geocoders (whole world coverage) available as core implementationn and create an API to register local/national geocoders by plugins.

Mederic: It could also be very interesting to have one or more  Processing module(s) for geocoding (natives QGIS "algorithms"). We could then chain this with other algorithms (find all objects of a layer intersecting a 500m buffer from the positions of the adresses in a list for example). Of course this module would be easier to write if we would have a native QGIS API for this...
### Example(s)

(optional)
### Affected Files

(required if applicable)
## Performance Implications

**(required if known at design time)**
## Further Considerations/Improvements

_(optional)_
## Backwards Compatibility

**(required)**
## Issue Tracking ID(s)

_(optional)_
## Votes

(required)

**Comment by rduivenvoorde** [comment]
Please see this email thread: https://lists.osgeo.org/pipermail/qgis-developer/2017-September/049834.html
About the use of QgsLocator(Widget) for this.

**Comment by nyalldawson** [comment]
> some of the geocoder plugins accept a csv/list, you have to select
some columnnames and you sent the list to a service and you get a list
back (with info about misses etcetc). This is much harder I think to
implement in a general way? Would be cool though...
pdokgeocoder and MMQGISplugin have these...

I'd suggest that these should be implemented within the processing framework, so that they can be reused during model execution (e.g. a model which pulls in a csv, geocodes it, then does other processing on the newly spatial data). 

We could have some generic base class for processing geocoding algorithms to ensure that the behaviour is similar across different providers (and also to ease development of the geocoding services)

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
