### ISSUE TITLE
QEP 66: Better editor widgets with support for arrays and maps

### ISSUE THREAD

**Issue by pvalsecc** [qgis/QGIS-Enhancement-Proposals#66]
# QGIS Enhancement 66: Better editor widgets with support for arrays and maps

**Date** 2016/07/18

**Author** Patrick Valsecchi (@pvalsecc)

**Contact** patrick.valsecchi@camptocamp.com

**maintainer** patrick.valsecchi@camptocamp.com

**Version** QGIS 3.0
# Summary

A simple INSPIRE WFS query returning GML Complex Features, mapped to a relational table, can lead to up to 50 tables due to the complexity of INSPIRE schemas and the presence of xlinks to additional info. In order to make such complex data usable in QGIS we need a few things in QGIS:
- Better support of array and map types for DB fields (at least for PostGIS and Spatialite). That would allow us to reduce the number of tables by mapping, for example, store translated texts into a `hstore` (lang=>text) in PostgreSQL instead of using a 1-N relation to an additional table (lang, text).
- Better default widgets used for editing feature attributes. For the moment, QGIS always use `TextEdit`. Using the native types of the DB, we could do better than that.
- Add support to lookup a table to specify the widgets to instantiate for editing a field. Something similar to the layer_styles table used to provide default stylings.
### Support for arrays and maps

Spatialite has no support for those types. To work around that, the TEXT type can be used with a JSON representation of the list of map to be stored.

PostgreSQL has native types for those (arrays and `hstore`). Arrays are converted internally into a PostgreSQL specific representation before being read. This would be switched to a `QList`/`QMap` internal representation.

Other type of datasource is not considered for this project. But they must have a sane default behaviour in regard to those changes.

Functions will be added to the expression language to manage those types. Their naming will match their equivalent in PostgreSQL if they have one. For example:
- array_length
- array_contains
- array_find
- array_get

New tests for the PostGIS datasource will be added to check the support of those types (read/write). The new expression functions will be tested as well.
### Better default edition widget

Change the `isFieldSupported` method to `QgsEditorWidgetFactory` allowing a factory to tell how good it is to edit/represent a given field:
- 0: not supported
- 5: barely supported (`Datetime` returns that for string fields)
- 10: barely supported (`TextEdit` returns always that)
- 20: perfect support
- …

Then, a `QgsEditorWidgetRegistry::findBest(const QgsVectorLayer& vl, int fieldIdx) const` could be created and used to find the best widget (internal or introduced by a plugin) for a given field. If more than one widget matches with the same rating, the first registered will be taken. This will be the subject of a few UTs.

A plugin system will be put in place so that `findBest` can be enhanced with datasource or customer specific logic.

Widgets will be added for editing array and maps. They will be represented as editable tables (one column for arrays and two for maps) with a toolbar to add/remove entries. Those widgets must be able to work with native `QMap`/`QList` and with a `QString` containing a JSON (for Spatialite). If doable, tests will cover those widgets.
### Widget types from a table

The INSPIRE schemas could be used to automatically feed a metadata table that specifies specialized widgets to be used and their default configuration for every fields of every tables. A plugin for `QgsEditorWidgetRegistry::findBest` will looks if this table exists in the database of the given layer and search a row for the given table and field. If an entry is found, use the specified widget.

The place in the code where the data for that will be collected is not yet determined.
### Affected Files

I’ve added a few TODO in the code where things need to be added/changed in this branch:
https://github.com/pvalsecc/QGIS/tree/editor_widgets_qep

Obviously, a few files will be added for the widgets for arrays and maps.
## Performance Implications

Negligible. There is no complex computation done on very little data and not very often (at startup)
## Further Considerations/Improvements

The feasibility to use sub-widgets (TextEdit, DateEdit, ...) for editing the array or map entries has not been studied for the moment. PostgreSQL supports only maps with strings for keys and values but is 100% flexible for arrays.
## Backwards Compatibility

Current projects using PostGIS with arrays will be affected because of the modified internal representation from `QString` to `QList`. This could be a problem for custom plugins relying on that. We don't support `hstore` yet, so the usage of `QMap` won't be a problem.
## Votes

(required)

**Comment by wonder-sk** [comment]
Hi Patrick

> For backward compatibility reasons, it would not be a good idea to switch to an QList or QMap internal representation.

I would think it is preferable to use QList and QMap (or QHash) for arrays/maps because they can be stored in QVariant easily. Additionally, in QGIS 3.0 we are free to break compatibility. I believe the native storage instead of JSON would make it easier to use the new types in the code...

**Comment by pvalsecc** [comment]
@wonder-sk, if you guys are OK breaking backward compatibility that much, I would be happy to use QList and QMap for those types. I agree with you.

**Comment by nyalldawson** [comment]
> I would think it is preferable to use QList and QMap (or QHash) for arrays/maps because they can be stored in QVariant easily. 

+1 . I'd much rather see use of proper lists/maps in place of json strings.

**Comment by nyalldawson** [comment]
> The structure of the strings returned for PostGIS native arrays would be changed from the specific PostgreSQL default representation (for example: {Georges,Germaine,"Cloé, Tulip","Henri Charles"}) to a JSON representation (for example: ["Georges","Germaine","Cloé, Tulip","Henri Charles"]). This could be a problem for custom plugins relying on that format.

I don't quite follow this. Do you mean so that the tables are usable in older QGIS versions?

**Comment by pvalsecc** [comment]
@nyalldawson, Yes, the current version of QGIS can work with tables containing array types. It just shows them as strings looking like in my example. If you edit them with the correct syntax, it works.

If I have no negative feedback by tomorrow morning about using QMap and QList internally, I'll change the QEP in that direction.

**Comment by nyalldawson** [comment]
The array/map proposal looks like it's on the right track for me! @m-kuhn or @3nids would be best to advise on the proposed editor widget changes.

Can you add a section outlining what tests you'll be adding too? I think for adding a new field type we should have tests covering:
- handling of the type in QgsField/QgsFields/QgsFeature
- individual provider test cases for each provider that supports the data type (read + write)

**Comment by mhugo** [comment]
@pvalsecc Nice proposal.
I am not sure to understand why an editor widget would "barely" support a given type ? What kind of use cases do you have in mind ?

> The QgsEditorWidgetRegistry::findBestMatch looks if this table exists in the database of the given layer

How do you see that ? A connection to the database from the layer url ? Or new methods to vector data provider ?

I wonder if the mapping between a field and its editor widget (extra type information) could be made through typeName() and comment(), i.e. without the need of an auxiliary metadata table ?

**Comment by ninsbl** [comment]
Nice ideas! Probaly related to: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/37 ?

**Comment by pvalsecc** [comment]
@mhugo, this rating would be reserved for TextEdit. Let's take an example for an enumerated type in PostgreSQL. TextEdit can "barely" support it, but a specialized "EnumEdit" could, in the future "perfectly" support it.

The way to get the connection to the DB has not been investigated for the moment. There must be a way, since the style of a layer can come from a table. If I am going to that level of details, I'm doing a PR instead of a QEP ;-)
I guess I can get the `QgsVectorDataProvider` from the `QgsVectorLayer` and ask it. At least add a method to do it, that returns null for providers that don't know about that.

Your proposal to go through typeName() is not working. Imagine a `color` column in a table. In PostgreSQL, it will be stored as an int4 and that would be the content of typeName. So you want to be able to ship your DB with some info saying that this column of this table is actually to be used with the "ColorEdit" widget (to be implemented). The comment() one is dangerous. This stuff could be used in existing applications for other purpose and recycling it would mess it up. But, I could add another attribute to it and transmit this value in there.

**Comment by mhugo** [comment]
> this rating would be reserved for TextEdit. Let's take an example for an enumerated type in PostgreSQL. TextEdit can "barely" support it, but a specialized "EnumEdit" could, in the future "perfectly" support it.
Is it equivalent to say each editor widget maps to some types and if no widget is found for a type, it is considered as text ?

About the metadata table, thanks for the clarification. Indeed comments() is not very clean. Maybe it is too early to state on this, but adding a new property to QgsField or QgsEditFormConfig to get the widget type from the provider may be considered.

Anyway, +1 from me for this proposal :)

**Comment by pvalsecc** [comment]
OK, updated:
- Switched the internal representation to QMap/QList when possible
- Added info about tests
- A few details here and there

What's the next steps? I'm new to this process and I'm not sure how the voting is done and where it is recorded. Anyway, it's vacation period... I guess I have to leave it up longer than a week, isn't it?

**Comment by m-kuhn** [comment]
Nice initiative!

> Add a virtual method to QgsEditorWidgetFactory allowing a factory to tell how good it is to edit/represent a given field.

There is already `bool QgsEditorWidgetFactory::supportsField()` which is there fore the same purpose. If you introduce a new method that is more precise than this simple boolean, better remove this one (it's 3.0 time 😄  ).
I'd probably return an integer and start with values like 50 and 100 (i.e. not 1, 2, 3) this way there's enough space between the values to reorder them easily down the road also for 3rd party contributed widgets.

Concerning maps, it would be nice to be able to "promote" certain map values to look like real fields to QGIS. If you know there will be in all features a map key (e.g. "image_path") you can just promote that to a real field, QGIS will offer it as such throughout the API and load/write it to/from the map transparently. It's just an idea I had once and can easily be added later on.

> Widget types from a table
> The place in the code where the data for that will be collected is not yet determined.

We have a similar project upcoming in the next months. We will be doing this as a plugin/python code. The decision to implement this as a python extension was taken based on the fact that there are a lot of schemas (In Switzerland there is Interlis which also contains useful information which cannot always be mapped to postgres databases but can help to identify suitable widgets. Interlis is then preprocessed by yet another tool which adds yet more interesting information. In the EU it's interlis and I'm sure other countries have different schemas.). Do you think it would also work for you to keep this code separate?

**Comment by pvalsecc** [comment]
@m-kuhn,

> There is already bool QgsEditorWidgetFactory::supportsField() which is there fore the same purpose.  If you introduce a new method that is more precise than this simple boolean, better remove this one (it's 3.0 time :smile: ).

The idea was that supportsField would call the new method by default. But I have nothing against removing it.

> I'd probably return an integer and start with values like 50 and 100 (i.e. not 1, 2, 3) this way there's enough space between the values to reorder them easily down the road also for 3rd party contributed widgets.

OK

> Concerning maps, it would be nice to be able to "promote" certain map values to look like real fields to QGIS. If you know there will be in all features a map key (e.g. "image_path") you can just promote that to a real field, QGIS will offer it as such throughout the API and load/write it to/from the map transparently. It's just an idea I had once and can easily be added later on.

IMHO, this is already solved by the field calculator. Just add new fields with expressions taking the values from the map.

> Do you think it would also work for you to keep this code separate?

I'd rather put a decent behaviour in the core, adding possible hooks for plugins to add more. For example, you don't use the widget type table, but you have a plugin registering itself so that `findBestMatch` offers it the possibility to choose the type.

**Comment by m-kuhn** [comment]
> IMHO, this is already solved by the field calculator. Just add new fields with expressions taking the values from the map.

That will only allow reading, no? Adding write support for virtual fields would of course be a nice enhancement too, but I'm not sure it's trivial.

> I'd rather put a decent behaviour in the core, adding possible hooks for plugins to add more. For example, you don't use the widget type table, but you have a plugin registering itself so that findBestMatch offers it the possibility to choose the type.

That sounds good.
And whatever is provider specific (postgres metatables) can be safely put there.

**Comment by eronlloyd** [comment]
Has there been any progress on this? I would definitely chip in towards sponsoring this enhancement!

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
