### ISSUE TITLE
QEP 70: Multi map canvas for QGIS

### ISSUE THREAD

**Issue by ahuarte47** [qgis/QGIS-Enhancement-Proposals#70]
# QGIS Enhancement 70: Multi map canvas for QGIS

**Date** 2016/09/08

**Author** Alvaro Huarte (@ahuarte47)

**Contact** ahuarte47 at yahoo dot es

**maintainer** @ahuarte47

**Version** QGIS 3.0
# Summary

QGIS manages only a map (QgsMapCanvas class) and maptools and plugins work with it reading or editing its properties. The reference to this MapCanvas is provided by the QgisApp singleton instance and it doesn't change upto QGIS closes. Also, the user can't create new extra maps with their own layers (a project only manages a map).

This is partially fullfilled by [DockableMirrorMap](https://plugins.qgis.org/plugins/DockableMirrorMap/) and other auxiliary plugins.
## Proposed Solution

Support this feature in core, QgisApp will allow you to create and remove maps and will change the references to new active map canvas. The application have to provide to maptools and plugins some methods to query and manage the current collection of maps of the application.

The code will try to minimize the implication of this new capability using an automatic mechanism of sinchronization of the connection of slots and signals to new active map canvas. 

In my proposed solution, MapTools automatically take care of this since QgsMapTool base class overrides the [QObject::connect()](http://doc.qt.io/qt-5/qobject.html#connect) and [QObject::disconnect()](http://doc.qt.io/qt-5/qobject.html#disconnect) methods to allow this automatic synchronization of references.

See experimental code: 
https://github.com/qgis/QGIS/pull/3465
### Example(s)

See video demo with results of this experimental branch:
https://vimeo.com/179982647
### Affected Files

Only the main tools of QGIS have been reviewed. Therefore there will be more files of other tools or plugins to change.
## Performance Implications

This should not have significative implication on performance.
## Further Considerations/Improvements

When the project saves non-floating maps, it saves the [full window state and geometry](http://doc.qt.io/qt-5/restoring-geometry.html) of the application. 

Currently Qt does not provide a method similar to [restoreDockWidget()](http://doc.qt.io/qt-4.8/qmainwindow.html#restoreDockWidget) method to restore as better as possible the state of a specific widget (a widget with a map) without change the full window state of the application. Therefore, the loading of a project with non-floating maps may cause that windows previously closed appear, or visible windows disappear.
## Backwards Compatibility

MapTools and plugins where there is currently an implicit assumption that only one canvas exists, must be revised. MapTools and plugins that need to update their own settings when the active canvas changes, must be edited as well.
## Issue Tracking ID(s)

_(optional)_
## Votes

(required)

**Comment by wonder-sk** [comment]
Hi @ahuarte47 thanks for starting the QEP. Would it be possible to explain the technical details in greater details, so it is possible to understand all the important concepts without going through the associated pull request? For example: how layer tree is affected, how switching of active canvas works (from both user's and developer's point of view), how composer is affected, how QgisInterface would be changed, what changes are required in existing map tools ...

**Comment by nyalldawson** [comment]
I had a look at the demo video - certainly some very nice stuff and along the right track!

My main concern: I think it's a mistake to have separate layers in each canvas. This will lead to many unexpected issues for users, such as having different edit buffers for a single datasource within the different canvases, having different selections between the canvases, etc. 

I think a better approach would be either:

1. Have shared layers/layer tree for all canvases. Individual canvases can have different visible layers and styles for layers, but they all work with a single layer registry and one copy of each layer. This approach could also resuse the existing visibility preset ("map theme" in 3.0) support which we already have - ie canvases are effectively showing a preset which defines the visible layer, layer order and layer styles.

2. Split the concept of layers away from the layer tree. Follow the MapInfo approach of an open layer lists, with individual layers not necessarily present in any canvas but still interact-able via a "open layer" panel.

I believe @manisandro has been doing a lot of work on this for Sourcepole's albiro fork - while it would be impossible to forward port their changes I'd love to hear his thoughts on the approach to take and what issues they had to resolve in their implementation.

**Comment by nyalldawson** [comment]
It also might be worthwhile if we collate a list of desired features from multi-canvas (ie different use cases) so we can use this to drive the design. @timlinux I'm expecting you to have lots of ideas on this ;)

**Comment by andreasneumann** [comment]
How about effects on QGIS server? So far, there is only one map in the project. When there are multiple maps in the project, which map does QGIS server use in the WMS requests? Just the first one? Or can one specify which map the request is relating to as a vendor specific extension? What would the GetProjectSettings request return?

**Comment by nyalldawson** [comment]
@andreasneumann That's a reason why it could be good to tie this in to the presets. If canvas settings were exposed in the same way as presets then server could be extended to support specific map preset (and canvas) styles

**Comment by andreasneumann** [comment]
@nyalldawson - I agree that coupling a canvas with a visibility preset and a global/shared layer tree would be a good idea.

**Comment by manisandro** [comment]
In the Albireo implementation we did the following: 
- We share the layers between all map canvases.
- The secondary views have a menu to toggle the visibility of the individual layers, but the remaining layer management needs to be done in the layer tree of the master view.
- Secondary views don't allow any other tool than the pan tool. This was rather to avoid UI consistency issues resp. to avoid needing to introduce the concept of an "active view" rather than actual technical issues.
- The most difficult part is handling of annotation items. In the end we opted for adding a `clone` method and an itemUpdated signal to the annotation items. Every time the item is updated (i.e. a property changed), a new clone is added to the child views and any previous clone deleted. It works well enough though it is a bit laggy when the user moves the item.

**Comment by nyalldawson** [comment]
Thanks @manisandro - that's really valuable feedback! Does Albireo support different crs per canvas?

**Comment by luipir** [comment]
Great enhancement Alvaro :)
About comments by @nyalldawson I can say that the plugin Dockable Mirror Map evolved from a complete synch canvas to the default one, to a way to select different layer visualization and zoom level. Last pull requests was to fix zoom proportion (kind of 2x respect default canvas).
Basing on this, I'm not sure that multiple layers three would be a problem. Probably your right can be confusion for common use cases. I believe this is a good functionality that can be hide by default (use same ans sync layer three) and forced only by user (split layer three) .

**Comment by nyalldawson** [comment]
I'm ok with multi layer tree *widgets* - but IMO they should share a common set of layers.

**Comment by manisandro** [comment]
@nyalldawson No, but I don't expect any technical issues in having different CRS

**Comment by ahuarte47** [comment]
@wonder-sk, about some detail of how QGIS works...

Layer tree shares the layers between all map canvases as usual, and the layer registry behavior remains without changes. I created a new LayerMapGroupTreeNode class that inherits from current LayerGroupTreeNode to simply indicate that its child nodes are showed in an map canvas.

The user activates a map canvas from legend tree selecting this node, or any child node. When the user moves the cursor over a map canvas, it temporally becomes active until the cursor leaves of this window. This work is done in the QgisApp singleton instance.

**Comment by ahuarte47** [comment]
Hi @andreasneumann, I can't reply a correct answer for this question. Now, I didn´t tests or changes for the QGIS Server context.

The multimap support is defined in a global setting disabled by default. In this state I tried preserve the current behavior. QGIS only manages the default map although the project contains configuration for more than one map canvas (QGIS only loads the data of the first canvas, ... the default or main map canvas).

Sorry for my terrible english :-(

**Comment by vmora** [comment]
In our use cases, the second map has a different CRS (wich is not a standard projection), for the moment the **map projection is at the projet** level, IMO it should go down to the canvas level (I had some issues with my second canvas returning to the project crs instead of the one we specified).

The legend with a different symbology for each canvas will be a bit crowded, IMO the **layertreeview per canvas** (tabbed) will be more practical than extending the current view.

To handle all layers in the registry, another widget would be usefull (drag/drop layers from there to the layertreeview of the canvas you want them in).

So +1 @luipir for multiple widget that are views on the same tree as @nyalldawson proposed, if my understanding is OK, or of different trees.

We also have a fairly **complex transform/filtering of the layer data** to display them in the other canvas, so we use memory layers in the second canvas with auto sync on edit (and we cheat on CRS, which is dirty, but works aroud the project CRS issue above). It would be nice to have a mechanism to do that cleanly in a plugin (OTF is there, but it would need to be slightly modified and custom transformation allowed for plugins).

I wonder if the different symbology means a different layer with the same datasource (data changes should be syncced from there). But a datasource instance is not really shared between layers for the moment.

**Comment by ahuarte47** [comment]
At 03:20 of the [video](https://vimeo.com/179982647) you can see how it works now. The UI actions use the active map canvas.

**Comment by nyalldawson** [comment]
> Layer tree shares the layers between all map canvases as usual, and the layer registry behavior remains without changes. I created a new LayerMapGroupTreeNode class that inherits from current LayerGroupTreeNode to simply indicate that its child nodes are showed in an map canvas.

Ok, that's good! Looks like I misunderstood how this was implemented. So my next question: in the demo video you add individual layers to each map separately. Does you implementation have support for adding existing layers which are visible in another canvas to a different canvas? In the demo you add the same layer to a different canvas by going through "add vector layer", but this will add the layer to the registry a second time.

And then we'd also need to decide on the behavior of closing layers. Is a layer removed from the registry only when it is removed from all maps? Should we separate the concept of removing a layer from closing layers (ie remove would just remove it from one canvas, close would remove it from all canvases). 

Another thing I noticed while quickly flicking through the code is that you're using the map canvases within composer. This shouldn't be done - it mixes the gui code into the core library. I'm aware that there's currently a hack in place which does this to get canvas items displayed, but that's on my todo list for qgis 3 (see https://github.com/qgis/qgis3.0_api/issues/59). Instead I think the multicanvas should be exposed to composer via the preset drop down - ie you can select whether you want the map to follow a preset OR follow a canvas. That's another reason why I think that multicanvas and map theme presets should be tightly entwined. 

(CRS selection could be handled separately - there's no reason a composer map should be forced to follow the canvas crs or require multiple canvases to have multiple maps in a composition with different CRS. )

**Comment by ahuarte47** [comment]
Hi @nyalldawson, 

> Ok, that's good! Looks like I misunderstood how this was implemented. So my next question: in the demo video you add individual layers to each map separately. Does you implementation have support for adding existing layers which are visible in another canvas to a different canvas? In the demo you add the same layer to a different canvas by going through "add vector layer", but this will add the layer to the registry a second time.
> 
> And then we'd also need to decide on the behavior of closing layers. Is a layer removed from the registry only when it is removed from all maps? Should we separate the concept of removing a layer from closing layers (ie remove would just remove it from one canvas, close would remove it from all canvases).

I didn't changes in the managament of layers, the trick of all commit is that when a MapCanvas is activated (from legendtree or mouse hover or ...) I change the reference of [QgisApp::mMapCanvas](https://github.com/qgis/QGIS/pull/3465/files#diff-989db6afac5dc91e42cf6d3e404431b3R7090) and all work as usual in QGIS. If QGIS is about to add a layer, the layer is added to the layerset of the current map canvas, and so on. Sorry for the confusion about that I use the same layer in the video.

> Another thing I noticed while quickly flicking through the code is that you're using the map canvases within composer. This shouldn't be done **it mixes the gui code into the core library**. I'm aware that there's currently a hack in place which does this to get canvas items displayed, but that's on my todo list for qgis 3 (see qgis/qgis3.0_api#59).

You are right, I should change it.

**Comment by ahuarte47** [comment]
I know three issues to fix:
- DragDrop always add the files to current map canvas, QGIS doesn't use the canvas where the cursor is.
- When the dockwidget containing a map canvas is floating, and it is focused, QGIS should active it in the legend tree.
- Remove references of map canvases within composer (Nyall's advice).

I know you are deciding what to do with this experimental branch, and it is possible that it never to be  merged. But, do you agree I fixing bugs, or is it still too early for that?

**Comment by nyalldawson** [comment]
I'd say too early to spend much time polishing this. We need to make sure the design is accepted by all interested parties first.

**Comment by ahuarte47** [comment]
ok, thanks to all for your review!

**Comment by saberraz** [comment]
With support for multi-styles for layers and Presets, QGIS already comes with a "virtual multi-canvas".

I know it is a bit difficult for some users to wrap their heads around the way things are done with the above method, but 0 from me for having an actual multiple canvas support. Plus, there is already a plugin to allow user to have multiple canvas.

OTH, having 3D canvas in future will be a great step forward.

**Comment by ahuarte47** [comment]
Hi @saberraz, thanks for your comments, I see "this" multiple canvas support complementary to current "multi-style and presets" combination. IMHO it can be more straightforward to use and QGIS could supports a bit different project types. With this commit, each new data source creates a new layer instance as if I add a layer twice. Then each map allow to define your full own layer settings (projection, OTF, fields settings (alias, visibility)...)

**Comment by interob** [comment]
Maybe I am taking things to far,, but IMO it would be best to split up the concept of "layer" into "datasource" and "layer". A datasource then is the specific context in which a Provider is being used; a QGIS project has a collection of datasources that is shared between all map canvases.  A layer then is the link between a datasource and a canvas, holding things like visibility, styling etc. etc; each canvas has its own collection of layers.
I am aware that this approach will have a major impact on the code... Yet, I think it's worth it.
