### ISSUE TITLE
QEP 71: Save/restore colorramp name for singleband pseudocolor renderer

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Enhancement-Proposals#71]
# QGIS Enhancement 71: Save/restore colorramp name for singleband pseudocolor renderer

**Date** 2016/09/08

**Author** Alexander Bruy (@alexbruy)

**Contact** alexander dot bruy at gmail dot com

**Maintainer** @alexbruy

**Version** QGIS 3.0
# Summary

Currently "Singleband Pseudocolor" renderer does not save name of the color ramp used for classification. So when user worked with multiple rasters and wants to modify classification settings for one of the rasters, he may forgot which color ramp was used for current raster.
## Proposed Solution

This can be fixed easily by saving not only color map but also name of the original color ramp used for classification. Name of the color ramp also should be exported to the QML file and restore from it when style applied to raster layer.

Draft implementation can be found at https://github.com/alexbruy/QGIS/tree/save-colorramp
### Affected Files

Affected files are:
- src/core/raster/qgsrastershader.cpp
- src/core/raster/qgscolorrampshader.h
- src/core/raster/qgscolorrampshader.cpp
- src/core/raster/qgssinglebandpseudocolorrenderer.cpp
- src/gui/raster/qgssinglebandpseudocolorrendererwidget.cpp

Also `colorrampshader` element of the QML files will be modified with addition of new attribute containing name of the color ramp.
## Backwards Compatibility

Backward compatibility will be kept. New QML files will have additional attribute, if this attribute is not found — default color ramp will be used.
## Votes

(required)

**Comment by NathanW2** [comment]
+1 that always seemed strange to me

**Comment by ghtmtt** [comment]
+1 that could be really useful

**Comment by hamiltoncj** [comment]
+1 that issue has frequently caused me problems. I hope it will be fixed.

**Comment by alexbruy** [comment]
Merged in master in qgis/QGIS@2497375ee95c5eb3046a8316793adf75c4ef1768

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
