### ISSUE TITLE
QEP 72: QgsMapCanvasCustomMap item for fast refreshing map layers

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#72]
# QGIS Enhancement 72: QgsMapCanvasCustomMap item for fast refreshing map layers

**Date** 2016/09/10

**Author** Nyall Dawson @nyalldawson

**Contact** nyall@north-road.com

**maintainer** Nyall Dawson

**Version** QGIS 3.0
# Summary

The map map renderer within QGIS is designed to render multiple map layers in one pass, allowing for
interaction between the layers (such as labels from one layer avoiding overlap with the features from
another layer). While this approach works well for “basemap” style map renders, it does not work well for rendering dynamic layers with frequently changing features and geometry. The map refreshes require all layers to be re-rendered and re-composited, resulting in a “flashing” appearance with each map redraw.

This proposal covers implementing a new type of canvas item designed for rapidly refreshing map layers without visible redraw “flashing” effects.

While it's currently possible to achieve a similar result using a workaround of multiple map canvases (see eg https://gist.github.com/nyalldawson/1b389d87e2c70ef44bd7307365217dbc - credit to Nathan Woodrow for the original inspiration to the gist), this approach has shortcomings such as the additional canvases obscuring canvas items which should be drawn above all map items (eg identify highlights and map tool rubber bands). 
## Proposed Solution

The proposed solution consists of implementing a new type of QgsMapCanvasItem, specifically for rendering isolated map layers which can be refreshed and repainted without affecting other map layers or requiring a full map redraw.
The new item type, `QgsMapCanvasCustomMap`, is designed for use by plugin developers **only** and will not be accessible or configurable by end users. It will be exposed via the c++ and PyQGIS APIs, and will have no graphical GUI within the QGIS app for configuring or controlling which layers are displayed in this way. It will be left to QGIS plugin developers to implement use of QgsMapCanvasCustomMap within their plugins as required.

QgsMapCanvasCustomMap will render its contents on request, based on a specified subset of the project's map layers. The rendering will be isolated from the main map canvas render, so no interaction will be possible between the rendering of the main canvas and the contents of the QgsMapCanvasCustomMap. This includes label collision detection, so for instance labels from the layers within the QgsMapCanvasCustomMap may overlap labels and features from the underlying base map layers. 

Additionally, QgsMapCanvasCustomMap items will always be rendered above the underlying base map, so it will not be possible for layers from the base map to be drawn above layers in the
QgsMapCanvasCustomMap. 

To aid with use of animated, frequently refreshed QgsMapCanvasCustomMap items the rendering results of a QgsMapCanvasCustomMap will be cached and will only be redrawn following a completed render of the contents of the custom map item. Ie, the results of the previous render will be persistently shown on screen until the new render results are ready, avoiding any redrawing “flicker” effects.

Additionally, the z value for existing canvas items will be predefined to ensure correct placement of rubbers bands, etc when QgsMapCanvasCustomMap items are present in the scene.
## Backwards Compatibility

N/A - this work will be targeted to QGIS 3.0 alone and will not be backported. Additionally, it will only be accessible though PyQGIS/c++ api and will not affect project files.
## Votes

(required)

**Comment by m-kuhn** [comment]
Is this just about the flickering or do you plan to do more with it in plugins?

For the flickering only I was thinking about another approach where each layer will be cached within its own QImage. When zooming/panning, the cached image is copied (zoomed/translated) onto a new cache image for the layer renderer. The layer renderer may now choose to dismiss an existing image (e.g. 2000 features of a vector layer have been rendered onto a pristine image) or just render on top of the prepopulated cache (fully opaque raster image).

I think the main difference of the two approaches are that the one you propose here is not necessarily on a single layer basis, it is based on a QGraphicsItem (right?) while mine would be all in raster images. What I am not sure about your approach is how compositing works with QGraphicsItems while I'm not sure about the implementation details concerning labelling with my approach.

**Comment by nyalldawson** [comment]
> Is this just about the flickering or do you plan to do more with it in plugins?

It's not just the flickering - it's also about being able to rapidly refresh just a subset of the map's layers.

> For the flickering only I was thinking about another approach where each layer will be cached within its own QImage. When zooming/panning, the cached image is copied (zoomed/translated) onto a new cache image for the layer renderer. The layer renderer may now choose to dismiss an existing image (e.g. 2000 features of a vector layer have been rendered onto a pristine image) or just render on top of the prepopulated cache (fully opaque raster image).

This sounds great - and would certainly help in a lot of cases.

> I think the main difference of the two approaches are that the one you propose here is not necessarily on a single layer basis, it is based on a QGraphicsItem (right?) while mine would be all in raster images. What I am not sure about your approach is how compositing works with QGraphicsItems while I'm not sure about the implementation details concerning labelling with my approach.

The big issue I see is with labeling. It's often the slowest part of the rendering and use of labeling in the dynamic layer (ie, the layer which needs to be rapidly updated) or in the base map layers will prevent use of the cache and cause an expensive refresh. By isolating the dynamic layer I'm hoping to avoid this - ie labels for the basemap could be complex and handle things like collision detection with other base map layers, but changes to the dynamic layer (and any labeling on it) will not impact the base map layers rendering. Ie - it's effectively just like rendering two separate maps and compositing them together, at the cost of potential label collisions between the base map and QgsMapCanvasCustomMap layers.


@mhugo based on our discussion last week I think you've hit a similar problem in the past. What's your thoughts on this approach?

**Comment by nyalldawson** [comment]
Just an aside - I've noticed that we're also extremely wasteful in rendering the map canvas and items. We aren't taking advantage of QGraphicsScenes/QGraphicsItem built in caching mechanism and instead are constantly redrawing items even with simple things like mouse movement over them. 

This is especially noticable when there's complex/many items in the scene. Eg identify a complex polygon and then watch QGIS ground to a halt. Or use the node editor on a complex polygon, make a large selection and again things crawl.

I was hoping this could be fixed with a simple `setCacheMode( QGraphicsItem::DeviceCoordinateCache )` call in the constructors of map items, but after testing this we also need a way of manually invalidating this cache (eg when the map settings change and a redraw is required). I couldn't find a straightforward way to do this.

**Comment by m-kuhn** [comment]
So the main issue is that for dynamic layers shown on a non-changing canvas extent labeling is the limiting factor?

There is also the problem with flickering map while navigation and in this scenario I am not sure that this approach is best because a slow base-layer will put a delay on the whole base layer group.

Why not treat the two things individually:

 * A concept of labeling groups (user configurable project setting) to reduce collision detection time for dynamic layers. Label groups can also be cached individually if it's of any help.
 * Caching based on a per-layer renderer notification, working on rastered images instead of the graphics scene.

That would have the advantage that things like compositing would not be affected by labeling performance deficiencies.

**Comment by mhugo** [comment]
@nyalldawson Yep I had a similar use case in the past. We wanted to be able to have background layers (with labels) and foregound layers with frequently refreshed features (including labels as well). I solved that by introducing a concept of "label layer" (labeling group would be ok :)) In an old branch here : https://github.com/mhugo/QGIS/tree/label_layer_dev (demonstrated here https://vimeo.com/152402776 )
Your approach seems good, but why don't you want the user to be able to set its own independent rendering groups ? do you see problems with my approach ?

**Comment by anitagraser** [comment]
I think this could be potentially very interesting for working with animations, e.g. in TimeManager.

**Comment by timlinux** [comment]
Just a note: @m-kuhn In the use case @nyalldawson is addressing, the overlay layer would not have labels and would render above the labels so there would not be any need to recompute label positions / establish label groups etc. in order to update the live overlay layer. A use case would be for example a vehicle moving along a road: you would not need to move labels aside as the vehicle progresses down the road its icon would simply draw over any existing map features and labels.

**Comment by m-kuhn** [comment]
@timlinux have a look at the video posted by @mhugo above, with an approach like this, labels can be put anywhere in the layer stack (also below other layers).

**Comment by timlinux** [comment]
@m-kuhn sorry for the slow reply. Yes that looks pretty much exactly like we wish to achieve. @t-hey what do you think?

**Comment by nyalldawson** [comment]
This can be closed now - an alternative approach was implemented in https://github.com/qgis/QGIS/pull/4110
