### ISSUE TITLE
QEP 73: Data definable label geometry

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#73]
# QGIS Enhancement 73: Data definable label geometry

**Date** 2016/09/13

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall@north-road.com

**maintainer** Nyall Dawson (@nyalldawson)

**Version** QGIS >= 3.0
# Summary

While current versions of QGIS include a very powerful and flexible labelling engine one use case which is not addressed is the ability to override a feature’s geometry for use within the label engine. Currently, the label engine always uses a feature’s original geometry when generating placement options for label candidates. In many cases this is not desirable, such as:
- when a feature’s geometry is complex and should be generalised or smoothed to allow optimal label placement
- when a manually created geometry should be used instead of the feature’s actual geometry for labelling, e.g. to create curved line based labels inside polygon water bodies
- altering label text (or appearance) for each label drawn from a multi-part input geometry (e.g. labelling each node in a line/polygon with its x/y value)

This proposal partially relates to the issues reported on the QGIS tracker at  http://hub.qgis.org/issues/1780 and http://hub.qgis.org/issues/3482

QGIS 2.14 introduced the ability to use a “geometry generator” style while rendering feature symbols, allowing for QGIS’ flexible expression engine to be used to specify geometric transforms (such as smoothing, translating, buffering, etc) to apply to a feature’s geometry prior to the symbol rendering for that feature. Geometry generators only apply to a feature’s symbology and do not affect labelling.
## Proposed Solution

The proposed solution to remedy this issue is to implement an expression based “label geometry generator”. Label generators will adopt a similar approach as the symbol geometry generators, and use geometry based expressions to modify the feature’s original geometry prior to labelling. Using the expression engine for geometry modification has proved to be a very flexible approach, and new geometry based functions are continually being added to the engine to increase its power.

The expression based approach will also allow for future expansion (not included in the scope of this
proposal) by allowing access to “secondary” geometry columns in supported data providers (such as PostGIS and spatialite). This would permit manual drawing of specific “labelling geometries” to be used solely for the label engine for specific features.
### UI Changes

Label geometry generators will be exposed to users through new options in the label settings GUI.  First, the label settings will be re-arranged to move some geometry-specific options from the “Rendering” tab to the “Placement” tab. Specifically, these are:
- the “Label every part of multi-part features” option
- the “Only draw labels which fit completely within feature” option (polygon geometries only)
- the “Suppress labelling of features smaller then” option
- the “Merge connected lines to avoid duplicate labels” option (line geometries only)

A new “modify label geometry” widget will be added to the placement tab. Like the symbology geometry generator configuration widget, this will allow users to specify the expected geometry type for the expression and enter a geometry expression (together with a button to show the full expression builder dialog).

Label geometry generators will only be applied when the corresponding check box is ticked. When ticked, the placement options in the tab will be updated to match the set “Geometry Type”. For instance, setting the type to “Polygon/Multipolygon” will show the placement options for polygons such as perimeter based placements, and setting the type to “Point/Multipoint” would show the point placement options (e.g. offset from point).

Note: there will be no support for mixed geometry type expressions (e.g., returning a centroid point for certain features and a polygons for others). If this setup is desirable then the supported approach would be to use rule-based labelling with two separate rules for the point and polygon based labels.
### Supported expressions

Expressions entered in the geometry expression widget will accept the standard syntax, functions and features supported in the QGIS expression engine. Accordingly, some sample expressions which could be used for labelling include:
- `buffer($geometry, -5 )`: buffer a polygon geometry inward by 5 map units, i.e. prevent labels from being placed within 5 map units of the polygon’s edge
- `smooth($geometry)`: smooths a linestring geometry for more gently curved line labels
- `line_interpolate_point($geometry, 3.75)`: places point labels at a distance of 3.75 map units along a linestring geometry
- `nodes_to_points($geometry)`: places labels at every node in a linestring/polygon geometry
- `intersection( $geometry, geom_from_wkt('POLYGON((100 100, 200 100, 200 200, 100 200, 100 100))'))`: clips a polygon geometry to a rectangular bounds, only allowing labels within this clipped region

The label geometry generator expression will apply before any other label placement option, i.e. the geometry is first calculated and then used for tests such as the “suppress labelling of features smaller than” and “only draw labels which fit completely within feature”.

When using geometry generators for symbology, QGIS allows use of the @geometry_part_count and @geometry_part_num expression variables for retrieving the total number of parts in the current multipart geometry and for retrieving the geometry current part number respectively. These variables can be used along with the geometry_n() function to retrieve properties of the current part of the geometry being rendered. These same expression variables will be made available for use with labelling geometry generators and for all labelling expressions and data defined overrides. By using these variables and functions it will be possible to achieve many advanced labelling approaches, such as labelling each node in a geometry with its corresponding x/y/z or m value, i.e., the combination of:

Label text expression: `z(geometry_n($geometry, @geometry_part_num ))`
Label geometry expression: `nodes_to_points($geometry)`
### Additional work

As part of this work QGIS’ handling of labelling multipart geometries will be refined. Development of the geometry generators will require major refactoring of multipart labels, so this opportunity will be used to fix some deficiencies in the current code. For instance, currently the option to “label every part of multipart geometries” does not respect any minimum feature size set for labels. This will be addressed as part of this proposal.

One important consideration for rendering multiple label for a single multipart geometry is correct handling of label obstacle geometries. Careful consideration will be made while developing this proposal to ensure that labels for each part of a multipart will correctly avoid being placed over the rendered symbol for a geometry where inappropriate.
## Backwards Compatibility

N/A - label geometry generators will not be backwards compatible
## Issue Tracking ID(s)

Relates to:
http://hub.qgis.org/issues/1780
http://hub.qgis.org/issues/3482
## Votes

(required)

**Comment by snow-raven** [comment]
Could also be useful if the polygon created by displaying the "layout extents" under "decorations" could be used as one of the geometries? Would potentially assist with managing labels for eventual layout display. (Forgive if this already exists, I'm still getting used to 3.4)
