### ISSUE TITLE
Lock layer and layout

### ISSUE THREAD

**Issue by GISsimbology** [qgis/QGIS-Enhancement-Proposals#81]
# QGIS Enhancement: Lock layer and layout

**Date** 2016/11/08

**Author** Luca Lanteri (@user)

**Contact** l.lanteri@arpa.piemonte.it

**maintainer** @user

**Version** QGIS X.X

# Summary

PCAV suggest to me to write this request here.
I frequently need to provide to my users a project with preset layer, view and layout, but they always touch part of the the project (deleting or modifying layers or layouts) that they should'n not do.
I would like to fund the development of a new feature that allows to provide a project with some locked layers and  layout that can be changed only by master password. I don't need any high security level for the password, it is only a way to prevent involuntary modify.
Do you think this is a possible approach? A way can be to develop first a plugin and then migarte it into the 3.0 core ?

## My Section

(optional) Insert custom sections wherever needed

## Proposed Solution

Insert a lock properties on layer  and layout properties

### Example(s)

(optional)

### Affected Files

(required if applicable)

## Performance Implications

**(required if known at design time)**

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

NO

## Issue Tracking ID(s)

*(optional)*

## Votes

??

**Comment by pcav** [comment]
Sounds quite reasonable to me.

**Comment by NathanW2** [comment]
I think this idea is fine although I think this needs to be fleshed out
more if you want to do it as a QEP.

**Comment by GISsimbology** [comment]
ok, I try to write more detail in the QEP.

**Comment by NathanW2** [comment]
I think this needs to be made as a feature request on hub.qgis.org until you have more design details.  QEPs should mainly be used as a design document.
