### ISSUE TITLE
QEP: 87 Restore legend customisation from composer templates (hub #2738)

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#87]
# QGIS Enhancement 87: Restore legend customisation from composer templates

**Date** 2017-01-10

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall.dawson@gmail.com

**maintainer** @nyalldawson

**Version** QGIS 2.18/3.0

**Sponsor** Faunalia, on behalf of ENEL

# Summary

As described in http://hub.qgis.org/issues/2738, when creating a composer from a template containing a legend with customisation (ie, auto update unchecked) no legend entries are restored.

Given that templates may be used for any project and these projects may not necessarily have the same layers present as the original project where the legend was customised, restoring these legend customisation is tricky. This QEP describes a possible approach to allow the customisations to be retained where possible.

## Proposed Solution

Currently, legend customisation is stored inside projects using layer IDs. When creating a new composer from a template designed in another project, these layer IDs do not match the layer IDs in the current project and accordingly the legend customisation is discarded.

The proposed logic to retain these customisations is :

When saving a legend's state to XML:
- store the layer's QgsMapLayer::publicSource() in addition to the layer ID for each legend layer node

When restoring a legend's state from XML:
1. check if a layer with matching ID exists in the project - if so, attach legend to that layer
2. if the legend node has the publicSource stored, then check whether layers exist in the project with this same publicSource. If so:
- if a single layer exists with the matching source, attach the legend to that layer
- if multiple layers exist in the project with a matching source, discard the customisation (alternatively, the legend could just be attached to the first matching layer with an equal source)

This approach would allow templates containing customised legends to "re-attach" to matching layers when loading the template in another project. It only applies to projects with the SAME layer - so a legend for a similar layer stored in a different location would NOT be restored with the template.

The customisation would only be restored for templates created in QGIS versions where the fix is implemented, so any existing templates would not be able to restore legend customisation until the template is updated in a future QGIS release with this fix.

## Issue Tracking ID(s)

http://hub.qgis.org/issues/2738

## Votes

(required)

**Comment by anitagraser** [comment]
If I understand the proposal correctly, it would check first the layer id and - if that does not match - then the layer source. Should it also try to check if the layer style is similar, i.e. would the legend even match?

**Comment by pcav** [comment]
+1 for me (but I'm obviously biased)

**Comment by nyalldawson** [comment]
> If I understand the proposal correctly, it would check first the layer id and - if that does not match - then the layer source. Should it also try to check if the layer style is similar, i.e. would the legend even match?

You mean something like:

project 1:
d:/layer.shp styled using graduated renderer

save composer template with customised legend

project 2:
d:/layer.shp styled with categorised renderer
restore template from project 1

?

I believe the existing legend code (with the proposed changes) would already handle this and result in any invalid legend symbol nodes being dropped.

**Comment by anitagraser** [comment]
@nyalldawson Yes, that's the case I was thinking of.

**Comment by DelazJ** [comment]
> if multiple layers exist in the project with a matching source, discard the customisation (alternatively, the legend could just be attached to the first matching layer with an equal source)

What about checking visibility of the matching layers? That said, I wonder if user takes care of layer's visibility before importing a template.

**Comment by wonder-sk** [comment]
My thoughts (briefly discussed with Nyall today):
- I would do matching of layers based on triplets: layer name + data source + provider key
- I would not try to match layer IDs to the current project's layer IDs - it will be always a hit or a miss - rather I would always do matching by the triplets
- the problem of missing layers is not specific just to custom legend, but also to composer maps with custom layers. Moreover, layers themselves can have dependent layers or layers that are joined to them.
- all layers referenced in composer template should IMHO have their definition stored in the composer template too. They can be either matched to the layers of the current project (using the triplets mentioned above) and user can be notified that some layers are missing, optionally having the option to load the missing layers from the layer definitions
