### ISSUE TITLE
QEP 88: Developer Tools Window

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS-Enhancement-Proposals#88]
# QGIS Enhancement 88: Developer Tools Windows

**Date** 2017/01/29
**Author** Nathan Woodrow (@nathanw2)
**Contact** woodrow dot nathan at gamil dot com
**maintainer** @nathanw2
**Version** QGIS 3.0

# Summary

This QEP outlines the work of evolving the current Python Console into the full Developer Tools Window in order to improve the developer experience for QGIS. 

## Motivations

After some recent adventures back into plugin development, it has become clear that current story around plugin development in QGIS is very fragmented and quite difficult compared to other platforms.  This is currently due to a number of factors including many tools doing a single job but not integrated tightly.

- pb_tool
- makefiles
- plugin builder (Plugin)
- FirstAid (Plugin)
- Remote Debugger (Plugin)
- Plugin Reloader (Plugin)
- Core Python Console
- Core Message Log Window

Whilst all these tools do work normally for their set tasks due to the lack of integration the user experience is very fragmented and feels broken.  They all also hang off the main QGIS application window which means you are going to many different places to get your job done.

Even as an experienced QGIS dev this leaves me feeling frustrated. 

## Proposed Solution

The proposed solution is to borrow heavily from what Chrome has done with the internal developer tools and create a single one stop shop for everything QGIS developer related.

The solution will involve evolving the current Python console into a Developer Tools dock/window which has more features and better UX in order to aid in development.

The final solution will include the following features:

- Editor/Console Split
- List of all loaded plugins with source explorer
- Stack viewer on exceptions
- QGIS environment details
- Plugin Load time viewer
- API doc viewer
- SDK tools downloader.
- Setting extra plugin paths, and manually loading plugins for testing.
- Dock and Undock into a full screen window.

UI mocks to come soon.

### Example(s)

If you haven't seen the Chrome tools before something like this:

![image](https://cloud.githubusercontent.com/assets/381660/22403517/4abf63c2-e665-11e6-9595-bc73db2afd82.png)

### Affected Files

Current console.py code will be expanded into a richer developer tools toolkit

## Votes

(required)

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
