### ISSUE TITLE
Processing documentation restyling

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS-Enhancement-Proposals#98]
# QGIS Enhancement: Restyling the Processing help layout

**Date** 2017/07/10

**Author** Matteo Ghetta (@ghtmtt)

**Contact** matteo.ghetta@gmail.com

**maintainer** @ghtmtt

**Version** QGIS 3.0

# Summary

Thanks to the recent Grant Proposal to enhance the Processing documentation, besides the algorithm text content (improving the existing docs with pictures and more detailed description, creating documentation from scratch, etc.) I'd like to discuss also the layout of current the webpages, e.g. for QGIS provider:

http://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/index.html

Right now there is a lot of *blank space* due to the section titles (Description, Parameters, Outputs, etc.) and the list formatting, especially for the **Parameter** section:

![selection_005](https://user-images.githubusercontent.com/2884884/28013424-47c84c00-6569-11e7-9dec-22d3d766b227.png)

The current layout brings to very very long and *ugly* pages for each Processing provider algorithm description.

## Proposed Solution
In order to make the layout cleaner and reducing page scrolling, the layout could be changed in different ways. 

1. Get rid or the redundant **Description** right after the algorithm name. Having the algorithm description right after the title is straightforward and no additional subtitle is needed:

   ![selection_006](https://user-images.githubusercontent.com/2884884/28013719-581f49cc-656a-11e7-97b9-c455283f2e9e.png)

2. Rearranging the **Parameters** section from the current list layout to a more cleaner table layout:

   ![selection_009](https://user-images.githubusercontent.com/2884884/28013924-121865fc-656b-11e7-939b-1841de1efd5e.png)

   **PROS**: layout more readable and cleaner, less blank space. Definitely better. 
   **CONS**: table are written together with [this tool](http://www.tablesgenerator.com/text_tables), given that it is very complicated to write large rst tables. Even with this tool, maintaining the tables (e.g. an additional parameter is added to an algorithm in a future release) is not handy at all. Moreover, having tables, forces the structure of all the parameters (e.g. the column ``Default Values`` is pretty much useless for the parameter ``layer in input``). 

## Further Considerations/Improvements
I'd like to raise this issue with all of you in order to have some more ideas on what the layout could be to become more *user friendly*.

Some consideration have been already made with some doc writers and dev (@DelazJ, @alexbruy, @yjacolin) but more comments and suggestions are more than welcome.

## Examples
Here 2 examples:

1. List layout: https://github.com/ghtmtt/QGIS-Documentation/blob/help_proc_vector_geom/source/docs/user_manual/processing_algs/qgis/vector_geometry_tools.rst

2. Table layout: https://github.com/ghtmtt/QGIS-Documentation/blob/help_proc_vector_geom_tables/source/docs/user_manual/processing_algs/qgis/vector_geometry_tools.rst

## Votes

(required)

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
