### ISSUE TITLE
Grouping of WxS and database connections

### ISSUE THREAD

**Issue by peterisb** [qgis/QGIS-Enhancement-Proposals#99]
# QGIS Enhancement: Grouping of WxS and database connections

**Date** 2017/08/05

**Author** Peteris Bruns (@peterisb)

**Contact** peteris.bruns@gmail.com

**maintainer** @peterisb

**Version** QGIS 3.X

# Summary

WxS services becomes more and more popular, connection item amount is growing. Existing listing of registered WxS services in interface for list with more than 20 items becomes inconvenient.

## Proposed Solution

Probably convenient solution would be to group Service and Database connections in groups defined by user. Would be enough with grouping in one level depth. That would requite one extra parameter/input in WMS, WFS, PostgreSQL, SqLite (probably some else) edit/add service/connection dialogue.

If group with exact name or similar name exists that would be shown in searchable/editable Combo box.
If entered group name does not exist it should be created.
In Browser panel should be possible to
* rename group (F2 ?)
* delete group with and without related connections
* with drag/drop move connection from one group to another inside connection type context
* Connection can be without group

### Example(s)

Result in browser panel
![grouped_in_browser](https://user-images.githubusercontent.com/2865324/28995886-6e87050e-79fd-11e7-98c0-d2aebf0feebc.png)

Edit/Create PostGIS connection with extra combo box for group
![pg_addgroup](https://user-images.githubusercontent.com/2865324/28995887-8affd544-79fd-11e7-939f-3489ceefae18.png)

Edit/Create WMS connection with extra combo box for group
![set_group](https://user-images.githubusercontent.com/2865324/28995890-9b1cd26a-79fd-11e7-8ab1-c88e7addc5d3.png)

Add service dialog combo box could be searchable (search in registered service name)
![serch_service](https://user-images.githubusercontent.com/2865324/28995894-c76e84b2-79fd-11e7-9923-cfc0833e1d71.png)

### Affected Files

ui/qgspgnewconnectionbase.ui
ui/qgsnewhttpconnectionbase.ui
ui/qgswmssourceselectbase.ui

maybe also
ui/qgsnewogrconnectionbase.ui

## Performance Implications

No implications

## Further Considerations/Improvements

Support of grouping in tree structures, add tags.

## Backwards Compatibility

This work is only intended to QGIS 3 branch and is not supposed to break compatibility

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
